/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.GeneralPanels;

import com.github.javafaker.Faker;
import courseroom.MainFrame;
import java.awt.Component;
import java.awt.Image;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import panels.StudentsPanel.StudentDashboardPanel;

/**
 *
 * @author LENOVO
 */
public class GeneralInfoProfilePanel extends javax.swing.JPanel {

    
    /**
     * Creates new form ProfilePanel
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public GeneralInfoProfilePanel() {
        initComponents();
        
        initMyComponents();
        
    }
    
    public void initMyComponents(){
        Component[] components = this.getComponents();
        for(Component component : components){
            component.setForeground(MainFrame.getFontColor());
        }
        
        jScrollPaneDescripcion.getViewport().setOpaque(false);
        jTextPaneDescripcion.setForeground(MainFrame.getFontColor());
        Faker faker = new Faker(new Locale("es","MX"));
        jLabelNombres.setText(faker.name().firstName() + " " + faker.name().firstName());
        jLabelApellidos.setText(faker.name().lastName() + " " + faker.name().lastName());
        jLabelCorreoElectronico.setText(faker.internet().emailAddress());
        jLabelLocalidad.setText(faker.address().fullAddress());
        jLabelNombreDeUsuario.setText(faker.name().username());
        jLabelNumeroTelefono.setText(faker.phoneNumber().cellPhone());
        jTextPaneDescripcion.setText(faker.lorem().paragraph());
        jLabelGenero.setText(faker.demographic().sex());
        jLabelFechaDeNacimiento.setText(faker.backToTheFuture().date());
        faker = null;
        
        ImageIcon imageIcon = new ImageIcon(StudentDashboardPanel.getUserImage());
        jLabelProfilePhoto.setIcon(imageIcon);
        jLabelNombres.setForeground(MainFrame.getSecondFontColor());
        jLabelApellidos.setForeground(MainFrame.getSecondFontColor());
        jLabelNombreDeUsuario.setForeground(MainFrame.getFontColor());
        imageIcon.getImage().flush();
        imageIcon = null;
        
        
    }
    
    public void colorMyComponents(){
        jLabelApellidos.setBackground(MainFrame.getThirdColor());
        jLabelApellidos.setForeground(MainFrame.getThirdFontColor());
        jLabelCorreoElectronico.setForeground(MainFrame.getFontColor());
        jButtonEditarPerfil.setForeground(MainFrame.getFontColor());
        jButtonEditarPerfil.setBackground(MainFrame.getFirstColor());
        jLabelFechaDeNacimiento.setForeground(MainFrame.getFontColor());
        jLabelGenero.setForeground(MainFrame.getFontColor());
        jLabelLocalidad.setForeground(MainFrame.getFontColor());
        jButtonMiDesempenoEscolar.setForeground(MainFrame.getFontColor());
        jButtonMiDesempenoEscolar.setBackground(MainFrame.getFirstColor());
        jLabelNombreDeUsuario.setForeground(MainFrame.getSecondFontColor());
        jLabelNombreDeUsuario.setBackground(MainFrame.getSecondColor());
        jLabelNombres.setBackground(MainFrame.getThirdColor());
        jLabelNombres.setForeground(MainFrame.getThirdFontColor());
        jLabelNumeroTelefono.setForeground(MainFrame.getFontColor());
        jLabelPerfil.setForeground(MainFrame.getFontColor());
        jLabelProfilePhoto.setForeground(MainFrame.getFontColor());
        jTextPaneDescripcion.setForeground(MainFrame.getFontColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProfilePhoto = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelNombres = new javax.swing.JLabel();
        jLabelNombreDeUsuario = new javax.swing.JLabel();
        jLabelCorreoElectronico = new javax.swing.JLabel();
        jLabelNumeroTelefono = new javax.swing.JLabel();
        jLabelPerfil = new javax.swing.JLabel();
        jLabelFechaDeNacimiento = new javax.swing.JLabel();
        jLabelLocalidad = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jScrollPaneDescripcion = new javax.swing.JScrollPane();
        jTextPaneDescripcion = new javax.swing.JTextPane();
        jButtonMiDesempenoEscolar = new javax.swing.JButton();
        jButtonEditarPerfil = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1085, 630));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1085, 630));

        jLabelProfilePhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProfilePhoto.setToolTipText("Imagen De Perfil");
        jLabelProfilePhoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelProfilePhoto.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabelProfilePhoto.setMinimumSize(new java.awt.Dimension(450, 450));
        jLabelProfilePhoto.setPreferredSize(new java.awt.Dimension(450, 450));

        jLabelApellidos.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabelApellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelApellidos.setText("Apellido(s) Del Usuario");
        jLabelApellidos.setToolTipText("Apellido(s)");
        jLabelApellidos.setMaximumSize(new java.awt.Dimension(380, 50));
        jLabelApellidos.setMinimumSize(new java.awt.Dimension(380, 50));
        jLabelApellidos.setName("label"); // NOI18N
        jLabelApellidos.setOpaque(true);
        jLabelApellidos.setPreferredSize(new java.awt.Dimension(380, 50));

        jLabelNombres.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabelNombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNombres.setText("Nombre(s) Del Usuario");
        jLabelNombres.setToolTipText("Nombre(s)");
        jLabelNombres.setMaximumSize(new java.awt.Dimension(380, 50));
        jLabelNombres.setMinimumSize(new java.awt.Dimension(380, 50));
        jLabelNombres.setName("label"); // NOI18N
        jLabelNombres.setOpaque(true);
        jLabelNombres.setPreferredSize(new java.awt.Dimension(380, 50));

        jLabelNombreDeUsuario.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        jLabelNombreDeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreDeUsuario.setText("Nombre De Usuario");
        jLabelNombreDeUsuario.setToolTipText("UserName");
        jLabelNombreDeUsuario.setMaximumSize(new java.awt.Dimension(430, 30));
        jLabelNombreDeUsuario.setMinimumSize(new java.awt.Dimension(430, 30));
        jLabelNombreDeUsuario.setOpaque(true);
        jLabelNombreDeUsuario.setPreferredSize(new java.awt.Dimension(430, 30));

        jLabelCorreoElectronico.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabelCorreoElectronico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCorreoElectronico.setText("correo.electronico@courseroom.com");
        jLabelCorreoElectronico.setToolTipText("Correo Electrónico");
        jLabelCorreoElectronico.setMaximumSize(new java.awt.Dimension(380, 25));
        jLabelCorreoElectronico.setMinimumSize(new java.awt.Dimension(380, 25));
        jLabelCorreoElectronico.setName("label"); // NOI18N
        jLabelCorreoElectronico.setPreferredSize(new java.awt.Dimension(380, 25));

        jLabelNumeroTelefono.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabelNumeroTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNumeroTelefono.setText("33-34-35-36-37");
        jLabelNumeroTelefono.setToolTipText("Número De Teléfono");
        jLabelNumeroTelefono.setMaximumSize(new java.awt.Dimension(163, 25));
        jLabelNumeroTelefono.setMinimumSize(new java.awt.Dimension(163, 25));
        jLabelNumeroTelefono.setName("label"); // NOI18N
        jLabelNumeroTelefono.setPreferredSize(new java.awt.Dimension(163, 25));

        jLabelPerfil.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabelPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPerfil.setText("Alumno");
        jLabelPerfil.setToolTipText("Tipo De Perfil");
        jLabelPerfil.setMaximumSize(new java.awt.Dimension(163, 25));
        jLabelPerfil.setMinimumSize(new java.awt.Dimension(163, 25));
        jLabelPerfil.setName("label"); // NOI18N
        jLabelPerfil.setPreferredSize(new java.awt.Dimension(163, 25));

        jLabelFechaDeNacimiento.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabelFechaDeNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFechaDeNacimiento.setText("2021-02-22 (18 Años)");
        jLabelFechaDeNacimiento.setToolTipText("Fecha De Nacimiento");
        jLabelFechaDeNacimiento.setMaximumSize(new java.awt.Dimension(163, 25));
        jLabelFechaDeNacimiento.setMinimumSize(new java.awt.Dimension(163, 25));
        jLabelFechaDeNacimiento.setName("label"); // NOI18N
        jLabelFechaDeNacimiento.setPreferredSize(new java.awt.Dimension(163, 25));

        jLabelLocalidad.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabelLocalidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelLocalidad.setText("<html>Blvd. Gral. Marcelino García Barragán 1421,<br>Olímpica, 44430 Guadalajara, Jal.</html>");
        jLabelLocalidad.setToolTipText("Localidad");
        jLabelLocalidad.setMinimumSize(new java.awt.Dimension(380, 60));
        jLabelLocalidad.setName("label"); // NOI18N
        jLabelLocalidad.setPreferredSize(new java.awt.Dimension(380, 60));

        jLabelGenero.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabelGenero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelGenero.setText("Mujer");
        jLabelGenero.setToolTipText("Género");
        jLabelGenero.setMaximumSize(new java.awt.Dimension(163, 25));
        jLabelGenero.setMinimumSize(new java.awt.Dimension(163, 25));
        jLabelGenero.setName("label"); // NOI18N
        jLabelGenero.setPreferredSize(new java.awt.Dimension(163, 25));

        jScrollPaneDescripcion.setOpaque(false);

        jTextPaneDescripcion.setEditable(false);
        jTextPaneDescripcion.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jTextPaneDescripcion.setOpaque(false);
        jScrollPaneDescripcion.setViewportView(jTextPaneDescripcion);

        jButtonMiDesempenoEscolar.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jButtonMiDesempenoEscolar.setText("Mi Desempeño Escolar");
        jButtonMiDesempenoEscolar.setToolTipText("Muestra Tu Desempeño Escolar & Predicciones De Estas");
        jButtonMiDesempenoEscolar.setBorder(null);
        jButtonMiDesempenoEscolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMiDesempenoEscolarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMiDesempenoEscolarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMiDesempenoEscolarMouseExited(evt);
            }
        });

        jButtonEditarPerfil.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jButtonEditarPerfil.setText("Editar Perfil");
        jButtonEditarPerfil.setToolTipText("Edita La Información De Tu Perfil");
        jButtonEditarPerfil.setBorder(null);
        jButtonEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEditarPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditarPerfilMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelProfilePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNombreDeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabelFechaDeNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonMiDesempenoEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPaneDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFechaDeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jLabelLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombreDeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMiDesempenoEscolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jLabelProfilePhoto.getAccessibleContext().setAccessibleName("jLabelProfilePhoto");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMiDesempenoEscolarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMiDesempenoEscolarMouseExited
        // TODO add your handling code here:
        jButtonMiDesempenoEscolar.setBackground(MainFrame.getFirstColor());
        jButtonMiDesempenoEscolar.setForeground(MainFrame.getFontColor());
    }//GEN-LAST:event_jButtonMiDesempenoEscolarMouseExited

    private void jButtonMiDesempenoEscolarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMiDesempenoEscolarMouseEntered
        // TODO add your handling code here:
        jButtonMiDesempenoEscolar.setBackground(MainFrame.getSecondColor());
        jButtonMiDesempenoEscolar.setForeground(MainFrame.getSecondFontColor());
    }//GEN-LAST:event_jButtonMiDesempenoEscolarMouseEntered

    private void jButtonMiDesempenoEscolarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMiDesempenoEscolarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMiDesempenoEscolarMouseClicked

    private void jButtonEditarPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarPerfilMouseEntered
        // TODO add your handling code here:
        jButtonEditarPerfil.setBackground(MainFrame.getSecondColor());
        jButtonEditarPerfil.setForeground(MainFrame.getSecondFontColor());
    }//GEN-LAST:event_jButtonEditarPerfilMouseEntered

    private void jButtonEditarPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarPerfilMouseExited
        // TODO add your handling code here:
        jButtonEditarPerfil.setBackground(MainFrame.getFirstColor());
        jButtonEditarPerfil.setForeground(MainFrame.getFontColor());
    }//GEN-LAST:event_jButtonEditarPerfilMouseExited

    private void jButtonEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarPerfilMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            StudentDashboardPanel.showView("editProfilePanel");
        }
        
    }//GEN-LAST:event_jButtonEditarPerfilMouseClicked

    public void setProfileImage(Image image){
        ImageIcon profileIcon = new ImageIcon(image.getScaledInstance(400,400,Image.SCALE_SMOOTH)); 
        jLabelProfilePhoto.setIcon(profileIcon);
        profileIcon = null;
    }
   
    public JLabel getProfilePhotoLabel(){
        return GeneralInfoProfilePanel.jLabelProfilePhoto;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarPerfil;
    private javax.swing.JButton jButtonMiDesempenoEscolar;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCorreoElectronico;
    private javax.swing.JLabel jLabelFechaDeNacimiento;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelNombreDeUsuario;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JLabel jLabelNumeroTelefono;
    private javax.swing.JLabel jLabelPerfil;
    private static javax.swing.JLabel jLabelProfilePhoto;
    private javax.swing.JScrollPane jScrollPaneDescripcion;
    private javax.swing.JTextPane jTextPaneDescripcion;
    // End of variables declaration//GEN-END:variables
}
