/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courses;

import chat.BoxChatPanel;
import data.collections.PairDoublyLinkedList;
import data.interfaces.MainInterface;
import data.structures.Pair;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.PixelGrabber;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import media.MusicPanel;



/**
 *
 * @author LENOVO
 */
public class InfoUserPanel extends javax.swing.JPanel implements MainInterface{

    private Color firstColor, secondColor, thirdColor;
    private Image userImage;
    
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public InfoUserPanel(String route) {
        initComponents();
        try {
            URL imageURL = new URL(route);
            userImage = ImageIO.read(imageURL).getScaledInstance(125,125,Image.SCALE_SMOOTH);
            ImageIcon chatIcon = new ImageIcon(userImage);
            jLabelImagenPerfil.setIcon(chatIcon);
            firstColor = Color.BLACK;
            secondColor = Color.BLACK;
            chatIcon = null;
            setColors(userImage);
            imageURL = null;
        } catch (MalformedURLException ex) {
            Logger.getLogger(BoxChatPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BoxChatPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagenPerfil = new javax.swing.JLabel();
        jLabelNombreAmigo = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(300, 250));
        setPreferredSize(new java.awt.Dimension(300, 250));

        jLabelImagenPerfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelImagenPerfil.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabelImagenPerfil.setPreferredSize(new java.awt.Dimension(130, 130));

        jLabelNombreAmigo.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabelNombreAmigo.setForeground(java.awt.Color.white);
        jLabelNombreAmigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreAmigo.setText("Nombre De Mi Amigo");
        jLabelNombreAmigo.setToolTipText("");

        jLabelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombreUsuario.setForeground(java.awt.Color.white);
        jLabelNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreUsuario.setText("Nombre De Usuario XX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelImagenPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(jLabelNombreAmigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelImagenPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombreAmigo)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setColors(Image image){
        
        try {
            Random colorRandom = new Random(System.currentTimeMillis());
           int maximum = 0;
            PairDoublyLinkedList<Integer, Color> colorList = new PairDoublyLinkedList<>();
            PixelGrabber pg = new PixelGrabber(image, 0, 0, -1, -1, false);
            
            if (pg.grabPixels()) {
                int[] pixels = (int[]) pg.getPixels();
                for(int i = 0; i < pixels.length; i++){
                    int pixel = pixels[i];
                    int  red = (pixel  & 0x00ff0000) >> 16;
                    int  green = (pixel & 0x0000ff00) >> 8;
                    int  blue = pixel & 0x000000ff;
                    Color color = new Color(red,green,blue);
                    Pair<Integer, Color> pair = colorList.get_from_second(color);
            
                    if (pair != null) {//exist
                        int number = pair.first()+ 1;
                        pair.first(number);
                        if (number > maximum) {
                            firstColor = color;
                            maximum = number;
                        }
                    } else {
                        colorList.push_back(1, color);
                    }

                    color = null;
                    i+= colorRandom.nextInt(401)+ 400;
                }

                secondColor = firstColor;
            
                int iterations = 0;
                if(colorList.size() > 1){
                    
                    while(Math.abs(secondColor.getRGB() - firstColor.getRGB()) < 3000000){
                        int position = colorRandom.nextInt((int)colorList.size()-1);
                        secondColor = colorList.get(position).second();
                        iterations++;
                        if(iterations > 25){
                             while(firstColor.getRGB() == secondColor.getRGB()){
                                position = colorRandom.nextInt((int)colorList.size()-1);
                                secondColor = colorList.get(position).second();
                            }
                             break;
                        }
                    }
                }
                

                thirdColor = secondColor;
                if(colorList.size() > 2){
                    iterations = 0;
                    
                    while(Math.abs(thirdColor.getRGB() - firstColor.getRGB()) < 3000000 || Math.abs(secondColor.getRGB() - thirdColor.getRGB()) < 3000000){
                        int position = colorRandom.nextInt((int)colorList.size()-1);
                        thirdColor = colorList.get(position).second();
                        iterations++;
                        if(iterations > 50){
                            while(thirdColor.getRGB() == firstColor.getRGB() || thirdColor.getRGB() == secondColor.getRGB()){
                                position = colorRandom.nextInt((int)colorList.size()-1);
                                thirdColor = colorList.get(position).second();
                            }
                            break;
                        }
                    }
                }
                
                int red = firstColor.getRed();
                Color fontColor = (red >= 155) ? Color.BLACK : Color.WHITE;

                colorList.clear();


                jLabelImagenPerfil.setForeground(fontColor);
                jLabelNombreAmigo.setForeground(fontColor);
                jLabelNombreUsuario.setForeground(fontColor);

                fontColor = null;
                colorRandom = null;
                colorList = null;
                fontColor = null;
                pg = null;
                pixels = null;
                this.repaint();
            }
            
        } catch (InterruptedException ex) {
            Logger.getLogger(MusicPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
 
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int w = this.getWidth();
        int h = this.getHeight();
        Graphics2D graphics = (Graphics2D)g;
        Color noColor =  new Color(0, 0, 0, 0);
        GradientPaint primary = new GradientPaint(0f, 0f, secondColor, w, 0f, thirdColor);
        GradientPaint secondary = new GradientPaint( 0f, 0f, noColor,0f, h, firstColor);
        graphics.setPaint(primary);
        graphics.fillRect(0, 0, w, h);
        graphics.setPaint(secondary);
        graphics.fillRect(0, 0, w, h);
        primary = null;
        secondary = null;
        noColor = null;
        graphics = null;

    }

    @Override
    public void dispose(){
        firstColor = null;
        secondColor = null;
        thirdColor = null;
        userImage.flush();
        userImage = null;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagenPerfil;
    private javax.swing.JLabel jLabelNombreAmigo;
    private javax.swing.JLabel jLabelNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
