/*
 * Copyright (C) 2022 LENOVO
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package paneles.profesores.chats;

import clases.Celda_Renderer;
import courseroom.CourseRoom;
import datos.interfaces.Carta_Visibilidad_Interface;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import paneles.generales.mensajes.Mensaje_Texto_Izquierdo_General_Panel;
import paneles.generales.mensajes.Mensaje_Texto_Derecho_General_Panel;
import paneles.generales.mensajes.Mensaje_Archivo_Derecho_General_Panel;
import paneles.generales.mensajes.Mensaje_Archivo_Izquierdo_General_Panel;
import datos.interfaces.Componentes_Interface;
import datos.interfaces.Envio_Interface;
import datos.interfaces.Limpieza_Interface;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.commons.io.FilenameUtils;
import paneles.profesores.Tablero_Profesor_Panel;

/**
 *
 * @author LENOVO
 */
public class Chat_Profesor_Panel extends javax.swing.JPanel  implements Componentes_Interface,  Envio_Interface,Limpieza_Interface, Carta_Visibilidad_Interface{

    private final String ID;
    private boolean carta_Visible;
    
    /**
     * Creates new form Chat_Profesor
     */
    public Chat_Profesor_Panel(String receptor_Nombre,
            String _id) {
        initComponents();
        
        this.ID = _id;
        
        nombre_JLabel.setText(receptor_Nombre);
        
        Iniciar_Componentes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_JPanel = new javax.swing.JPanel();
        nombre_JLabel = new javax.swing.JLabel();
        informacion_JButton = new javax.swing.JButton();
        chat_JButton = new javax.swing.JButton();
        regresar_JButton = new javax.swing.JButton();
        actualizar_JButton = new javax.swing.JButton();
        chat_JLayeredPane = new javax.swing.JLayeredPane();
        chat_JPanel = new javax.swing.JPanel();
        mensajes_JScrollPane = new javax.swing.JScrollPane();
        mensajes_JPanel = new javax.swing.JPanel();
        enviar_Mensajes_JPanel = new javax.swing.JPanel();
        enviar_Archivos_JButton = new javax.swing.JButton();
        redactar_Mensaje_JTextField = new javax.swing.JTextField();
        informacion_Chat_JPanel = new javax.swing.JPanel();
        imagen_Perfil_JLabel = new javax.swing.JLabel();
        apellidos_JLabel = new javax.swing.JLabel();
        nombres_JLabel = new javax.swing.JLabel();
        correo_JLabel = new javax.swing.JLabel();
        tipo_Perfil_JLabel = new javax.swing.JLabel();
        genero_JLabel = new javax.swing.JLabel();
        intereses_Tematicas_JScrollPane = new javax.swing.JScrollPane();
        intereses_Tematicas_JTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1110, 630));
        setOpaque(false);

        titulo_JPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titulo_JPanel.setMaximumSize(new java.awt.Dimension(32767, 72));
        titulo_JPanel.setPreferredSize(new java.awt.Dimension(982, 72));

        nombre_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_JLabel.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        nombre_JLabel.setMaximumSize(new java.awt.Dimension(818, 68));
        nombre_JLabel.setMinimumSize(new java.awt.Dimension(818, 68));
        nombre_JLabel.setPreferredSize(new java.awt.Dimension(818, 68));

        informacion_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/verified-user.png"))); // NOI18N
        informacion_JButton.setBorder(null);
        informacion_JButton.setPreferredSize(new java.awt.Dimension(36, 36));
        ((ImageIcon)informacion_JButton.getIcon()).getImage().flush();
        informacion_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informacion_JButtonMouseClicked(evt);
            }
        });

        chat_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/influencer.png"))); // NOI18N
        chat_JButton.setBorder(null);
        chat_JButton.setPreferredSize(new java.awt.Dimension(36, 36));
        ((ImageIcon)chat_JButton.getIcon()).getImage().flush();
        chat_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chat_JButtonMouseClicked(evt);
            }
        });

        regresar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/reply.png"))); // NOI18N
        regresar_JButton.setBorder(null);
        regresar_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar_JButton.setToolTipText("Regresar A Mis Chats");
        ((ImageIcon)regresar_JButton.getIcon()).getImage().flush();
        regresar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseExited(evt);
            }
        });

        actualizar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/updated.png"))); // NOI18N
        actualizar_JButton.setBorder(null);
        actualizar_JButton.setPreferredSize(new java.awt.Dimension(36, 36));
        ((ImageIcon)actualizar_JButton.getIcon()).getImage().flush();
        actualizar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizar_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actualizar_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actualizar_JButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout titulo_JPanelLayout = new javax.swing.GroupLayout(titulo_JPanel);
        titulo_JPanel.setLayout(titulo_JPanelLayout);
        titulo_JPanelLayout.setHorizontalGroup(
            titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titulo_JPanelLayout.createSequentialGroup()
                .addComponent(regresar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chat_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(informacion_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(actualizar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titulo_JPanelLayout.setVerticalGroup(
            titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titulo_JPanelLayout.createSequentialGroup()
                .addGroup(titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresar_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(titulo_JPanelLayout.createSequentialGroup()
                        .addGroup(titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(informacion_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chat_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualizar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        chat_JLayeredPane.setLayout(new java.awt.CardLayout());

        chat_JPanel.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        chat_JPanel.setOpaque(false);
        chat_JPanel.setPreferredSize(new java.awt.Dimension(1110, 630));

        mensajes_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        mensajes_JScrollPane.setOpaque(false);

        mensajes_JPanel.setOpaque(false);
        mensajes_JPanel.setLayout(new javax.swing.BoxLayout(mensajes_JPanel, javax.swing.BoxLayout.PAGE_AXIS));
        mensajes_JScrollPane.setViewportView(mensajes_JPanel);

        enviar_Mensajes_JPanel.setMaximumSize(new java.awt.Dimension(32767, 44));
        enviar_Mensajes_JPanel.setPreferredSize(new java.awt.Dimension(1085, 44));

        enviar_Archivos_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/attachment.png"))); // NOI18N
        enviar_Archivos_JButton.setBorder(null);
        enviar_Archivos_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar_Archivos_JButton.setMaximumSize(new java.awt.Dimension(36, 36));
        enviar_Archivos_JButton.setMinimumSize(new java.awt.Dimension(36, 36));
        enviar_Archivos_JButton.setPreferredSize(new java.awt.Dimension(36, 36));
        enviar_Archivos_JButton.setToolTipText("Enviar Archivo");
        ((ImageIcon)enviar_Archivos_JButton.getIcon()).getImage().flush();
        enviar_Archivos_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar_Archivos_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enviar_Archivos_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enviar_Archivos_JButtonMouseExited(evt);
            }
        });

        redactar_Mensaje_JTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        redactar_Mensaje_JTextField.setPreferredSize(new java.awt.Dimension(71, 34));
        redactar_Mensaje_JTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                redactar_Mensaje_JTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout enviar_Mensajes_JPanelLayout = new javax.swing.GroupLayout(enviar_Mensajes_JPanel);
        enviar_Mensajes_JPanel.setLayout(enviar_Mensajes_JPanelLayout);
        enviar_Mensajes_JPanelLayout.setHorizontalGroup(
            enviar_Mensajes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enviar_Mensajes_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enviar_Archivos_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(redactar_Mensaje_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        enviar_Mensajes_JPanelLayout.setVerticalGroup(
            enviar_Mensajes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enviar_Mensajes_JPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(enviar_Mensajes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redactar_Mensaje_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviar_Archivos_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chat_JPanelLayout = new javax.swing.GroupLayout(chat_JPanel);
        chat_JPanel.setLayout(chat_JPanelLayout);
        chat_JPanelLayout.setHorizontalGroup(
            chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_JPanelLayout.createSequentialGroup()
                .addGroup(chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mensajes_JScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
                    .addComponent(enviar_Mensajes_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        chat_JPanelLayout.setVerticalGroup(
            chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_JPanelLayout.createSequentialGroup()
                .addComponent(mensajes_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(enviar_Mensajes_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        chat_JLayeredPane.add(chat_JPanel, "Chat");

        informacion_Chat_JPanel.setOpaque(false);
        informacion_Chat_JPanel.setPreferredSize(new java.awt.Dimension(1110, 630));

        imagen_Perfil_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen_Perfil_JLabel.setToolTipText("Imagen De Perfil");
        imagen_Perfil_JLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagen_Perfil_JLabel.setMaximumSize(new java.awt.Dimension(2000, 2000));
        imagen_Perfil_JLabel.setMinimumSize(new java.awt.Dimension(450, 450));
        imagen_Perfil_JLabel.setPreferredSize(new java.awt.Dimension(450, 450));

        apellidos_JLabel.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        apellidos_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apellidos_JLabel.setToolTipText("Apellido(s)");
        apellidos_JLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        apellidos_JLabel.setMaximumSize(new java.awt.Dimension(560, 50));
        apellidos_JLabel.setMinimumSize(new java.awt.Dimension(560, 50));
        apellidos_JLabel.setName("label"); // NOI18N
        apellidos_JLabel.setOpaque(true);
        apellidos_JLabel.setPreferredSize(new java.awt.Dimension(560, 50));

        nombres_JLabel.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        nombres_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombres_JLabel.setToolTipText("Nombre(s)");
        nombres_JLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nombres_JLabel.setMaximumSize(new java.awt.Dimension(560, 50));
        nombres_JLabel.setMinimumSize(new java.awt.Dimension(560, 50));
        nombres_JLabel.setName("label"); // NOI18N
        nombres_JLabel.setOpaque(true);
        nombres_JLabel.setPreferredSize(new java.awt.Dimension(560, 50));

        correo_JLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        correo_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        correo_JLabel.setToolTipText("Correo Electrónico");
        correo_JLabel.setMaximumSize(new java.awt.Dimension(560, 25));
        correo_JLabel.setMinimumSize(new java.awt.Dimension(560, 25));
        correo_JLabel.setName("label"); // NOI18N
        correo_JLabel.setPreferredSize(new java.awt.Dimension(560, 25));

        tipo_Perfil_JLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        tipo_Perfil_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tipo_Perfil_JLabel.setToolTipText("Tipo De Perfil");
        tipo_Perfil_JLabel.setMaximumSize(new java.awt.Dimension(345, 25));
        tipo_Perfil_JLabel.setMinimumSize(new java.awt.Dimension(345, 25));
        tipo_Perfil_JLabel.setName("label"); // NOI18N
        tipo_Perfil_JLabel.setPreferredSize(new java.awt.Dimension(345, 25));

        genero_JLabel.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        genero_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genero_JLabel.setToolTipText("Género");
        genero_JLabel.setMaximumSize(new java.awt.Dimension(212, 25));
        genero_JLabel.setMinimumSize(new java.awt.Dimension(212, 25));
        genero_JLabel.setName("label"); // NOI18N
        genero_JLabel.setPreferredSize(new java.awt.Dimension(212, 25));

        intereses_Tematicas_JScrollPane.setBorder(null);
        intereses_Tematicas_JScrollPane.setOpaque(false);

        intereses_Tematicas_JTable.setAutoCreateRowSorter(true);
        intereses_Tematicas_JTable.setModel(

            new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Interes / Temática"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }

                @Override
                public Class getColumnClass(int column)
                {
                    for(int i = 0; i < intereses_Tematicas_JTable.getRowCount(); i++)
                    {
                        //The first valid value of a cell of given column is retrieved.
                        if(getValueAt(i,column) != null)
                        {
                            return getValueAt(i, column).getClass();
                        }
                    }
                    //if no valid value is found, default renderer is returned.
                    return super.getColumnClass(column);
                }
            });
            intereses_Tematicas_JTable.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
            intereses_Tematicas_JTable.setOpaque(false);
            intereses_Tematicas_JTable.setRowHeight(45);
            intereses_Tematicas_JTable.setRowMargin(10);
            intereses_Tematicas_JTable.setShowGrid(true);
            intereses_Tematicas_JTable.setShowVerticalLines(false);
            intereses_Tematicas_JTable.setRowSorter(new TableRowSorter(intereses_Tematicas_JTable.getModel()));
            intereses_Tematicas_JScrollPane.setViewportView(intereses_Tematicas_JTable);

            javax.swing.GroupLayout informacion_Chat_JPanelLayout = new javax.swing.GroupLayout(informacion_Chat_JPanel);
            informacion_Chat_JPanel.setLayout(informacion_Chat_JPanelLayout);
            informacion_Chat_JPanelLayout.setHorizontalGroup(
                informacion_Chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(informacion_Chat_JPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagen_Perfil_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(informacion_Chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(correo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(apellidos_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(nombres_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(informacion_Chat_JPanelLayout.createSequentialGroup()
                            .addComponent(genero_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tipo_Perfil_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addComponent(intereses_Tematicas_JScrollPane))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            informacion_Chat_JPanelLayout.setVerticalGroup(
                informacion_Chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacion_Chat_JPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(informacion_Chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(imagen_Perfil_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(informacion_Chat_JPanelLayout.createSequentialGroup()
                            .addComponent(nombres_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(apellidos_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(correo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addGroup(informacion_Chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(genero_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tipo_Perfil_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(intereses_Tematicas_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            chat_JLayeredPane.add(informacion_Chat_JPanel, "Informacion");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chat_JLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(titulo_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE))
                    .addGap(32, 32, 32))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(titulo_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chat_JLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addContainerGap())
            );
        }// </editor-fold>//GEN-END:initComponents

    private void regresar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Profesor_Panel.Mostrar_Vista("Chats");
        }
    }//GEN-LAST:event_regresar_JButtonMouseClicked

    private void regresar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseEntered
        // TODO add your handling code here:
        regresar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
    }//GEN-LAST:event_regresar_JButtonMouseEntered

    private void regresar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseExited
        // TODO add your handling code here:
        regresar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
    }//GEN-LAST:event_regresar_JButtonMouseExited

    private void enviar_Archivos_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_Archivos_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Enviar_Archivos();
        }
    }//GEN-LAST:event_enviar_Archivos_JButtonMouseClicked

    private void enviar_Archivos_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_Archivos_JButtonMouseEntered
        // TODO add your handling code here:
        enviar_Archivos_JButton.setBackground(CourseRoom.Utilerias.Primer_Color());
    }//GEN-LAST:event_enviar_Archivos_JButtonMouseEntered

    private void enviar_Archivos_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_Archivos_JButtonMouseExited
        // TODO add your handling code here:
        enviar_Archivos_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
    }//GEN-LAST:event_enviar_Archivos_JButtonMouseExited

    private void informacion_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacion_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            ((CardLayout)chat_JLayeredPane.getLayout()).show(chat_JLayeredPane,"Informacion");
            carta_Visible = true;
            Carta_Visible();
        }
    }//GEN-LAST:event_informacion_JButtonMouseClicked

    private void chat_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chat_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            ((CardLayout)chat_JLayeredPane.getLayout()).show(chat_JLayeredPane,"Chat");
            carta_Visible = false;
            Carta_Visible();
        }
    }//GEN-LAST:event_chat_JButtonMouseClicked

    private void actualizar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){

        }
    }//GEN-LAST:event_actualizar_JButtonMouseClicked

    private void actualizar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_JButtonMouseEntered
        // TODO add your handling code here:
        actualizar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
    }//GEN-LAST:event_actualizar_JButtonMouseEntered

    private void actualizar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_JButtonMouseExited
        // TODO add your handling code here:
        actualizar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
    }//GEN-LAST:event_actualizar_JButtonMouseExited

    private void redactar_Mensaje_JTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_redactar_Mensaje_JTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Enviar_Mensaje();
        }
    }//GEN-LAST:event_redactar_Mensaje_JTextFieldKeyPressed

    public String ID() {
        return this.ID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar_JButton;
    private javax.swing.JLabel apellidos_JLabel;
    private javax.swing.JButton chat_JButton;
    private javax.swing.JLayeredPane chat_JLayeredPane;
    private javax.swing.JPanel chat_JPanel;
    private javax.swing.JLabel correo_JLabel;
    private javax.swing.JButton enviar_Archivos_JButton;
    private javax.swing.JPanel enviar_Mensajes_JPanel;
    private javax.swing.JLabel genero_JLabel;
    private static javax.swing.JLabel imagen_Perfil_JLabel;
    private javax.swing.JPanel informacion_Chat_JPanel;
    private javax.swing.JButton informacion_JButton;
    private javax.swing.JScrollPane intereses_Tematicas_JScrollPane;
    private javax.swing.JTable intereses_Tematicas_JTable;
    private javax.swing.JPanel mensajes_JPanel;
    private javax.swing.JScrollPane mensajes_JScrollPane;
    private javax.swing.JLabel nombre_JLabel;
    private javax.swing.JLabel nombres_JLabel;
    private javax.swing.JTextField redactar_Mensaje_JTextField;
    private javax.swing.JButton regresar_JButton;
    private javax.swing.JLabel tipo_Perfil_JLabel;
    private javax.swing.JPanel titulo_JPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Iniciar_Componentes() {
        carta_Visible = false;
        mensajes_JScrollPane.getViewport().setOpaque(false);
        mensajes_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        nombres_JLabel.setText(nombre_JLabel.getText());
        apellidos_JLabel.setText(CourseRoom.Utilerias.Concatenar(CourseRoom.Utilerias.name().lastName(), " ", CourseRoom.Utilerias.name().lastName()));
        correo_JLabel.setText(CourseRoom.Utilerias.internet().emailAddress());
        genero_JLabel.setText(CourseRoom.Utilerias.demographic().sex());
        tipo_Perfil_JLabel.setText(CourseRoom.Utilerias.bool().bool() ? "Estudiante" : "Profesor");

        
        ImageIcon imagen = new ImageIcon(Tablero_Profesor_Panel.Obtener_Imagen_Usuario());
        imagen_Perfil_JLabel.setIcon(imagen);
        imagen.getImage().flush();

        intereses_Tematicas_JScrollPane.getViewport().setOpaque(false);
        intereses_Tematicas_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        intereses_Tematicas_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);

        Font gadugi = new Font("Gadugi", Font.BOLD, 16);
        intereses_Tematicas_JTable.getTableHeader().setFont(gadugi);
        intereses_Tematicas_JTable.setDefaultRenderer(Celda_Renderer.class, new Celda_Renderer());

        DefaultTableModel modelo = (DefaultTableModel) intereses_Tematicas_JTable.getModel();
        Celda_Renderer[] celda = new Celda_Renderer[1];
        for (int i = 0; i < CourseRoom.Utilerias.number().numberBetween(1, 10); i++) {
            celda[0] = new Celda_Renderer(CourseRoom.Utilerias.music().genre(), "");
            modelo.addRow(celda);
        }

        Colorear_Componentes();
    }

    @Override
    public void Colorear_Componentes() {
        
        titulo_JPanel.setBackground(CourseRoom.Utilerias.Segundo_Color());
        nombre_JLabel.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        
        Carta_Visible();
        
        regresar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
        
        nombre_JLabel.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        redactar_Mensaje_JTextField.setBackground(CourseRoom.Utilerias.Primer_Color());
        redactar_Mensaje_JTextField.setForeground(CourseRoom.Utilerias.Primer_Color_Fuente());
        enviar_Mensajes_JPanel.setBackground(CourseRoom.Utilerias.Segundo_Color());

        enviar_Archivos_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
        actualizar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());

        nombres_JLabel.setBackground(CourseRoom.Utilerias.Tercer_Color());
        nombres_JLabel.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        imagen_Perfil_JLabel.setForeground(CourseRoom.Utilerias.Primer_Color_Fuente());
        apellidos_JLabel.setBackground(CourseRoom.Utilerias.Tercer_Color());
        apellidos_JLabel.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        correo_JLabel.setForeground(CourseRoom.Utilerias.Primer_Color_Fuente());
        genero_JLabel.setForeground(CourseRoom.Utilerias.Primer_Color_Fuente());
        tipo_Perfil_JLabel.setForeground(CourseRoom.Utilerias.Primer_Color_Fuente());

        intereses_Tematicas_JTable.getTableHeader().setBackground(CourseRoom.Utilerias.Segundo_Color());
        intereses_Tematicas_JTable.getTableHeader().setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());

        DefaultTableModel modelo = (DefaultTableModel) intereses_Tematicas_JTable.getModel();
        Celda_Renderer celda;
        for (int i = 0; i < intereses_Tematicas_JTable.getRowCount(); i++) {
            celda = (Celda_Renderer) modelo.getValueAt(i, 0);
            celda.Color_Fuente(CourseRoom.Utilerias.Primer_Color_Fuente());
        }

        Component[] chat_Componentes = mensajes_JPanel.getComponents();
        for (Component chat_Componente : chat_Componentes) {
            ((Componentes_Interface) chat_Componente).Colorear_Componentes();
        }
    }
    
    
    @Override
    public void Enviar_Mensaje() {

        String mensaje = redactar_Mensaje_JTextField.getText();
        if (!mensaje.isEmpty() && !mensaje.isBlank()) {
            String emisor = CourseRoom.Utilerias.dune().character();
            String fecha = CourseRoom.Utilerias.Fecha_Hora_Local();
            if (CourseRoom.Utilerias.number().numberBetween(1,10) < 5) {
                Mensaje_Texto_Izquierdo_General_Panel mensaje_Texto_General_Panel
                        = new Mensaje_Texto_Izquierdo_General_Panel(emisor, fecha, mensaje);
                mensajes_JPanel.add(mensaje_Texto_General_Panel);
            } else {
                Mensaje_Texto_Derecho_General_Panel mensaje_Texto_General_Panel
                        = new Mensaje_Texto_Derecho_General_Panel(emisor, fecha, mensaje);
                mensajes_JPanel.add(mensaje_Texto_General_Panel);
            }
            redactar_Mensaje_JTextField.setText("");
            redactar_Mensaje_JTextField.setCaretPosition(0);
        }
    }

    @Override
    public void Enviar_Archivos() {
        JFileChooser escogedor_Archivos = new JFileChooser();
        escogedor_Archivos.setFileSelectionMode(JFileChooser.FILES_ONLY);
        escogedor_Archivos.setApproveButtonText("Enviar Archivo(s)");
        escogedor_Archivos.setMultiSelectionEnabled(true);
        int resultado = escogedor_Archivos.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File[] archivos_Abiertos = escogedor_Archivos.getSelectedFiles();

            if (archivos_Abiertos != null) {

                String emisor;
                String fecha;
                String ruta;
                String extension;
                String nombre_Archivo;

                if (CourseRoom.Utilerias.number().numberBetween(1,10) < 5) {
                    Mensaje_Archivo_Izquierdo_General_Panel mensaje_Archivo_Panel;
                    for (File archivo_Abierto : archivos_Abiertos) {
                        ruta = archivo_Abierto.getAbsolutePath();
                        nombre_Archivo = archivo_Abierto.getName();
                        extension = FilenameUtils.getExtension(nombre_Archivo);
                        emisor = CourseRoom.Utilerias.dune().character();
                        fecha = CourseRoom.Utilerias.Fecha_Hora_Local();
                        mensaje_Archivo_Panel
                                = new Mensaje_Archivo_Izquierdo_General_Panel(emisor, fecha, ruta, extension, nombre_Archivo);
                        mensajes_JPanel.add(mensaje_Archivo_Panel);
                    }
                } else {
                    Mensaje_Archivo_Derecho_General_Panel mensaje_Archivo_Panel;
                    for (File archivo_Abierto : archivos_Abiertos) {
                        ruta = archivo_Abierto.getAbsolutePath();
                        nombre_Archivo = archivo_Abierto.getName();
                        extension = FilenameUtils.getExtension(nombre_Archivo);
                        emisor = CourseRoom.Utilerias.dune().character();
                        fecha = CourseRoom.Utilerias.Fecha_Hora_Local();
                        mensaje_Archivo_Panel
                                = new Mensaje_Archivo_Derecho_General_Panel(emisor, fecha, ruta, extension, nombre_Archivo);
                        mensajes_JPanel.add(mensaje_Archivo_Panel);
                    }
                }

            }

        }

    }

  
    @Override
    public void Limpiar() {
        mensajes_JPanel.removeAll();
        intereses_Tematicas_JTable.removeAll();
    }

    @Override
    public void Carta_Visible() {
        if(!carta_Visible){
            chat_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
            informacion_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
        }else{
            chat_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
            informacion_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());

        }
    }
    
    

}
