/*
 * Copyright (C) 2022 LENOVO
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package paneles.profesores.tareas;

import clases.Celda_Renderer;
import courseroom.CourseRoom;
import datos.interfaces.Carta_Visibilidad_Interface;
import datos.interfaces.Componentes_Interface;
import datos.interfaces.Envio_Interface;
import datos.interfaces.Limpieza_Interface;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.commons.io.FilenameUtils;
import paneles.profesores.Tablero_Profesor_Panel;

/**
 *
 * @author LENOVO
 */
public class Tarea_Por_Calificar_Profesor_Panel extends javax.swing.JPanel implements  Componentes_Interface, Envio_Interface, Limpieza_Interface, Carta_Visibilidad_Interface{

    private byte carta_Visible;
    
    
    public Tarea_Por_Calificar_Profesor_Panel(
            String nombre_Tarea, 
            String nombre_Curso,
            String fecha_Creacion,
            String fecha_Entrega,
            String fecha_Entregada,
            String estatus){
        initComponents();
        
        titulo_JLabel.setText(nombre_Tarea);
        curso_JLabel.setText(CourseRoom.Utilerias.Concatenar("Del Curso ", nombre_Curso));
        fecha_Entrega_JLabel.setText(CourseRoom.Utilerias.Concatenar("Se entrega el ", fecha_Entrega));
        fecha_Creacion_JLabel.setText(CourseRoom.Utilerias.Concatenar("Creada el ", fecha_Creacion));
        fecha_Entregado_JLabel.setText(CourseRoom.Utilerias.Concatenar("Entregada el ", fecha_Entregada));
        estatus_Tarea_JLabel.setText(estatus);
        
        Iniciar_Componentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_JPanel = new javax.swing.JPanel();
        titulo_JLabel = new javax.swing.JLabel();
        informacion_JButton = new javax.swing.JButton();
        chat_JButton = new javax.swing.JButton();
        entregar_Tarea_JButton = new javax.swing.JButton();
        regresar_JButton = new javax.swing.JButton();
        actualizar_JButton = new javax.swing.JButton();
        retroalimentacion_JButton = new javax.swing.JButton();
        tarea_JLayeredPane = new javax.swing.JLayeredPane();
        informacion_Tarea_JPanel = new javax.swing.JPanel();
        curso_JLabel = new javax.swing.JLabel();
        descripcion_JScrollPane = new javax.swing.JScrollPane();
        descripcion_JTextPane = new javax.swing.JTextPane();
        fecha_Entrega_JLabel = new javax.swing.JLabel();
        estatus_Tarea_JLabel = new javax.swing.JLabel();
        fecha_Creacion_JLabel = new javax.swing.JLabel();
        chat_JPanel = new javax.swing.JPanel();
        mensajes_Chat_JScrollPane = new javax.swing.JScrollPane();
        mensajes_Chat_JTable = new javax.swing.JTable();
        enviar_Mensaje_Chat_JPanel = new javax.swing.JPanel();
        enviar_Archivo_Chat_JButton = new javax.swing.JButton();
        redactar_Mensaje_Chat_JTextField = new javax.swing.JTextField();
        archivos_Entregados_JPanel = new javax.swing.JPanel();
        archivos_Entregados_JScrollPane = new javax.swing.JScrollPane();
        archivos_Entregados_JTable = new javax.swing.JTable();
        calificar_JButton = new javax.swing.JButton();
        fecha_Entregado_JLabel = new javax.swing.JLabel();
        es_Tarea_Grupal_JLabel = new javax.swing.JLabel();
        retroalimentacion_JPanel = new javax.swing.JPanel();
        retroalimentacion_JScrollPane = new javax.swing.JScrollPane();
        retroalimentacion_JTable = new javax.swing.JTable();
        retroalimentar_JButton = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1110, 630));

        titulo_JPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titulo_JPanel.setMaximumSize(new java.awt.Dimension(32767, 72));
        titulo_JPanel.setPreferredSize(new java.awt.Dimension(982, 72));

        titulo_JLabel.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        titulo_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_JLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        titulo_JLabel.setMaximumSize(new java.awt.Dimension(818, 68));
        titulo_JLabel.setMinimumSize(new java.awt.Dimension(818, 68));
        titulo_JLabel.setOpaque(true);
        titulo_JLabel.setPreferredSize(new java.awt.Dimension(818, 68));

        informacion_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/info_1.png"))); // NOI18N
        informacion_JButton.setBorder(null);
        informacion_JButton.setPreferredSize(new java.awt.Dimension(36, 36));
        ((ImageIcon)informacion_JButton.getIcon()).getImage().flush();
        informacion_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informacion_JButtonMouseClicked(evt);
            }
        });

        chat_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/online-chat_1.png"))); // NOI18N
        chat_JButton.setBorder(null);
        chat_JButton.setPreferredSize(new java.awt.Dimension(36, 36));
        ((ImageIcon)chat_JButton.getIcon()).getImage().flush();
        chat_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chat_JButtonMouseClicked(evt);
            }
        });

        entregar_Tarea_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/woman.png"))); // NOI18N
        entregar_Tarea_JButton.setBorder(null);
        entregar_Tarea_JButton.setPreferredSize(new java.awt.Dimension(36, 36));
        ((ImageIcon)entregar_Tarea_JButton.getIcon()).getImage().flush();
        entregar_Tarea_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entregar_Tarea_JButtonMouseClicked(evt);
            }
        });

        regresar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/reply.png"))); // NOI18N
        regresar_JButton.setToolTipText("Regresar A Mis Chats");
        regresar_JButton.setBorder(null);
        regresar_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ((ImageIcon)regresar_JButton.getIcon()).getImage().flush();
        regresar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseExited(evt);
            }
        });

        actualizar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/updated.png"))); // NOI18N
        actualizar_JButton.setBorder(null);
        actualizar_JButton.setPreferredSize(new java.awt.Dimension(36, 36));
        ((ImageIcon)actualizar_JButton.getIcon()).getImage().flush();
        actualizar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizar_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actualizar_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actualizar_JButtonMouseExited(evt);
            }
        });

        retroalimentacion_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/feedback.png"))); // NOI18N
        retroalimentacion_JButton.setBorder(null);
        retroalimentacion_JButton.setPreferredSize(new java.awt.Dimension(36, 36));
        ((ImageIcon)retroalimentacion_JButton.getIcon()).getImage().flush();
        retroalimentacion_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retroalimentacion_JButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titulo_JPanelLayout = new javax.swing.GroupLayout(titulo_JPanel);
        titulo_JPanel.setLayout(titulo_JPanelLayout);
        titulo_JPanelLayout.setHorizontalGroup(
            titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titulo_JPanelLayout.createSequentialGroup()
                .addComponent(regresar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titulo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(informacion_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chat_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(entregar_Tarea_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(retroalimentacion_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(actualizar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titulo_JPanelLayout.setVerticalGroup(
            titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titulo_JPanelLayout.createSequentialGroup()
                .addGroup(titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresar_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(titulo_JPanelLayout.createSequentialGroup()
                        .addGroup(titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chat_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(informacion_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entregar_Tarea_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualizar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retroalimentacion_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)))
                .addContainerGap())
        );

        tarea_JLayeredPane.setPreferredSize(new java.awt.Dimension(982, 534));
        tarea_JLayeredPane.setLayout(new java.awt.CardLayout());

        informacion_Tarea_JPanel.setToolTipText("");
        informacion_Tarea_JPanel.setOpaque(false);
        informacion_Tarea_JPanel.setPreferredSize(new java.awt.Dimension(1110, 630));

        curso_JLabel.setFont(new java.awt.Font("Gadugi", 1, 15)); // NOI18N
        curso_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curso_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/training.png"))); // NOI18N
        curso_JLabel.setToolTipText("<html>\n<h3>Curso de provenencia</h3>\n</html>");
        curso_JLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        curso_JLabel.setOpaque(true);
        curso_JLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                curso_JLabelMouseClicked(evt);
            }
        });

        descripcion_JScrollPane.setBorder(null);
        descripcion_JScrollPane.setFocusable(false);
        descripcion_JScrollPane.setOpaque(false);
        descripcion_JScrollPane.setRequestFocusEnabled(false);
        descripcion_JScrollPane.setVerifyInputWhenFocusTarget(false);
        descripcion_JScrollPane.setWheelScrollingEnabled(false);

        descripcion_JTextPane.setEditable(false);
        descripcion_JTextPane.setBorder(null);
        descripcion_JTextPane.setContentType("text/html"); // NOI18N
        descripcion_JTextPane.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        descripcion_JTextPane.setText("");
        descripcion_JTextPane.setToolTipText("<html>\n<h3>Descripción</h3>\n</html>");
        descripcion_JTextPane.setFocusCycleRoot(false);
        descripcion_JTextPane.setOpaque(false);
        descripcion_JTextPane.setRequestFocusEnabled(false);
        descripcion_JScrollPane.setViewportView(descripcion_JTextPane);

        fecha_Entrega_JLabel.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        fecha_Entrega_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_Entrega_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/clock.png"))); // NOI18N
        fecha_Entrega_JLabel.setOpaque(true);

        estatus_Tarea_JLabel.setFont(new java.awt.Font("Gadugi", 1, 15)); // NOI18N
        estatus_Tarea_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estatus_Tarea_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/homework_1.png"))); // NOI18N
        estatus_Tarea_JLabel.setOpaque(true);

        fecha_Creacion_JLabel.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        fecha_Creacion_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_Creacion_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/homework_1.png"))); // NOI18N
        fecha_Creacion_JLabel.setOpaque(true);

        javax.swing.GroupLayout informacion_Tarea_JPanelLayout = new javax.swing.GroupLayout(informacion_Tarea_JPanel);
        informacion_Tarea_JPanel.setLayout(informacion_Tarea_JPanelLayout);
        informacion_Tarea_JPanelLayout.setHorizontalGroup(
            informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion_Tarea_JPanelLayout.createSequentialGroup()
                .addGroup(informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informacion_Tarea_JPanelLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcion_JScrollPane)
                            .addGroup(informacion_Tarea_JPanelLayout.createSequentialGroup()
                                .addComponent(curso_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(estatus_Tarea_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(informacion_Tarea_JPanelLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(fecha_Entrega_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(fecha_Creacion_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        informacion_Tarea_JPanelLayout.setVerticalGroup(
            informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion_Tarea_JPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(curso_JLabel)
                    .addComponent(estatus_Tarea_JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha_Entrega_JLabel)
                    .addComponent(fecha_Creacion_JLabel))
                .addGap(0, 0, 0))
        );

        tarea_JLayeredPane.add(informacion_Tarea_JPanel, "Informacion");

        chat_JPanel.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        chat_JPanel.setOpaque(false);
        chat_JPanel.setPreferredSize(new java.awt.Dimension(1110, 630));
        chat_JPanel.setLayout(new java.awt.BorderLayout());

        mensajes_Chat_JScrollPane.setBorder(null);
        mensajes_Chat_JScrollPane.setOpaque(false);

        mensajes_Chat_JTable.setAutoCreateRowSorter(true);
        mensajes_Chat_JTable.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        mensajes_Chat_JTable.setModel(

            new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Emisor", "Mensaje", "Fecha"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, true, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }

                @Override
                public Class getColumnClass(int column)
                {
                    for(int i = 0; i < mensajes_Chat_JTable.getRowCount(); i++)
                    {
                        //The first valid value of a cell of given column is retrieved.
                        if(getValueAt(i,column) != null)
                        {
                            return getValueAt(i, column).getClass();
                        }
                    }
                    //if no valid value is found, default renderer is returned.
                    return super.getColumnClass(column);
                }
            });
            mensajes_Chat_JTable.setOpaque(false);
            mensajes_Chat_JTable.setRowHeight(80);
            mensajes_Chat_JTable.setRowMargin(15);
            mensajes_Chat_JTable.setShowGrid(true);
            mensajes_Chat_JTable.setRowSorter(new TableRowSorter(mensajes_Chat_JTable.getModel()));
            mensajes_Chat_JTable.addMouseListener(new MouseAdapter() {

                @Override
                public void mousePressed(MouseEvent e) {
                    if (e.getClickCount() == 2) {

                        JTable tabla = (JTable) e.getComponent();
                        int columna = tabla.getSelectedColumn();

                        // Abrir
                        if (columna == 1) {
                            int fila = tabla.getRowSorter().convertRowIndexToModel(tabla.getSelectedRow());
                            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
                            Celda_Renderer celda = (Celda_Renderer)modelo.getValueAt(fila, columna);

                            if(celda.Tiene_Icono()){
                                String extension = FilenameUtils.getExtension(celda.Texto());
                                String ruta = celda.ID();
                                CourseRoom.Utilerias.Abrir_Archivo(ruta, extension, celda.Texto());
                            }
                        }
                    }
                }
            });
            mensajes_Chat_JScrollPane.setViewportView(mensajes_Chat_JTable);

            chat_JPanel.add(mensajes_Chat_JScrollPane, java.awt.BorderLayout.CENTER);

            enviar_Mensaje_Chat_JPanel.setMaximumSize(new java.awt.Dimension(32767, 44));
            enviar_Mensaje_Chat_JPanel.setPreferredSize(new java.awt.Dimension(1085, 44));

            enviar_Archivo_Chat_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/attachment.png"))); // NOI18N
            enviar_Archivo_Chat_JButton.setToolTipText("Enviar Archivo");
            enviar_Archivo_Chat_JButton.setBorder(null);
            enviar_Archivo_Chat_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            enviar_Archivo_Chat_JButton.setMaximumSize(new java.awt.Dimension(36, 36));
            enviar_Archivo_Chat_JButton.setMinimumSize(new java.awt.Dimension(36, 36));
            enviar_Archivo_Chat_JButton.setPreferredSize(new java.awt.Dimension(36, 36));
            ((ImageIcon)enviar_Archivo_Chat_JButton.getIcon()).getImage().flush();
            enviar_Archivo_Chat_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    enviar_Archivo_Chat_JButtonMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    enviar_Archivo_Chat_JButtonMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    enviar_Archivo_Chat_JButtonMouseExited(evt);
                }
            });

            redactar_Mensaje_Chat_JTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            redactar_Mensaje_Chat_JTextField.setPreferredSize(new java.awt.Dimension(71, 34));
            redactar_Mensaje_Chat_JTextField.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    redactar_Mensaje_Chat_JTextFieldKeyPressed(evt);
                }
            });

            javax.swing.GroupLayout enviar_Mensaje_Chat_JPanelLayout = new javax.swing.GroupLayout(enviar_Mensaje_Chat_JPanel);
            enviar_Mensaje_Chat_JPanel.setLayout(enviar_Mensaje_Chat_JPanelLayout);
            enviar_Mensaje_Chat_JPanelLayout.setHorizontalGroup(
                enviar_Mensaje_Chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enviar_Mensaje_Chat_JPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(enviar_Archivo_Chat_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(redactar_Mensaje_Chat_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                    .addContainerGap())
            );
            enviar_Mensaje_Chat_JPanelLayout.setVerticalGroup(
                enviar_Mensaje_Chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enviar_Mensaje_Chat_JPanelLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(enviar_Mensaje_Chat_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(enviar_Archivo_Chat_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(redactar_Mensaje_Chat_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(4, 4, 4))
            );

            chat_JPanel.add(enviar_Mensaje_Chat_JPanel, java.awt.BorderLayout.SOUTH);

            tarea_JLayeredPane.add(chat_JPanel, "Chat");

            archivos_Entregados_JPanel.setToolTipText("");
            archivos_Entregados_JPanel.setOpaque(false);
            archivos_Entregados_JPanel.setPreferredSize(new java.awt.Dimension(1110, 630));

            archivos_Entregados_JScrollPane.setBorder(null);
            archivos_Entregados_JScrollPane.setOpaque(false);

            archivos_Entregados_JTable.setAutoCreateRowSorter(true);
            archivos_Entregados_JTable.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
            archivos_Entregados_JTable.setModel(

                new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Archivo", "Subido", "Descargar"
                    }
                ) {
                    boolean[] canEdit = new boolean [] {
                        false, false,false
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }

                    @Override
                    public Class getColumnClass(int column)
                    {
                        for(int i = 0; i < archivos_Entregados_JTable.getRowCount(); i++)
                        {
                            //The first valid value of a cell of given column is retrieved.
                            if(getValueAt(i,column) != null)
                            {
                                return getValueAt(i, column).getClass();
                            }
                        }
                        //if no valid value is found, default renderer is returned.
                        return super.getColumnClass(column);
                    }
                });
                archivos_Entregados_JTable.setOpaque(false);
                archivos_Entregados_JTable.setRowHeight(75);
                archivos_Entregados_JTable.setRowMargin(15);
                archivos_Entregados_JTable.setShowGrid(true);
                archivos_Entregados_JTable.setShowVerticalLines(false);
                archivos_Entregados_JTable.setRowSorter(new TableRowSorter(archivos_Entregados_JTable.getModel()));
                archivos_Entregados_JTable.addMouseListener(new MouseAdapter() {

                    @Override
                    public void mousePressed(MouseEvent e) {
                        if (e.getClickCount() == 2) {

                            JTable tabla = (JTable) e.getComponent();
                            int columna = tabla.getSelectedColumn();

                            // Abrir
                            if (columna == 0){
                                int fila = tabla.getRowSorter().convertRowIndexToModel(tabla.getSelectedRow());
                                DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
                                Celda_Renderer celda = (Celda_Renderer) modelo.getValueAt(fila, 0);
                                String extension = FilenameUtils.getExtension(celda.Texto());
                                String ruta = celda.ID();
                                CourseRoom.Utilerias.Abrir_Archivo(ruta, extension, celda.Texto());
                            }
                        }
                    }
                });
                archivos_Entregados_JScrollPane.setViewportView(archivos_Entregados_JTable);

                calificar_JButton.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
                calificar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/rating.png"))); // NOI18N
                calificar_JButton.setText("Calificar");
                calificar_JButton.setToolTipText("");
                ((ImageIcon)calificar_JButton.getIcon()).getImage().flush();
                calificar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        calificar_JButtonMouseClicked(evt);
                    }
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        calificar_JButtonMouseEntered(evt);
                    }
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        calificar_JButtonMouseExited(evt);
                    }
                });

                fecha_Entregado_JLabel.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
                fecha_Entregado_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                fecha_Entregado_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/circular-clock.png"))); // NOI18N
                fecha_Entregado_JLabel.setOpaque(true);

                es_Tarea_Grupal_JLabel.setFont(new java.awt.Font("Gadugi", 3, 15)); // NOI18N
                es_Tarea_Grupal_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                es_Tarea_Grupal_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/group_2.png"))); // NOI18N
                es_Tarea_Grupal_JLabel.setText("Esta Tarea Se Envió De Manera Grupal");
                es_Tarea_Grupal_JLabel.setOpaque(true);
                ((ImageIcon)es_Tarea_Grupal_JLabel.getIcon()).getImage().flush();

                javax.swing.GroupLayout archivos_Entregados_JPanelLayout = new javax.swing.GroupLayout(archivos_Entregados_JPanel);
                archivos_Entregados_JPanel.setLayout(archivos_Entregados_JPanelLayout);
                archivos_Entregados_JPanelLayout.setHorizontalGroup(
                    archivos_Entregados_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(archivos_Entregados_JPanelLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(archivos_Entregados_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(archivos_Entregados_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, archivos_Entregados_JPanelLayout.createSequentialGroup()
                                .addComponent(es_Tarea_Grupal_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fecha_Entregado_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(archivos_Entregados_JPanelLayout.createSequentialGroup()
                                .addComponent(calificar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, 0))
                );
                archivos_Entregados_JPanelLayout.setVerticalGroup(
                    archivos_Entregados_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(archivos_Entregados_JPanelLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(archivos_Entregados_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_Entregado_JLabel)
                            .addComponent(es_Tarea_Grupal_JLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(archivos_Entregados_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calificar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                );

                tarea_JLayeredPane.add(archivos_Entregados_JPanel, "Archivos_Entregados");

                retroalimentacion_JPanel.setOpaque(false);

                retroalimentacion_JScrollPane.setBorder(null);
                retroalimentacion_JScrollPane.setOpaque(false);

                retroalimentacion_JTable.setAutoCreateRowSorter(true);
                retroalimentacion_JTable.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
                retroalimentacion_JTable.setModel(

                    new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                            "Retroalimentación", "Fecha", "Adjunto", "Descargar"
                        }
                    ) {
                        boolean[] canEdit = new boolean [] {
                            false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                            return canEdit [columnIndex];
                        }

                        @Override
                        public Class getColumnClass(int column)
                        {
                            for(int i = 0; i < retroalimentacion_JTable.getRowCount(); i++)
                            {
                                //The first valid value of a cell of given column is retrieved.
                                if(getValueAt(i,column) != null)
                                {
                                    return getValueAt(i, column).getClass();
                                }
                            }
                            //if no valid value is found, default renderer is returned.
                            return super.getColumnClass(column);
                        }
                    });
                    retroalimentacion_JTable.setOpaque(false);
                    retroalimentacion_JTable.setRowHeight(90);
                    retroalimentacion_JTable.setRowMargin(15);
                    retroalimentacion_JTable.setShowGrid(true);
                    retroalimentacion_JTable.setRowSorter(new TableRowSorter(retroalimentacion_JTable.getModel()));
                    retroalimentacion_JTable.addMouseListener(new MouseAdapter() {

                        @Override
                        public void mousePressed(MouseEvent e) {
                            if (e.getClickCount() == 2) {

                                JTable tabla = (JTable) e.getComponent();
                                int columna = tabla.getSelectedColumn();

                                // Abrir
                                if (columna == 2) {
                                    int fila = tabla.getRowSorter().convertRowIndexToModel(tabla.getSelectedRow());
                                    DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
                                    Celda_Renderer celda = (Celda_Renderer)modelo.getValueAt(fila, columna);

                                    if(celda.Tiene_Icono()){
                                        String extension = FilenameUtils.getExtension(celda.Texto());
                                        String ruta = celda.ID();
                                        CourseRoom.Utilerias.Abrir_Archivo(ruta, extension, celda.Texto());
                                    }
                                } // Descargar
                                else if (columna == 3) {

                                }
                            }
                        }
                    });
                    retroalimentacion_JScrollPane.setViewportView(retroalimentacion_JTable);

                    retroalimentar_JButton.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
                    retroalimentar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/online-registration.png"))); // NOI18N
                    retroalimentar_JButton.setText("Retroalimentar");
                    retroalimentar_JButton.setToolTipText("");
                    ((ImageIcon)retroalimentar_JButton.getIcon()).getImage().flush();
                    retroalimentar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                            retroalimentar_JButtonMouseClicked(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                            retroalimentar_JButtonMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                            retroalimentar_JButtonMouseExited(evt);
                        }
                    });

                    javax.swing.GroupLayout retroalimentacion_JPanelLayout = new javax.swing.GroupLayout(retroalimentacion_JPanel);
                    retroalimentacion_JPanel.setLayout(retroalimentacion_JPanelLayout);
                    retroalimentacion_JPanelLayout.setHorizontalGroup(
                        retroalimentacion_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(retroalimentacion_JPanelLayout.createSequentialGroup()
                            .addGap(0, 0, 0)
                            .addGroup(retroalimentacion_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(retroalimentacion_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
                                .addGroup(retroalimentacion_JPanelLayout.createSequentialGroup()
                                    .addComponent(retroalimentar_JButton)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(0, 0, 0))
                    );
                    retroalimentacion_JPanelLayout.setVerticalGroup(
                        retroalimentacion_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(retroalimentacion_JPanelLayout.createSequentialGroup()
                            .addGap(0, 0, 0)
                            .addComponent(retroalimentacion_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(retroalimentar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    );

                    tarea_JLayeredPane.add(retroalimentacion_JPanel, "Retroalimentacion");

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                    this.setLayout(layout);
                    layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tarea_JLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
                                .addComponent(titulo_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE))
                            .addGap(32, 32, 32))
                    );
                    layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(titulo_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tarea_JLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                    );
                }// </editor-fold>//GEN-END:initComponents

    private void chat_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chat_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            ((CardLayout)tarea_JLayeredPane.getLayout()).show(tarea_JLayeredPane, "Chat");
            carta_Visible = 1;
            Carta_Visible();
            
        }
    }//GEN-LAST:event_chat_JButtonMouseClicked

    private void informacion_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacion_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            ((CardLayout) tarea_JLayeredPane.getLayout()).show(tarea_JLayeredPane, "Informacion");
            carta_Visible = 0;
            Carta_Visible();
        }
    }//GEN-LAST:event_informacion_JButtonMouseClicked

    private void entregar_Tarea_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entregar_Tarea_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            ((CardLayout) tarea_JLayeredPane.getLayout()).show(tarea_JLayeredPane, "Archivos_Entregados");
            carta_Visible = 2;
            Carta_Visible();
        }
    }//GEN-LAST:event_entregar_Tarea_JButtonMouseClicked

    private void regresar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Profesor_Panel.Mostrar_Vista("Tareas");
        }
    }//GEN-LAST:event_regresar_JButtonMouseClicked

    private void regresar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseEntered
        // TODO add your handling code here:
        regresar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
    }//GEN-LAST:event_regresar_JButtonMouseEntered

    private void regresar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseExited
        // TODO add your handling code here:
        regresar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
    }//GEN-LAST:event_regresar_JButtonMouseExited

    private void curso_JLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curso_JLabelMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){

        }
    }//GEN-LAST:event_curso_JLabelMouseClicked

    private void actualizar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){

        }
    }//GEN-LAST:event_actualizar_JButtonMouseClicked

    private void actualizar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_JButtonMouseEntered
        // TODO add your handling code here:
        actualizar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
    }//GEN-LAST:event_actualizar_JButtonMouseEntered

    private void actualizar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizar_JButtonMouseExited
        // TODO add your handling code here:
        actualizar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
    }//GEN-LAST:event_actualizar_JButtonMouseExited

    private void retroalimentacion_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retroalimentacion_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            ((CardLayout) tarea_JLayeredPane.getLayout()).show(tarea_JLayeredPane, "Retroalimentacion");
            carta_Visible = 3;
            Carta_Visible();
        }
    }//GEN-LAST:event_retroalimentacion_JButtonMouseClicked

    private void enviar_Archivo_Chat_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_Archivo_Chat_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Enviar_Archivos();
        }
    }//GEN-LAST:event_enviar_Archivo_Chat_JButtonMouseClicked

    private void enviar_Archivo_Chat_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_Archivo_Chat_JButtonMouseEntered
        // TODO add your handling code here:
        enviar_Archivo_Chat_JButton.setBackground(CourseRoom.Utilerias.Primer_Color());
    }//GEN-LAST:event_enviar_Archivo_Chat_JButtonMouseEntered

    private void enviar_Archivo_Chat_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_Archivo_Chat_JButtonMouseExited
        // TODO add your handling code here:
        enviar_Archivo_Chat_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
    }//GEN-LAST:event_enviar_Archivo_Chat_JButtonMouseExited

    private void redactar_Mensaje_Chat_JTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_redactar_Mensaje_Chat_JTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Enviar_Mensaje();
        }
    }//GEN-LAST:event_redactar_Mensaje_Chat_JTextFieldKeyPressed

    private void calificar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calificar_JButtonMouseExited
        // TODO add your handling code here:
        calificar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
        calificar_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
    }//GEN-LAST:event_calificar_JButtonMouseExited

    private void calificar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calificar_JButtonMouseEntered
        // TODO add your handling code here:
        calificar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
        calificar_JButton.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
    }//GEN-LAST:event_calificar_JButtonMouseEntered

    private void calificar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calificar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){

            fecha_Entregado_JLabel.setText(CourseRoom.Utilerias.Concatenar("Actualizado: ",LocalDateTime.now().toString()));
        }
    }//GEN-LAST:event_calificar_JButtonMouseClicked

    private void retroalimentar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retroalimentar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Retroalimentar_Profesor_Frame retroalimentar_Profesor_Frame
                     = new Retroalimentar_Profesor_Frame();
            retroalimentar_Profesor_Frame.setVisible(true);
        }
    }//GEN-LAST:event_retroalimentar_JButtonMouseClicked

    private void retroalimentar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retroalimentar_JButtonMouseEntered
        // TODO add your handling code here:
        retroalimentar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
        retroalimentar_JButton.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        
    }//GEN-LAST:event_retroalimentar_JButtonMouseEntered

    private void retroalimentar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retroalimentar_JButtonMouseExited
        // TODO add your handling code here:
        retroalimentar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
        retroalimentar_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        
    }//GEN-LAST:event_retroalimentar_JButtonMouseExited

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar_JButton;
    private javax.swing.JPanel archivos_Entregados_JPanel;
    private javax.swing.JScrollPane archivos_Entregados_JScrollPane;
    private javax.swing.JTable archivos_Entregados_JTable;
    private javax.swing.JButton calificar_JButton;
    private javax.swing.JButton chat_JButton;
    private javax.swing.JPanel chat_JPanel;
    private javax.swing.JLabel curso_JLabel;
    private javax.swing.JScrollPane descripcion_JScrollPane;
    private javax.swing.JTextPane descripcion_JTextPane;
    private javax.swing.JButton entregar_Tarea_JButton;
    private javax.swing.JButton enviar_Archivo_Chat_JButton;
    private javax.swing.JPanel enviar_Mensaje_Chat_JPanel;
    private javax.swing.JLabel es_Tarea_Grupal_JLabel;
    private javax.swing.JLabel estatus_Tarea_JLabel;
    private javax.swing.JLabel fecha_Creacion_JLabel;
    private javax.swing.JLabel fecha_Entrega_JLabel;
    private javax.swing.JLabel fecha_Entregado_JLabel;
    private javax.swing.JButton informacion_JButton;
    private javax.swing.JPanel informacion_Tarea_JPanel;
    private javax.swing.JScrollPane mensajes_Chat_JScrollPane;
    private javax.swing.JTable mensajes_Chat_JTable;
    private javax.swing.JTextField redactar_Mensaje_Chat_JTextField;
    private javax.swing.JButton regresar_JButton;
    private javax.swing.JButton retroalimentacion_JButton;
    private javax.swing.JPanel retroalimentacion_JPanel;
    private javax.swing.JScrollPane retroalimentacion_JScrollPane;
    private javax.swing.JTable retroalimentacion_JTable;
    private javax.swing.JButton retroalimentar_JButton;
    private javax.swing.JLayeredPane tarea_JLayeredPane;
    private javax.swing.JLabel titulo_JLabel;
    private javax.swing.JPanel titulo_JPanel;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void Iniciar_Componentes() {
        
        carta_Visible = 0;
        Font gadugi = new Font("Gadugi", Font.BOLD, 16);
        
        descripcion_JTextPane.setText(
                CourseRoom.Utilerias.Formato_HTML_Izquierda(CourseRoom.Utilerias.lorem().paragraph(40)));
        
        descripcion_JScrollPane.getViewport().setOpaque(false);
        descripcion_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        
        archivos_Entregados_JScrollPane.getViewport().setOpaque(false);
        archivos_Entregados_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        archivos_Entregados_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
        
        retroalimentacion_JScrollPane.getViewport().setOpaque(false);
        retroalimentacion_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        retroalimentacion_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
        
        mensajes_Chat_JScrollPane.getViewport().setOpaque(false);
        mensajes_Chat_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        mensajes_Chat_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);

        archivos_Entregados_JTable.getTableHeader().setFont(gadugi);
        retroalimentacion_JTable.getTableHeader().setFont(gadugi);
        mensajes_Chat_JTable.getTableHeader().setFont(gadugi);
        
        retroalimentacion_JTable.setDefaultRenderer(Celda_Renderer.class, new Celda_Renderer());
        archivos_Entregados_JTable.setDefaultRenderer(Celda_Renderer.class, new Celda_Renderer());
        mensajes_Chat_JTable.setDefaultRenderer(Celda_Renderer.class, new Celda_Renderer());
        
        Colorear_Componentes();
    }

    @Override
    public void Colorear_Componentes() {
        
        titulo_JPanel.setBackground(CourseRoom.Utilerias.Segundo_Color());
        
        Carta_Visible();
        
        titulo_JLabel.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        titulo_JLabel.setBackground(CourseRoom.Utilerias.Tercer_Color());
        
        regresar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
        
        actualizar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
        
        retroalimentar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
        retroalimentar_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        
        calificar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
        calificar_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        
        curso_JLabel.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        curso_JLabel.setBackground(CourseRoom.Utilerias.Segundo_Color());
        
        estatus_Tarea_JLabel.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        estatus_Tarea_JLabel.setBackground(CourseRoom.Utilerias.Tercer_Color());
        
        fecha_Entrega_JLabel.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        fecha_Entrega_JLabel.setBackground(CourseRoom.Utilerias.Tercer_Color());
        
        fecha_Creacion_JLabel.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        fecha_Creacion_JLabel.setBackground(CourseRoom.Utilerias.Segundo_Color());
        
        fecha_Entregado_JLabel.setBackground(CourseRoom.Utilerias.Segundo_Color());
        fecha_Entregado_JLabel.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        
        descripcion_JTextPane.setForeground(CourseRoom.Utilerias.Primer_Color_Fuente());
        
        redactar_Mensaje_Chat_JTextField.setBackground(CourseRoom.Utilerias.Primer_Color());
        redactar_Mensaje_Chat_JTextField.setForeground(CourseRoom.Utilerias.Primer_Color_Fuente());
        
        es_Tarea_Grupal_JLabel.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        es_Tarea_Grupal_JLabel.setBackground(CourseRoom.Utilerias.Segundo_Color());
        
        enviar_Mensaje_Chat_JPanel.setBackground(CourseRoom.Utilerias.Segundo_Color());
        enviar_Archivo_Chat_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
        
        archivos_Entregados_JTable.getTableHeader().setBackground(CourseRoom.Utilerias.Segundo_Color());
        archivos_Entregados_JTable.getTableHeader().setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        archivos_Entregados_JTable.setGridColor(CourseRoom.Utilerias.Segundo_Color());
        
        retroalimentacion_JTable.getTableHeader().setBackground(CourseRoom.Utilerias.Segundo_Color());
        retroalimentacion_JTable.getTableHeader().setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        retroalimentacion_JTable.setGridColor(CourseRoom.Utilerias.Segundo_Color());
        
        mensajes_Chat_JTable.getTableHeader().setBackground(CourseRoom.Utilerias.Tercer_Color());
        mensajes_Chat_JTable.getTableHeader().setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        mensajes_Chat_JTable.setGridColor(CourseRoom.Utilerias.Segundo_Color());
        
        DefaultTableModel modelo;
        Celda_Renderer celda;
        
        modelo = (DefaultTableModel) archivos_Entregados_JTable.getModel();
        for (int i = 0; i < archivos_Entregados_JTable.getRowCount(); i++) {
            for (int j = 0; j < modelo.getColumnCount(); j++) {
                celda = (Celda_Renderer) modelo.getValueAt(i, j);
                celda.Color_Fuente(CourseRoom.Utilerias.Primer_Color_Fuente());
            }
        }
        
        modelo = (DefaultTableModel) retroalimentacion_JTable.getModel();
        for (int i = 0; i < retroalimentacion_JTable.getRowCount(); i++) {
            for (int j = 0; j < modelo.getColumnCount(); j++) {
                celda = (Celda_Renderer) modelo.getValueAt(i, j);
                celda.Color_Fuente(CourseRoom.Utilerias.Primer_Color_Fuente());
            }
        }
        
        
        modelo = (DefaultTableModel) mensajes_Chat_JTable.getModel();
        for(int i = 0; i < mensajes_Chat_JTable.getRowCount();i++){
            for(int j = 0; j < modelo.getColumnCount(); j++){
                celda = (Celda_Renderer)modelo.getValueAt(i, j);
                celda.Color_Fuente(CourseRoom.Utilerias.Primer_Color_Fuente());
            }
        }
        
        
        Font gadugi = new Font("Gadugi", 0, 18);
        
        descripcion_JScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(CourseRoom.Utilerias.Primer_Color_Fuente()), "Descripcion De La Tarea", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION, gadugi, CourseRoom.Utilerias.Primer_Color_Fuente()));

    }

    
    public void Retroalimentar(String retroalimentacion, File archivo_Abierto) {
        
        Celda_Renderer[] celdas = new Celda_Renderer[4];

        DefaultTableModel modelo = (DefaultTableModel) retroalimentacion_JTable.getModel();
        ImageIcon icono_Abrir = new ImageIcon(getClass().getResource("/recursos/iconos/box.png"));
        ImageIcon icono_Descargar = new ImageIcon(getClass().getResource("/recursos/iconos/download.png"));

        celdas[0] = new Celda_Renderer(retroalimentacion,"");
        celdas[1] = new Celda_Renderer(CourseRoom.Utilerias.Fecha_Hora_Local(),"");

        if(archivo_Abierto != null){
            celdas[2] = new Celda_Renderer(icono_Abrir,archivo_Abierto.getName(),archivo_Abierto.getAbsolutePath());
            celdas[3] = new Celda_Renderer(icono_Descargar,"");
        }else{
            celdas[2] = new Celda_Renderer("No Disponible","");
            celdas[3] = new Celda_Renderer("No Disponible","");
        }
        modelo.addRow(celdas);

        retroalimentacion_JTable.setRowHeight(modelo.getRowCount()-1,CourseRoom.Utilerias.Altura_Fila_Tabla_Icono(retroalimentacion.length()));
        
    }
    
    @Override
    public void Enviar_Mensaje() {
        
        String mensaje = redactar_Mensaje_Chat_JTextField.getText();
        if (!mensaje.isEmpty() && !mensaje.isBlank()) {
            String emisor = CourseRoom.Utilerias.dune().character();
            String fecha = CourseRoom.Utilerias.Fecha_Hora_Local();
            Celda_Renderer[] celdas = new Celda_Renderer[3];
  
            Celda_Renderer celda;
            celda = new Celda_Renderer(emisor,"");
            celdas[0] = celda;
            celda = new Celda_Renderer(mensaje,"");
            celdas[1] = celda;
            celda = new Celda_Renderer(fecha,"");
            celdas[2] = celda;
            DefaultTableModel modelo = (DefaultTableModel) mensajes_Chat_JTable.getModel();
            modelo.addRow(celdas);
            mensajes_Chat_JTable.setRowHeight(modelo.getRowCount()-1, CourseRoom.Utilerias.Altura_Fila_Tabla(mensaje.length()));
            
            redactar_Mensaje_Chat_JTextField.setText("");
            redactar_Mensaje_Chat_JTextField.setCaretPosition(0);
        }
    }

    @Override
    public void Enviar_Archivos() {
        JFileChooser escogedor_Archivos = new JFileChooser();
        escogedor_Archivos.setFileSelectionMode(JFileChooser.FILES_ONLY);
        escogedor_Archivos.setApproveButtonText("Enviar Archivo(s)");
        escogedor_Archivos.setMultiSelectionEnabled(true);
        int resultado = escogedor_Archivos.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File[] archivos_Abiertos = escogedor_Archivos.getSelectedFiles();

            if (archivos_Abiertos != null) {

                String emisor;
                String fecha;
                String ruta;
                String nombre_Archivo;
                Celda_Renderer[] celdas = new Celda_Renderer[3];
                DefaultTableModel modelo = (DefaultTableModel) mensajes_Chat_JTable.getModel();
                Celda_Renderer celda;
                ImageIcon icono_Abrir = new ImageIcon(getClass().getResource("/recursos/iconos/box.png"));
                for (File archivo_Abierto : archivos_Abiertos) {
                    ruta = archivo_Abierto.getAbsolutePath();
                    nombre_Archivo = archivo_Abierto.getName();
                    emisor = CourseRoom.Utilerias.dune().character();
                    fecha = CourseRoom.Utilerias.Fecha_Hora_Local();
                    
                    celda = new Celda_Renderer(emisor,"");
                    celdas[0] = celda;
                    celda = new Celda_Renderer(icono_Abrir,nombre_Archivo,ruta);
                    celdas[1] = celda;
                    celda = new Celda_Renderer(fecha,"");
                    celdas[2] = celda;
                    
                    modelo.addRow(celdas);
                }
            }

        }

    }
   

    @Override
    public void Limpiar() {
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) archivos_Entregados_JTable.getModel();
        modelo.setRowCount(0);
        modelo = (DefaultTableModel) retroalimentacion_JTable.getModel();
        modelo.setRowCount(0);
        modelo = (DefaultTableModel) mensajes_Chat_JTable.getModel();
        modelo.setRowCount(0);
        
    }

    @Override
    public void Carta_Visible() {
        switch (carta_Visible) {
            case 0:
                informacion_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
                chat_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                entregar_Tarea_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                retroalimentacion_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                break;
            case 1:
                informacion_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                chat_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
                entregar_Tarea_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                retroalimentacion_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                break;
            case 2:
                informacion_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                chat_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                entregar_Tarea_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
                retroalimentacion_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                break;
            case 3:
                informacion_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                chat_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                entregar_Tarea_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
                retroalimentacion_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
                break;
            
        }
    }
    
    private class Retroalimentar_Profesor_Frame extends javax.swing.JDialog implements Componentes_Interface{

        private File archivo_Adjunto;
        
        public Retroalimentar_Profesor_Frame() {

            initComponents();

            Iniciar_Componentes();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            contenido_JPanel = new javax.swing.JPanel();
            retroalimentar_JButton = new javax.swing.JButton();
            retroalimentacion_JScrollPane = new javax.swing.JScrollPane();
            retroalimentacion_JTextPane = new javax.swing.JTextPane();
            cerrar_JButton = new javax.swing.JButton();
            archivo_Adjunto_JLabel = new javax.swing.JLabel();
            adjuntar_Archivo_JButton = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setAlwaysOnTop(true);
            setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
            setMinimumSize(new java.awt.Dimension(1000, 300));
            setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            setUndecorated(true);
            setResizable(false);
            setType(java.awt.Window.Type.POPUP);
            getContentPane().setLayout(new java.awt.CardLayout());

            contenido_JPanel.setMaximumSize(new java.awt.Dimension(800, 227));
            contenido_JPanel.setMinimumSize(new java.awt.Dimension(800, 227));
            contenido_JPanel.setPreferredSize(new java.awt.Dimension(800, 227));

            retroalimentar_JButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            retroalimentar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/feedback.png"))); // NOI18N
            retroalimentar_JButton.setText("Retroalimentar");
            ((ImageIcon)retroalimentar_JButton.getIcon()).getImage().flush();
            retroalimentar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    retroalimentar_JButtonMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    retroalimentar_JButtonMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    retroalimentar_JButtonMouseExited(evt);
                }
            });

            retroalimentacion_JScrollPane.setBorder(null);

            retroalimentacion_JTextPane.setBorder(null);
            retroalimentacion_JTextPane.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
            retroalimentacion_JScrollPane.setViewportView(retroalimentacion_JTextPane);

            cerrar_JButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            cerrar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/close.png"))); // NOI18N
            cerrar_JButton.setText("Cancelar");
            ((ImageIcon)cerrar_JButton.getIcon()).getImage().flush();
            cerrar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    cerrar_JButtonMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    cerrar_JButtonMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    cerrar_JButtonMouseExited(evt);
                }
            });

            archivo_Adjunto_JLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            archivo_Adjunto_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            archivo_Adjunto_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/attachment.png"))); // NOI18N

            adjuntar_Archivo_JButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            adjuntar_Archivo_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/docs.png"))); // NOI18N
            adjuntar_Archivo_JButton.setText("Adjuntar Archivo");
            ((ImageIcon)retroalimentar_JButton.getIcon()).getImage().flush();
            adjuntar_Archivo_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    adjuntar_Archivo_JButtonMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    adjuntar_Archivo_JButtonMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    adjuntar_Archivo_JButtonMouseExited(evt);
                }
            });

            javax.swing.GroupLayout contenido_JPanelLayout = new javax.swing.GroupLayout(contenido_JPanel);
            contenido_JPanel.setLayout(contenido_JPanelLayout);
            contenido_JPanelLayout.setHorizontalGroup(
                contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contenido_JPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contenido_JPanelLayout.createSequentialGroup()
                            .addComponent(cerrar_JButton)
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addComponent(adjuntar_Archivo_JButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(retroalimentar_JButton))
                        .addComponent(retroalimentacion_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                        .addComponent(archivo_Adjunto_JLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            contenido_JPanelLayout.setVerticalGroup(
                contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contenido_JPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(retroalimentacion_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(archivo_Adjunto_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(adjuntar_Archivo_JButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cerrar_JButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(retroalimentar_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );

            getContentPane().add(contenido_JPanel, "card2");

            pack();
        }// </editor-fold>                        

        private void retroalimentar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                    
            // TODO add your handling code here:
            if(SwingUtilities.isLeftMouseButton(evt)){
                if (!retroalimentacion_JTextPane.getText().isBlank() && !retroalimentacion_JTextPane.getText().isEmpty()) {

                    Retroalimentar(retroalimentacion_JTextPane.getText(),archivo_Adjunto);

                    this.dispose();
                }

            }
        }                                                   

        private void retroalimentar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {                                                    
            // TODO add your handling code here:
            retroalimentar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
            retroalimentar_JButton.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        }                                                   

        private void retroalimentar_JButtonMouseExited(java.awt.event.MouseEvent evt) {                                                   
            // TODO add your handling code here:
            retroalimentar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
            retroalimentar_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        }                                                  

        private void cerrar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {                                            
            // TODO add your handling code here:
            if(SwingUtilities.isLeftMouseButton(evt)){
                this.dispose();
            }
        }                                           

        private void cerrar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {                                            
            // TODO add your handling code here:
            cerrar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
            cerrar_JButton.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        }                                           

        private void cerrar_JButtonMouseExited(java.awt.event.MouseEvent evt) {                                           
            // TODO add your handling code here:
            cerrar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
            cerrar_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        }                                          

        private void adjuntar_Archivo_JButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                      
            // TODO add your handling code here:
            if(SwingUtilities.isLeftMouseButton(evt)){
                Adjuntar_Archivo();
            }
        }                                                     

        private void adjuntar_Archivo_JButtonMouseEntered(java.awt.event.MouseEvent evt) {                                                      
            // TODO add your handling code here:
            adjuntar_Archivo_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
            adjuntar_Archivo_JButton.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        }                                                     

        private void adjuntar_Archivo_JButtonMouseExited(java.awt.event.MouseEvent evt) {                                                     
            // TODO add your handling code here:
            adjuntar_Archivo_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
            adjuntar_Archivo_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        }                                                    


        // Variables declaration - do not modify                     
        private javax.swing.JButton adjuntar_Archivo_JButton;
        private javax.swing.JLabel archivo_Adjunto_JLabel;
        private javax.swing.JButton cerrar_JButton;
        private javax.swing.JPanel contenido_JPanel;
        private javax.swing.JScrollPane retroalimentacion_JScrollPane;
        private javax.swing.JTextPane retroalimentacion_JTextPane;
        private javax.swing.JButton retroalimentar_JButton;
        // End of variables declaration                   

        @Override
        public void Iniciar_Componentes() {

            this.setLocationRelativeTo(null);

            Font gadugi = new java.awt.Font("Gadugi", 1, 16);

            retroalimentacion_JScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(),
                    "Retroalimentación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                    javax.swing.border.TitledBorder.DEFAULT_POSITION,
                    gadugi, CourseRoom.Utilerias.Tercer_Color_Fuente()));

            retroalimentacion_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
            retroalimentacion_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);

            Colorear_Componentes();
        }

        @Override
        public void Colorear_Componentes() {

            retroalimentacion_JScrollPane.setBackground(CourseRoom.Utilerias.Tercer_Color());
            retroalimentacion_JScrollPane.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());

            retroalimentacion_JTextPane.setBackground(CourseRoom.Utilerias.Tercer_Color());
            retroalimentacion_JTextPane.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
            retroalimentacion_JTextPane.setCaretColor(CourseRoom.Utilerias.Tercer_Color_Fuente());


            contenido_JPanel.setBackground(CourseRoom.Utilerias.Segundo_Color());

            cerrar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
            cerrar_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());

            adjuntar_Archivo_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
            adjuntar_Archivo_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());

            retroalimentar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
            retroalimentar_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());

        }


        private void Adjuntar_Archivo(){
            JFileChooser escogedor_Archivo = new JFileChooser();
            escogedor_Archivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
            escogedor_Archivo.setApproveButtonText("Subir Archivo(s)");
            escogedor_Archivo.setMultiSelectionEnabled(false);
            int resultado = escogedor_Archivo.showOpenDialog(this);
            if (resultado == JFileChooser.APPROVE_OPTION) {
                archivo_Adjunto = escogedor_Archivo.getSelectedFile();
                if(archivo_Adjunto != null){
                    archivo_Adjunto_JLabel.setText(archivo_Adjunto.getName());
                }
            }
        }

    }
    
}
