/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles.estudiantes.chats;

import clases.Celda_Renderer;
import datos.colecciones.Lista;
import datos.estructuras.Nodo;
import interfaces.Componentes_Interface;
import interfaces.Limpieza_Interface;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import main.CourseRoom;
import paneles.estudiantes.Tablero_Estudiante_Panel;

/**
 *
 * @author LENOVO
 */
public class Buscar_Chats_Estudiante_Panel extends javax.swing.JPanel implements Limpieza_Interface, Componentes_Interface{

    private Lista<Chat_Estudiante_Panel> lista_Chats;
    
    /**
     * Creates new form Cursos_Agrupados_Estudiante_Panel
     */
    public Buscar_Chats_Estudiante_Panel() {
        initComponents();
        
        Iniciar_Componentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscar_JTextField = new javax.swing.JTextField();
        chats_JButton = new javax.swing.JButton();
        chats_JScrollPane = new javax.swing.JScrollPane();
        chats_JTable = new javax.swing.JTable();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1080, 630));

        buscar_JTextField.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        buscar_JTextField.setToolTipText("<html> <h3>Buscar chats. Presiona ENTER para realizar la búsqueda</h3> </html>");
        buscar_JTextField.setBorder(null);
        buscar_JTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscar_JTextFieldKeyPressed(evt);
            }
        });

        chats_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/video-chat.png"))); // NOI18N
        chats_JButton.setToolTipText("<html>\n<h3>Regresar a mis chats personales</h3>\n</html>");
        chats_JButton.setBorder(null);
        chats_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chats_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chats_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chats_JButtonMouseExited(evt);
            }
        });

        chats_JScrollPane.setBorder(null);
        chats_JScrollPane.setOpaque(false);

        chats_JTable.setAutoCreateRowSorter(true);
        chats_JTable.setModel(

            new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Chat", "Ultimo Mensaje", "Fecha", "No Leídos"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }

                @Override
                public Class getColumnClass(int column)
                {
                    for(int i = 0; i < chats_JTable.getRowCount(); i++)
                    {
                        //The first valid value of a cell of given column is retrieved.
                        if(getValueAt(i,column) != null)
                        {
                            return getValueAt(i, column).getClass();
                        }
                    }
                    //if no valid value is found, default renderer is returned.
                    return super.getColumnClass(column);
                }
            });
            chats_JTable.setOpaque(false);
            chats_JTable.setRowHeight(100);
            chats_JTable.setRowMargin(15);
            chats_JTable.setShowGrid(true);
            chats_JTable.setShowVerticalLines(false);
            chats_JTable.setRowSorter(new TableRowSorter(chats_JTable.getModel()));
            chats_JScrollPane.setViewportView(chats_JTable);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chats_JButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buscar_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE))
                        .addComponent(chats_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buscar_JTextField)
                        .addComponent(chats_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chats_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addContainerGap())
            );
        }// </editor-fold>//GEN-END:initComponents

    private void buscar_JTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar_JTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
        }
        
    }//GEN-LAST:event_buscar_JTextFieldKeyPressed

    private void chats_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chats_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Pagina_Chats_Estudiante_Panel.Mostrar_Chats();
        }
    }//GEN-LAST:event_chats_JButtonMouseClicked

    private void chats_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chats_JButtonMouseEntered
        // TODO add your handling code here:
        chats_JButton.setBackground(CourseRoom.Segundo_Color());
    }//GEN-LAST:event_chats_JButtonMouseEntered

    private void chats_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chats_JButtonMouseExited
        // TODO add your handling code here:
        chats_JButton.setBackground(CourseRoom.Primer_Color());
    }//GEN-LAST:event_chats_JButtonMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar_JTextField;
    private javax.swing.JButton chats_JButton;
    private javax.swing.JScrollPane chats_JScrollPane;
    private static javax.swing.JTable chats_JTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Iniciar_Componentes() {
        chats_JScrollPane.getViewport().setOpaque(false);
        chats_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        chats_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);

        lista_Chats = new Lista<>();

        Font gadugi = new Font("Gadugi", Font.BOLD, 16);
        chats_JTable.getTableHeader().setFont(gadugi);

        chats_JTable.setDefaultRenderer(Celda_Renderer.class, new Celda_Renderer());
        
        chats_JTable.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                if (e.getClickCount() == 2) {

                    JTable tabla = (JTable) e.getComponent();
                    int fila = tabla.getRowSorter().convertRowIndexToModel(tabla.getSelectedRow());
                    int columna = tabla.getSelectedColumn();

                    DefaultTableModel modelo = (DefaultTableModel) chats_JTable.getModel();

                    Celda_Renderer celda = (Celda_Renderer) modelo.getValueAt(fila, columna);

                    Tablero_Estudiante_Panel.Mostrar_Vista(celda.ID());

                }
            }
        });
    }

    @Override
    public void Colorear_Componentes() {
        Font gadugi = new java.awt.Font("Gadugi", 1, 16);
        buscar_JTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(),
                "Buscar Chats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                gadugi, CourseRoom.Tercer_Color_Fuente()));
        
        buscar_JTextField.setBackground(CourseRoom.Tercer_Color());
        buscar_JTextField.setForeground(CourseRoom.Tercer_Color_Fuente());
        buscar_JTextField.setCaretColor(CourseRoom.Tercer_Color_Fuente());
        
        chats_JButton.setBackground(CourseRoom.Primer_Color());
        
        chats_JTable.getTableHeader().setBackground(CourseRoom.Segundo_Color());
        chats_JTable.getTableHeader().setForeground(CourseRoom.Segundo_Color_Fuente());

        Celda_Renderer celda;
        DefaultTableModel modelo = (DefaultTableModel) chats_JTable.getModel();
        for (int i = 0; i < chats_JTable.getRowCount(); i++) {
            for (int j = 0; j < 4; j++) {
                celda = (Celda_Renderer) modelo.getValueAt(i, j);
                celda.Color_Fuente(CourseRoom.Primer_Color_Fuente());
            }
        }

        Chat_Estudiante_Panel chat_Estudiante_Panel;
        for (Nodo<Chat_Estudiante_Panel> nodo = lista_Chats.front(); nodo != null; nodo = nodo.next()) {
            chat_Estudiante_Panel = nodo.element();
            chat_Estudiante_Panel.Colorear_Componentes();
        }
        
    }
    
    @Override
    public void Limpiar() {
        lista_Chats.clear();
        chats_JTable.removeAll();
    }

}
