/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames.generales;

import interfaces.Limpieza_Interface;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JPanel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import org.icepdf.ri.common.MyAnnotationCallback;

/**
 *
 * @author LENOVO
 */
public class Lector_PDF_General_Frame extends javax.swing.JFrame implements Limpieza_Interface{

    private SwingController controlador_Swing;
    
    /**
     * Creates new form PDFReader
     */
    public Lector_PDF_General_Frame(String ruta) throws MalformedURLException {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setState(MAXIMIZED_BOTH);
        
        contenido_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        contenido_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
        
        URL url = new URL(ruta);
        controlador_Swing = new SwingController();
        SwingViewBuilder constructor_Vista_Swing = new SwingViewBuilder(controlador_Swing);
        JPanel contenido_JPanel = constructor_Vista_Swing.buildViewerPanel();
        ComponentKeyBinding.install(controlador_Swing,contenido_JPanel);
        MyAnnotationCallback mi_Llamada = new MyAnnotationCallback(controlador_Swing.getDocumentViewController());
        controlador_Swing.getDocumentViewController().setAnnotationCallback(mi_Llamada);
        controlador_Swing.openDocument(url); 
        contenido_JScrollPane.setViewportView(contenido_JPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido_JScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(contenido_JScrollPane, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
       this.Limpiar();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane contenido_JScrollPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Limpiar() {
        controlador_Swing.getDocument().dispose();
        controlador_Swing.closeDocument();
        this.dispose();
    }
}
