/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import com.github.javafaker.Faker;
import data.collections.PairDoublyLinkedList;
import data.interfaces.MainInterface;
import data.structures.Pair;
import java.awt.Color;
import java.awt.Component;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.LinearGradientPaint;
import java.awt.Point;
import java.awt.image.PixelGrabber;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Locale;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author LENOVO
 */
public class BoxAvisoPanel extends javax.swing.JPanel implements MainInterface{

    private Image avisoImage;
    private Color firstColor,secondColor;
    /**
     * Creates new form BoxAvisoPanel
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public BoxAvisoPanel(String route) {
        initComponents();
        try {
            firstColor = secondColor = Color.BLACK;
            //URL imageURL = new URL(route);
            Faker faker = new Faker(new Locale("es","MX"));
            jLabelDescripcionAviso.setText(faker.lorem().paragraph(1));
            jLabelFechaHoraAviso.setText(faker.date().birthday().toString());
            jLabelProvenenciaAviso.setText(faker.company().name());
            jLabelEstado.setText(faker.book().publisher());
            jLabelEstado.setText((faker.bool().bool()) ? "Leído" : "No Leído");
            Image getImage = ImageIO.read(getClass().getResource("/resources/images/notification.jpg"));
            avisoImage = getImage.getScaledInstance(92,92,Image.SCALE_SMOOTH);
            ImageIcon avisoIcon = new ImageIcon(avisoImage);
            jLabelFotoAviso.setIcon(avisoIcon);
            setColors(getImage);
            getImage.flush();
            getImage = null;
            avisoIcon = null;
            //imageURL = null;
        } catch (MalformedURLException ex) {
            Logger.getLogger(BoxChatPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BoxChatPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFotoAviso = new javax.swing.JLabel();
        jLabelProvenenciaAviso = new javax.swing.JLabel();
        jLabelDescripcionAviso = new javax.swing.JLabel();
        jLabelFechaHoraAviso = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();

        setBackground(java.awt.Color.black);
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(32767, 141));
        setMinimumSize(new java.awt.Dimension(598, 141));

        jLabelFotoAviso.setMaximumSize(new java.awt.Dimension(92, 92));
        jLabelFotoAviso.setMinimumSize(new java.awt.Dimension(92, 92));
        jLabelFotoAviso.setPreferredSize(new java.awt.Dimension(92, 92));
        jLabelFotoAviso.setRequestFocusEnabled(false);

        jLabelProvenenciaAviso.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        jLabelProvenenciaAviso.setForeground(java.awt.Color.white);
        jLabelProvenenciaAviso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelProvenenciaAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/notification.png"))); // NOI18N
        jLabelProvenenciaAviso.setText("Provenencia Del Aviso");
        jLabelProvenenciaAviso.setMaximumSize(new java.awt.Dimension(488, 32));
        jLabelProvenenciaAviso.setMinimumSize(new java.awt.Dimension(488, 32));
        jLabelProvenenciaAviso.setPreferredSize(new java.awt.Dimension(488, 32));

        jLabelDescripcionAviso.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        jLabelDescripcionAviso.setForeground(java.awt.Color.white);
        jLabelDescripcionAviso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDescripcionAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/announcement.png"))); // NOI18N
        jLabelDescripcionAviso.setText("Descripción Corta Del Aviso");
        jLabelDescripcionAviso.setMaximumSize(new java.awt.Dimension(417, 22));
        jLabelDescripcionAviso.setMinimumSize(new java.awt.Dimension(417, 22));
        jLabelDescripcionAviso.setPreferredSize(new java.awt.Dimension(417, 22));

        jLabelFechaHoraAviso.setFont(new java.awt.Font("Gadugi", 2, 14)); // NOI18N
        jLabelFechaHoraAviso.setForeground(java.awt.Color.white);
        jLabelFechaHoraAviso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFechaHoraAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/time-limit.png"))); // NOI18N
        jLabelFechaHoraAviso.setText("10/08/2021 05:42 P.M - Hace 18 Horas");

        jLabelEstado.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabelEstado.setForeground(java.awt.Color.white);
        jLabelEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/read.png"))); // NOI18N
        jLabelEstado.setText("No Leído");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFotoAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFechaHoraAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelProvenenciaAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescripcionAviso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFotoAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelProvenenciaAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDescripcionAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFechaHoraAviso)
                            .addComponent(jLabelEstado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        @Override
    protected void paintComponent(Graphics g) {
        
       super.paintComponent(g);
        Graphics2D graphics = (Graphics2D) g;
        int w = getWidth();
        int h = getHeight();
        Point start = new Point(0,0);
        Point end = new Point(w,h);
        float[] slice = new float[]{0.5f,1f};
        Color[] colors = new Color[]{firstColor,secondColor};
        LinearGradientPaint gp = new LinearGradientPaint(start,end, slice, colors);
        graphics.setPaint(gp);
        graphics.fillRect(0, 0, w, h);
        graphics = null;
        gp = null;
        graphics = null;
        slice = null;
        colors = null;
        
    }
    
    
    @Override
    public void setColors(Image image){
        
        try {
            Random colorRandom = new Random(System.currentTimeMillis());
            int maximum = 0;
            
            PairDoublyLinkedList<Integer, Color> colorList = new PairDoublyLinkedList<>();
            PixelGrabber pg = new PixelGrabber(image, 0, 0, -1, -1, false);
            int large = (image.getWidth(null)/3);
            if (pg.grabPixels()) {
                int[] pixels = (int[]) pg.getPixels();
                for(int i = 0; i < pixels.length; i++){
                    int pixel = pixels[i];
                    int  red = (pixel  & 0x00ff0000) >> 16;
                    int  green = (pixel & 0x0000ff00) >> 8;
                    int  blue = pixel & 0x000000ff;
                    Color color = new Color(red,green,blue);
                    Pair<Integer, Color> pair = colorList.get_from_second(color);
            
                    if (pair != null) {//exist
                        int number = pair.first()+ 1;
                        pair.first(number);
                        if (number > maximum) {
                            firstColor = color;
                            maximum = number;
                        }
                    } else {
                        colorList.push_back(1, color);
                    }

                    color = null;
                    i += colorRandom.nextInt(large+1) + large;
                }

                secondColor = firstColor;
            
                int iterations = 0;
                if(colorList.size() > 1){
                    
                    while(Math.abs(secondColor.getRGB() - firstColor.getRGB()) < 3000000){
                        int position = colorRandom.nextInt((int)colorList.size()-1);
                        secondColor = colorList.get(position).second();
                        iterations++;
                        if(iterations > 25){
                             while(firstColor.getRGB() == secondColor.getRGB()){
                                position = colorRandom.nextInt((int)colorList.size()-1);
                                secondColor = colorList.get(position).second();
                            }
                             break;
                        }
                    }
                }
              
                int red = firstColor.getRed();
                Color fontColor = (red >= 155) ? Color.BLACK : Color.WHITE;
                red = secondColor.getRed();
                Color secondFontColor = (red >= 155) ? Color.BLACK : Color.WHITE;

                colorList.clear();

                Component[] components = this.getComponents();
                for (Component component : components){
                    component.setForeground(fontColor);
                }
                
                jLabelDescripcionAviso.setForeground(fontColor);
                jLabelEstado.setForeground(secondFontColor);
                jLabelFechaHoraAviso.setForeground(fontColor);
                jLabelProvenenciaAviso.setForeground(fontColor);
                this.setBorder(javax.swing.BorderFactory.createLineBorder(fontColor));

                fontColor = null;
                colorRandom = null;
                colorList = null;
                secondFontColor = null;
                pg = null;
                pixels = null;
            }
            
        } catch (InterruptedException ex) {
            Logger.getLogger(MusicPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @Override
    public void dispose(){
        avisoImage.flush();
        avisoImage = null;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDescripcionAviso;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFechaHoraAviso;
    private javax.swing.JLabel jLabelFotoAviso;
    private javax.swing.JLabel jLabelProvenenciaAviso;
    // End of variables declaration//GEN-END:variables
}
