/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import com.github.javafaker.Faker;
import data.collections.PairDoublyLinkedList;
import data.interfaces.MainInterface;
import data.structures.Pair;
import java.awt.Color;
import java.awt.Component;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.LinearGradientPaint;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.image.PixelGrabber;
import java.util.Locale;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class ChatingPanel extends javax.swing.JPanel implements MainInterface{

    private Image chatImage;
    private Color firstColor, secondColor;
    
    /**
     * Creates new form ChatPanel
     */
    public ChatingPanel(Image image, String name) {
        initComponents();
        jScrollPaneChatsCenter.getViewport().setOpaque(false);
        jScrollPaneChatsCenter.getVerticalScrollBar().setUnitIncrement(15);
        firstColor = secondColor = Color.BLACK;
        //URL imageURL = new URL(route);
        jLabelChatName.setText(name);
        chatImage = image.getScaledInstance(360,168,Image.SCALE_SMOOTH);
        ImageIcon chatIcon = new ImageIcon(chatImage);
        jLabelFotoChat.setIcon(chatIcon);
        setColors(image);
        image.flush();
        image = null;
        chatIcon = null;
        //imageURL = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelChatTop = new JPanel(){
            @Override
            protected void paintComponent(Graphics g) {

                super.paintComponent(g);
                Graphics2D graphics = (Graphics2D) g;
                int w = getWidth();
                int h = getHeight();
                Point start = new Point(0,0);
                Point end = new Point(w,h);
                float[] slice = new float[]{0.5f,1f};
                Color[] colors = new Color[]{firstColor,secondColor};
                LinearGradientPaint gp = new LinearGradientPaint(start,end, slice, colors);
                graphics.setPaint(gp);
                graphics.fillRect(0, 0, w, h);
                graphics = null;
                gp = null;
                graphics = null;
                slice = null;
                colors = null;

            }
        };
        jLabelBack = new javax.swing.JLabel();
        jLabelChatName = new javax.swing.JLabel();
        jLabelMoreInfo = new javax.swing.JLabel();
        jLabelPersonasConQuienSeChatea = new javax.swing.JLabel();
        jPanelChatBottom = new JPanel(){
            @Override
            protected void paintComponent(Graphics g) {

                super.paintComponent(g);
                Graphics2D graphics = (Graphics2D) g;
                int w = getWidth();
                int h = getHeight();
                Point start = new Point(0,0);
                Point end = new Point(w,h);
                float[] slice = new float[]{0.5f,1f};
                Color[] colors = new Color[]{firstColor,secondColor};
                LinearGradientPaint gp = new LinearGradientPaint(start,end, slice, colors);
                graphics.setPaint(gp);
                graphics.fillRect(0, 0, w, h);
                graphics = null;
                gp = null;
                graphics = null;
                slice = null;
                colors = null;

            }
        };
        jLabelAttachFile = new javax.swing.JLabel();
        jScrollPaneMessage = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jLabelSendMessage = new javax.swing.JLabel();
        jPanelChatInformation = new JPanel(){
            @Override
            protected void paintComponent(Graphics g) {

                super.paintComponent(g);
                Graphics2D graphics = (Graphics2D) g;
                int w = getWidth();
                int h = getHeight();
                GradientPaint gp = new GradientPaint(0, 0, firstColor, 0, h, secondColor);
                graphics.setPaint(gp);
                graphics.fillRect(0, 0, w, h);
                graphics = null;
                gp = null;
                graphics = null;

            }
        };
        jTabbedPaneChatInfo = new javax.swing.JTabbedPane();
        jPanelAllFilesSend = new javax.swing.JPanel();
        jPanelMembers = new javax.swing.JPanel();
        jPanelMoreInformationChat = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jToggleButtonEditarNombre = new javax.swing.JToggleButton();
        jButtonCambiarImagen = new javax.swing.JButton();
        jScrollPaneDescripcionChat = new javax.swing.JScrollPane();
        jTextAreaDescripcionChat = new javax.swing.JTextArea();
        jLabelDescripcion = new javax.swing.JLabel();
        jToggleButtonEdiatrDescripcion = new javax.swing.JToggleButton();
        jLabelFechaCreacion = new javax.swing.JLabel();
        jLabelFotoChat = new javax.swing.JLabel();
        jScrollPaneChatsCenter = new javax.swing.JScrollPane();
        jPanelChatCenter = new javax.swing.JPanel();

        setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1085, 630));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1085, 630));

        jPanelChatTop.setMinimumSize(new java.awt.Dimension(1085, 70));
        jPanelChatTop.setPreferredSize(new java.awt.Dimension(1085, 70));

        jLabelBack.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabelBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBack.setText("←");
        jLabelBack.setMaximumSize(new java.awt.Dimension(58, 58));
        jLabelBack.setMinimumSize(new java.awt.Dimension(58, 58));
        jLabelBack.setPreferredSize(new java.awt.Dimension(58, 58));
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });

        jLabelChatName.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabelChatName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelChatName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/chat_1.png"))); // NOI18N
        jLabelChatName.setText("Nombre Del Chat O La Persona Con Quien Se Chatea");

        jLabelMoreInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMoreInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/info_1.png"))); // NOI18N
        jLabelMoreInfo.setMaximumSize(new java.awt.Dimension(58, 58));
        jLabelMoreInfo.setMinimumSize(new java.awt.Dimension(58, 58));
        jLabelMoreInfo.setPreferredSize(new java.awt.Dimension(58, 58));
        jLabelMoreInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMoreInfoMouseClicked(evt);
            }
        });

        jLabelPersonasConQuienSeChatea.setFont(new java.awt.Font("Gadugi", 2, 14)); // NOI18N
        jLabelPersonasConQuienSeChatea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPersonasConQuienSeChatea.setText("Nombre De La Persona O Personas Con Quien Se Chatea");

        javax.swing.GroupLayout jPanelChatTopLayout = new javax.swing.GroupLayout(jPanelChatTop);
        jPanelChatTop.setLayout(jPanelChatTopLayout);
        jPanelChatTopLayout.setHorizontalGroup(
            jPanelChatTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChatTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelChatTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelChatName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPersonasConQuienSeChatea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMoreInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelChatTopLayout.setVerticalGroup(
            jPanelChatTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChatTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChatTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMoreInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelChatTopLayout.createSequentialGroup()
                        .addGroup(jPanelChatTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelChatTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPersonasConQuienSeChatea))
                            .addComponent(jLabelChatName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelChatBottom.setMinimumSize(new java.awt.Dimension(1085, 70));
        jPanelChatBottom.setPreferredSize(new java.awt.Dimension(1085, 70));

        jLabelAttachFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/attachment.png"))); // NOI18N
        jLabelAttachFile.setToolTipText("Attach File");
        jLabelAttachFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAttachFileMouseClicked(evt);
            }
        });

        jScrollPaneMessage.setMinimumSize(new java.awt.Dimension(530, 32));
        jScrollPaneMessage.setPreferredSize(new java.awt.Dimension(530, 32));

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jTextAreaMessage.setRows(1);
        jTextAreaMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaMessageKeyPressed(evt);
            }
        });
        jScrollPaneMessage.setViewportView(jTextAreaMessage);

        jLabelSendMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/send.png"))); // NOI18N
        jLabelSendMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSendMessageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelChatBottomLayout = new javax.swing.GroupLayout(jPanelChatBottom);
        jPanelChatBottom.setLayout(jPanelChatBottomLayout);
        jPanelChatBottomLayout.setHorizontalGroup(
            jPanelChatBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChatBottomLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelAttachFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSendMessage)
                .addContainerGap())
        );
        jPanelChatBottomLayout.setVerticalGroup(
            jPanelChatBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChatBottomLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelChatBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAttachFile)
                    .addComponent(jScrollPaneMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSendMessage)))
        );

        jTabbedPaneChatInfo.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jTabbedPaneChatInfo.setMaximumSize(new java.awt.Dimension(360, 3200));
        jTabbedPaneChatInfo.setMinimumSize(new java.awt.Dimension(360, 409));
        jTabbedPaneChatInfo.setPreferredSize(new java.awt.Dimension(360, 409));

        jPanelAllFilesSend.setOpaque(false);

        javax.swing.GroupLayout jPanelAllFilesSendLayout = new javax.swing.GroupLayout(jPanelAllFilesSend);
        jPanelAllFilesSend.setLayout(jPanelAllFilesSendLayout);
        jPanelAllFilesSendLayout.setHorizontalGroup(
            jPanelAllFilesSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanelAllFilesSendLayout.setVerticalGroup(
            jPanelAllFilesSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jTabbedPaneChatInfo.addTab("Archivos", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/file.png")), jPanelAllFilesSend); // NOI18N

        jPanelMembers.setOpaque(false);

        javax.swing.GroupLayout jPanelMembersLayout = new javax.swing.GroupLayout(jPanelMembers);
        jPanelMembers.setLayout(jPanelMembersLayout);
        jPanelMembersLayout.setHorizontalGroup(
            jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanelMembersLayout.setVerticalGroup(
            jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jTabbedPaneChatInfo.addTab("Miembros", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/group-meeting.png")), jPanelMembers); // NOI18N

        jPanelMoreInformationChat.setOpaque(false);

        Nombre.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        Nombre.setText("Nombre");

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N

        jToggleButtonEditarNombre.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jToggleButtonEditarNombre.setText("Editar?");

        jButtonCambiarImagen.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButtonCambiarImagen.setText("Cambiar Imagen");
        jButtonCambiarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambiarImagenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCambiarImagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCambiarImagenMouseExited(evt);
            }
        });

        jTextAreaDescripcionChat.setEditable(false);
        jTextAreaDescripcionChat.setColumns(20);
        jTextAreaDescripcionChat.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jTextAreaDescripcionChat.setRows(5);
        jScrollPaneDescripcionChat.setViewportView(jTextAreaDescripcionChat);

        jLabelDescripcion.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabelDescripcion.setText("Descripción");

        jToggleButtonEdiatrDescripcion.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jToggleButtonEdiatrDescripcion.setText("Editar?");

        javax.swing.GroupLayout jPanelMoreInformationChatLayout = new javax.swing.GroupLayout(jPanelMoreInformationChat);
        jPanelMoreInformationChat.setLayout(jPanelMoreInformationChatLayout);
        jPanelMoreInformationChatLayout.setHorizontalGroup(
            jPanelMoreInformationChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoreInformationChatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMoreInformationChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre)
                    .addGroup(jPanelMoreInformationChatLayout.createSequentialGroup()
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonEditarNombre))
                    .addComponent(jButtonCambiarImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDescripcionChat, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(jPanelMoreInformationChatLayout.createSequentialGroup()
                        .addComponent(jLabelDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonEdiatrDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelMoreInformationChatLayout.setVerticalGroup(
            jPanelMoreInformationChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoreInformationChatLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelMoreInformationChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonEditarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMoreInformationChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescripcion)
                    .addComponent(jToggleButtonEdiatrDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDescripcionChat, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCambiarImagen)
                .addGap(18, 18, 18))
        );

        jTabbedPaneChatInfo.addTab("Información", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/group.png")), jPanelMoreInformationChat); // NOI18N

        jLabelFechaCreacion.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabelFechaCreacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFechaCreacion.setText("Creado El 15/10/2021 A Las 12:30 P.M");
        jLabelFechaCreacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelFotoChat.setMaximumSize(new java.awt.Dimension(360, 168));
        jLabelFotoChat.setMinimumSize(new java.awt.Dimension(360, 168));
        jLabelFotoChat.setPreferredSize(new java.awt.Dimension(360, 168));

        javax.swing.GroupLayout jPanelChatInformationLayout = new javax.swing.GroupLayout(jPanelChatInformation);
        jPanelChatInformation.setLayout(jPanelChatInformationLayout);
        jPanelChatInformationLayout.setHorizontalGroup(
            jPanelChatInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChatInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChatInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFotoChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFechaCreacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelChatInformationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTabbedPaneChatInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelChatInformationLayout.setVerticalGroup(
            jPanelChatInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChatInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFotoChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneChatInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaCreacion)
                .addGap(10, 10, 10))
        );

        jScrollPaneChatsCenter.setOpaque(false);

        jPanelChatCenter.setOpaque(false);
        jPanelChatCenter.setLayout(new javax.swing.BoxLayout(jPanelChatCenter, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPaneChatsCenter.setViewportView(jPanelChatCenter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelChatTop, javax.swing.GroupLayout.PREFERRED_SIZE, 715, Short.MAX_VALUE)
                    .addComponent(jScrollPaneChatsCenter, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelChatBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 715, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanelChatInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelChatTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneChatsCenter)
                .addGap(0, 0, 0)
                .addComponent(jPanelChatBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelChatInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        // TODO add your handling code here:
        DashboardPanel.showView("chatsPanel");
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jLabelMoreInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMoreInfoMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            jPanelChatInformation.setVisible(!jPanelChatInformation.isVisible());
        }
    }//GEN-LAST:event_jLabelMoreInfoMouseClicked

    private void jButtonCambiarImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambiarImagenMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
        }
    }//GEN-LAST:event_jButtonCambiarImagenMouseClicked

    private void jButtonCambiarImagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambiarImagenMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCambiarImagenMouseEntered

    private void jButtonCambiarImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambiarImagenMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCambiarImagenMouseExited

    private void jLabelSendMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSendMessageMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            String text = jTextAreaMessage.getText();
            if(!text.isEmpty() && !text.isBlank()){
                Faker faker = new Faker(new Locale("es","MX"));
                String sender = faker.dune().character();
                String date = faker.backToTheFuture().date();
                TextMessagePanel textMessagePanel = new TextMessagePanel(sender,text,date);
                jPanelChatCenter.add(textMessagePanel);
                
                jTextAreaMessage.setText("");
            }
        }
    }//GEN-LAST:event_jLabelSendMessageMouseClicked

    private void jLabelAttachFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAttachFileMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
        }
    }//GEN-LAST:event_jLabelAttachFileMouseClicked

    private void jTextAreaMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaMessageKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String text = jTextAreaMessage.getText();
            if(!text.isEmpty() && !text.isBlank()){
                Faker faker = new Faker(new Locale("es","MX"));
                String sender = faker.dune().character();
                String date = faker.backToTheFuture().date();
                TextMessagePanel textMessagePanel = new TextMessagePanel(sender,text,date);
               
                jPanelChatCenter.add(textMessagePanel);
                    
                jTextAreaMessage.setText("");
            }
        }
    }//GEN-LAST:event_jTextAreaMessageKeyPressed

     @Override
    public void setColors(Image image){
        
        try {
            Random colorRandom = new Random(System.currentTimeMillis());
            int maximum = 0;
            
            PairDoublyLinkedList<Integer, Color> colorList = new PairDoublyLinkedList<>();
            PixelGrabber pg = new PixelGrabber(image, 0, 0, -1, -1, false);
            int large = (image.getWidth(null)/3);
            if (pg.grabPixels()) {
                int[] pixels = (int[]) pg.getPixels();
                for(int i = 0; i < pixels.length; i++){
                    int pixel = pixels[i];
                    int  red = (pixel  & 0x00ff0000) >> 16;
                    int  green = (pixel & 0x0000ff00) >> 8;
                    int  blue = pixel & 0x000000ff;
                    Color color = new Color(red,green,blue);
                    Pair<Integer, Color> pair = colorList.get_from_second(color);
            
                    if (pair != null) {//exist
                        int number = pair.first()+ 1;
                        pair.first(number);
                        if (number > maximum) {
                            firstColor = color;
                            maximum = number;
                        }
                    } else {
                        colorList.push_back(1, color);
                    }

                    color = null;
                    i += colorRandom.nextInt(large+1) + large;
                }

                secondColor = firstColor;
            
                int iterations = 0;
                if(colorList.size() > 1){
                    
                    while(Math.abs(secondColor.getRGB() - firstColor.getRGB()) < 3000000){
                        int position = colorRandom.nextInt((int)colorList.size()-1);
                        secondColor = colorList.get(position).second();
                        iterations++;
                        if(iterations > 25){
                             while(firstColor.getRGB() == secondColor.getRGB()){
                                position = colorRandom.nextInt((int)colorList.size()-1);
                                secondColor = colorList.get(position).second();
                            }
                             break;
                        }
                    }
                }
              
                int red = firstColor.getRed();
                Color fontColor = (red >= 155) ? Color.BLACK : Color.WHITE;
                red = secondColor.getRed();
                Color secondFontColor = (red >= 155) ? Color.BLACK : Color.WHITE;

                colorList.clear();

                Component[] components = this.getComponents();
                for (Component component : components){
                    component.setForeground(fontColor);
                }
                
                jLabelBack.setForeground(fontColor);
                jLabelChatName.setForeground(fontColor);
                jLabelPersonasConQuienSeChatea.setForeground(fontColor);
                jTextAreaMessage.setBackground(secondColor);
                jTextAreaMessage.setForeground(secondFontColor);
                jTabbedPaneChatInfo.setBackground(secondColor);
                jTabbedPaneChatInfo.setForeground(secondFontColor);
                jLabelFechaCreacion.setForeground(secondFontColor);
                jLabelDescripcion.setForeground(fontColor);
                jLabelChatName.setForeground(fontColor);
                jButtonCambiarImagen.setBackground(firstColor);
                jButtonCambiarImagen.setForeground(fontColor);
                jToggleButtonEdiatrDescripcion.setBackground(secondColor);
                jToggleButtonEdiatrDescripcion.setForeground(secondFontColor);
                jToggleButtonEditarNombre.setBackground(secondColor);
                jToggleButtonEditarNombre.setForeground(secondFontColor);
                jTextAreaDescripcionChat.setBackground(secondColor);
                jTextAreaDescripcionChat.setForeground(secondFontColor);
                jTextFieldNombre.setBackground(secondColor);
                jTextFieldNombre.setForeground(secondFontColor);
                jScrollPaneChatsCenter.setForeground(fontColor);

                
                colorRandom = null;
                colorList = null;
                pg = null;
                fontColor = secondFontColor = null;
                pixels = null;
            }
            
        } catch (InterruptedException ex) {
            Logger.getLogger(MusicPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 
  
    @Override
    public void dispose(){
        chatImage.flush();
        chatImage = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton jButtonCambiarImagen;
    private javax.swing.JLabel jLabelAttachFile;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelChatName;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelFechaCreacion;
    private javax.swing.JLabel jLabelFotoChat;
    private javax.swing.JLabel jLabelMoreInfo;
    private javax.swing.JLabel jLabelPersonasConQuienSeChatea;
    private javax.swing.JLabel jLabelSendMessage;
    private javax.swing.JPanel jPanelAllFilesSend;
    private javax.swing.JPanel jPanelChatBottom;
    private javax.swing.JPanel jPanelChatCenter;
    private javax.swing.JPanel jPanelChatInformation;
    private javax.swing.JPanel jPanelChatTop;
    private javax.swing.JPanel jPanelMembers;
    private javax.swing.JPanel jPanelMoreInformationChat;
    private javax.swing.JScrollPane jScrollPaneChatsCenter;
    private javax.swing.JScrollPane jScrollPaneDescripcionChat;
    private javax.swing.JScrollPane jScrollPaneMessage;
    private javax.swing.JTabbedPane jTabbedPaneChatInfo;
    private javax.swing.JTextArea jTextAreaDescripcionChat;
    private javax.swing.JTextArea jTextAreaMessage;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JToggleButton jToggleButtonEdiatrDescripcion;
    private javax.swing.JToggleButton jToggleButtonEditarNombre;
    // End of variables declaration//GEN-END:variables
}
