/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import com.github.javafaker.Faker;
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DateTimePicker;
import components.ImageFilePreview;
import data.interfaces.DisposeInterface;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author LENOVO
 */
public class GroupingPanel extends javax.swing.JPanel implements DisposeInterface{
    
    private GroupChatingPanel groupChatingPanel;
    private DateTimePicker dateTimePicker;
    private Color firstColor, secondColor,thirdColor,fontColor, secondFontColor, thirdFontColor;
    
   
    public GroupingPanel(Image image, String name, Color _firstColor, Color _secondColor, Color _thirdColor, Color _fontColor, Color _secondFontColor,Color _thirdFontColor ) {
        initComponents();
        firstColor = _firstColor;
        secondColor = _secondColor;
        fontColor = _fontColor;
        secondFontColor = _secondFontColor;
        thirdColor = _thirdColor;
        thirdFontColor = _thirdFontColor;
        Image groupImage = image.getScaledInstance(440,440,Image.SCALE_SMOOTH);
        jLabelGroupName.setText(name);
        initMyComponents(groupImage);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneGrouping = new javax.swing.JTabbedPane();
        jPanelAboutGroup = new javax.swing.JPanel();
        jLabelGroupImage = new javax.swing.JLabel();
        jLabelGroupName = new javax.swing.JLabel();
        jScrollPaneMembers = new javax.swing.JScrollPane();
        jPanelMembers = new javax.swing.JPanel();
        jLabelGroupClass = new javax.swing.JLabel();
        jLabelFechaCreacion = new javax.swing.JLabel();
        jLabelMiembros = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jPanelGrupalChat = new javax.swing.JPanel();
        jPanelArchivos = new javax.swing.JPanel();
        jScrollPaneArchivosCompartidos = new javax.swing.JScrollPane();
        jPanelArchivosCompartidos = new javax.swing.JPanel();
        jButtonCompartirArchivo = new javax.swing.JButton();
        jComboBoxOrdenarArchivosCompartidos = new javax.swing.JComboBox<>();
        jLabelOrdenarPor = new javax.swing.JLabel();
        jPanelPorHacer = new javax.swing.JPanel();
        jScrollPaneListaTareasPendientes = new javax.swing.JScrollPane();
        jPanelListaDeTareasPendientes = new javax.swing.JPanel();
        jLabelNombreTareaPendiente = new javax.swing.JLabel();
        jComboBoxMiembros = new javax.swing.JComboBox<>();
        jLabelMiembroACargo = new javax.swing.JLabel();
        jTextFieldNombreTareaPendiente = new javax.swing.JTextField();
        jLabelFechaFinalizacion = new javax.swing.JLabel();
        jScrollPaneDescripcionTareaPendiente = new javax.swing.JScrollPane();
        jTextAreaDescripcionTareaPendiente = new javax.swing.JTextArea();
        jLabelDescripcion = new javax.swing.JLabel();
        jPanelFechaFinalizacion = new javax.swing.JPanel();
        jLabelListaTareasPendientes = new javax.swing.JLabel();
        jButtonAgregarTareaPendiente = new javax.swing.JButton();
        jPanelConfiguraciones = new javax.swing.JPanel();
        jButtonEditGroupImage = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1085, 630));
        setOpaque(false);
        setLayout(new java.awt.CardLayout());

        jTabbedPaneGrouping.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N

        jLabelGroupImage.setPreferredSize(new java.awt.Dimension(440, 440));

        jLabelGroupName.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        jLabelGroupName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGroupName.setText("Group Name");
        jLabelGroupName.setMaximumSize(new java.awt.Dimension(416, 84));
        jLabelGroupName.setMinimumSize(new java.awt.Dimension(416, 84));
        jLabelGroupName.setOpaque(true);
        jLabelGroupName.setPreferredSize(new java.awt.Dimension(416, 84));

        jScrollPaneMembers.setBorder(null);
        jScrollPaneMembers.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneMembers.setOpaque(false);

        jPanelMembers.setOpaque(false);
        jPanelMembers.setLayout(new javax.swing.BoxLayout(jPanelMembers, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPaneMembers.setViewportView(jPanelMembers);

        jLabelGroupClass.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabelGroupClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGroupClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/teacher.png"))); // NOI18N
        jLabelGroupClass.setText("De La Clase Sistemas Operativos");
        jLabelGroupClass.setOpaque(true);
        jLabelGroupClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGroupClassMouseClicked(evt);
            }
        });

        jLabelFechaCreacion.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabelFechaCreacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFechaCreacion.setText("Creado El 22 De Octubre De 2021");

        jLabelMiembros.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        jLabelMiembros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMiembros.setText("Miembros");
        jLabelMiembros.setMaximumSize(new java.awt.Dimension(416, 84));
        jLabelMiembros.setMinimumSize(new java.awt.Dimension(416, 84));
        jLabelMiembros.setOpaque(true);
        jLabelMiembros.setPreferredSize(new java.awt.Dimension(416, 84));

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/reply.png"))); // NOI18N
        jButtonRegresar.setBorder(null);
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelAboutGroupLayout = new javax.swing.GroupLayout(jPanelAboutGroup);
        jPanelAboutGroup.setLayout(jPanelAboutGroupLayout);
        jPanelAboutGroupLayout.setHorizontalGroup(
            jPanelAboutGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutGroupLayout.createSequentialGroup()
                .addGroup(jPanelAboutGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAboutGroupLayout.createSequentialGroup()
                        .addGroup(jPanelAboutGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAboutGroupLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonRegresar))
                            .addGroup(jPanelAboutGroupLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelAboutGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelGroupName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                                    .addComponent(jLabelGroupClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAboutGroupLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelGroupImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jPanelAboutGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneMembers)
                    .addComponent(jLabelFechaCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAboutGroupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanelAboutGroupLayout.setVerticalGroup(
            jPanelAboutGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutGroupLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanelAboutGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGroupName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAboutGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAboutGroupLayout.createSequentialGroup()
                        .addComponent(jLabelGroupImage, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelGroupClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jButtonRegresar))
                    .addGroup(jPanelAboutGroupLayout.createSequentialGroup()
                        .addComponent(jScrollPaneMembers)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFechaCreacion)))
                .addContainerGap())
        );

        jTabbedPaneGrouping.addTab("Información", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/information.png")), jPanelAboutGroup); // NOI18N

        jPanelGrupalChat.setLayout(new java.awt.CardLayout());
        jTabbedPaneGrouping.addTab("Chat Grupal", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/group_3.png")), jPanelGrupalChat); // NOI18N

        jScrollPaneArchivosCompartidos.setBorder(null);
        jScrollPaneArchivosCompartidos.setOpaque(false);

        jPanelArchivosCompartidos.setOpaque(false);
        jPanelArchivosCompartidos.setLayout(new javax.swing.BoxLayout(jPanelArchivosCompartidos, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPaneArchivosCompartidos.setViewportView(jPanelArchivosCompartidos);

        jButtonCompartirArchivo.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButtonCompartirArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/submit.png"))); // NOI18N
        jButtonCompartirArchivo.setText("Compartir Archivo");
        jButtonCompartirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCompartirArchivoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCompartirArchivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCompartirArchivoMouseExited(evt);
            }
        });

        jComboBoxOrdenarArchivosCompartidos.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jComboBoxOrdenarArchivosCompartidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Tipo", "Fecha", "Miembro" }));

        jLabelOrdenarPor.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabelOrdenarPor.setText("Ordenar Por");

        javax.swing.GroupLayout jPanelArchivosLayout = new javax.swing.GroupLayout(jPanelArchivos);
        jPanelArchivos.setLayout(jPanelArchivosLayout);
        jPanelArchivosLayout.setHorizontalGroup(
            jPanelArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArchivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneArchivosCompartidos)
                    .addGroup(jPanelArchivosLayout.createSequentialGroup()
                        .addComponent(jLabelOrdenarPor)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxOrdenarArchivosCompartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 650, Short.MAX_VALUE)
                        .addComponent(jButtonCompartirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelArchivosLayout.setVerticalGroup(
            jPanelArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArchivosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCompartirArchivo)
                    .addComponent(jComboBoxOrdenarArchivosCompartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrdenarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneArchivosCompartidos, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneGrouping.addTab("Archivos", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/file-upload.png")), jPanelArchivos); // NOI18N

        jScrollPaneListaTareasPendientes.setBorder(null);
        jScrollPaneListaTareasPendientes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneListaTareasPendientes.setOpaque(false);

        jPanelListaDeTareasPendientes.setOpaque(false);
        jPanelListaDeTareasPendientes.setLayout(new javax.swing.BoxLayout(jPanelListaDeTareasPendientes, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPaneListaTareasPendientes.setViewportView(jPanelListaDeTareasPendientes);

        jLabelNombreTareaPendiente.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabelNombreTareaPendiente.setText("Nombre Del Pendiente");

        jComboBoxMiembros.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N

        jLabelMiembroACargo.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabelMiembroACargo.setText("Miembro A Cargo");

        jTextFieldNombreTareaPendiente.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N

        jLabelFechaFinalizacion.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabelFechaFinalizacion.setText("Fecha De Finalización");

        jTextAreaDescripcionTareaPendiente.setColumns(20);
        jTextAreaDescripcionTareaPendiente.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jTextAreaDescripcionTareaPendiente.setRows(5);
        jScrollPaneDescripcionTareaPendiente.setViewportView(jTextAreaDescripcionTareaPendiente);

        jLabelDescripcion.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabelDescripcion.setText("Descripción");

        jPanelFechaFinalizacion.setOpaque(false);
        jPanelFechaFinalizacion.setLayout(new java.awt.CardLayout());

        jLabelListaTareasPendientes.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        jLabelListaTareasPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaTareasPendientes.setText("Lista De Tareas Pendientes");
        jLabelListaTareasPendientes.setMaximumSize(new java.awt.Dimension(416, 84));
        jLabelListaTareasPendientes.setMinimumSize(new java.awt.Dimension(416, 84));
        jLabelListaTareasPendientes.setOpaque(true);
        jLabelListaTareasPendientes.setPreferredSize(new java.awt.Dimension(416, 84));

        jButtonAgregarTareaPendiente.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButtonAgregarTareaPendiente.setText("Agregar Tarea Pendiente");
        jButtonAgregarTareaPendiente.setActionCommand("Agregar Pendiente");
        jButtonAgregarTareaPendiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarTareaPendienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelPorHacerLayout = new javax.swing.GroupLayout(jPanelPorHacer);
        jPanelPorHacer.setLayout(jPanelPorHacerLayout);
        jPanelPorHacerLayout.setHorizontalGroup(
            jPanelPorHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorHacerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPorHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPorHacerLayout.createSequentialGroup()
                        .addGap(0, 180, Short.MAX_VALUE)
                        .addComponent(jLabelListaTareasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 180, Short.MAX_VALUE))
                    .addComponent(jScrollPaneListaTareasPendientes))
                .addGap(18, 18, 18)
                .addGroup(jPanelPorHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelFechaFinalizacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFechaFinalizacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDescripcionTareaPendiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addComponent(jLabelDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombreTareaPendiente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombreTareaPendiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxMiembros, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMiembroACargo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgregarTareaPendiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPorHacerLayout.setVerticalGroup(
            jPanelPorHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPorHacerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPorHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPorHacerLayout.createSequentialGroup()
                        .addComponent(jLabelListaTareasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneListaTareasPendientes))
                    .addGroup(jPanelPorHacerLayout.createSequentialGroup()
                        .addComponent(jLabelMiembroACargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNombreTareaPendiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombreTareaPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneDescripcionTareaPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFechaFinalizacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelFechaFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(jButtonAgregarTareaPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPaneGrouping.addTab("Pendientes", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/daily-tasks.png")), jPanelPorHacer); // NOI18N

        jButtonEditGroupImage.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        jButtonEditGroupImage.setText("Cambiar Imagen");
        jButtonEditGroupImage.setToolTipText("<html>Click Para Cargar Tu Foto De Perfil Desde Tu Ordenador.<br><b>NOTA: LA IMAGEN DE PERFIL TENDRÁ UNA RESOLUCIÓN DE 250x250 px.</b></html>");
        jButtonEditGroupImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEditGroupImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditGroupImage.setMaximumSize(new java.awt.Dimension(400, 40));
        jButtonEditGroupImage.setMinimumSize(new java.awt.Dimension(400, 40));
        jButtonEditGroupImage.setPreferredSize(new java.awt.Dimension(400, 40));
        jButtonEditGroupImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditGroupImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEditGroupImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditGroupImageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelConfiguracionesLayout = new javax.swing.GroupLayout(jPanelConfiguraciones);
        jPanelConfiguraciones.setLayout(jPanelConfiguracionesLayout);
        jPanelConfiguracionesLayout.setHorizontalGroup(
            jPanelConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConfiguracionesLayout.createSequentialGroup()
                .addGap(829, 829, 829)
                .addComponent(jButtonEditGroupImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelConfiguracionesLayout.setVerticalGroup(
            jPanelConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfiguracionesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButtonEditGroupImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
        );

        jTabbedPaneGrouping.addTab("Configuraciones", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/edit-tool.png")), jPanelConfiguraciones); // NOI18N

        add(jTabbedPaneGrouping, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditGroupImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditGroupImageMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setAccessory(new ImageFilePreview(fileChooser));
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos De Imagenes", "png", "jpg", "jpeg", "bmp");
            fileChooser.addChoosableFileFilter(filter);
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setAcceptAllFileFilterUsed(true);
            fileChooser.setApproveButtonText("Cargar Imagen");
            int result = fileChooser.showOpenDialog(this);

            if (result == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();

                try {
                    Image openImage = ImageIO.read(file);
                    int large = jLabelGroupImage.getHeight();
                    ImageIcon autenticacionIcon = new ImageIcon(openImage.getScaledInstance(large,large,Image.SCALE_SMOOTH));

                    jLabelGroupImage.setIcon(autenticacionIcon);

                    DashboardPanel.setUserImage(autenticacionIcon.getImage());

                    openImage = null;
                    autenticacionIcon = null;

                } catch (IOException ex) {
                    Logger.getLogger(EditProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            fileChooser = null;
        }
    }//GEN-LAST:event_jButtonEditGroupImageMouseClicked

    private void jButtonEditGroupImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditGroupImageMouseEntered
        // TODO add your handling code here:
        jButtonEditGroupImage.setBackground(secondColor);
        jButtonEditGroupImage.setForeground(secondFontColor);
    }//GEN-LAST:event_jButtonEditGroupImageMouseEntered

    private void jButtonEditGroupImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditGroupImageMouseExited
        // TODO add your handling code here:
        jButtonEditGroupImage.setBackground(thirdColor);
        jButtonEditGroupImage.setForeground(thirdFontColor);
    }//GEN-LAST:event_jButtonEditGroupImageMouseExited

    private void jLabelGroupClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGroupClassMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
        }
    }//GEN-LAST:event_jLabelGroupClassMouseClicked

    private void jButtonAgregarTareaPendienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarTareaPendienteMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
            MemberPanel memberPanel = (MemberPanel)jPanelMembers.getComponent(jComboBoxMiembros.getSelectedIndex());
            String todo_name = jTextFieldNombreTareaPendiente.getText();
            String todo_description = jTextAreaDescripcionTareaPendiente.getText();
            String todo_datetime = dateTimePicker.getDatePicker().getDateStringOrEmptyString() + " - " +dateTimePicker.getTimePicker().getTimeStringOrEmptyString();
            
            if(!todo_name.isEmpty() && !todo_name.isBlank() && 
                    !todo_description.isEmpty() && !todo_description.isBlank() &&
                    !todo_datetime.isEmpty() && !todo_datetime.isBlank()){
                ToDoPanel toDoPanel = new ToDoPanel(memberPanel.getImageIcon(),memberPanel.getFirstColor(),memberPanel.getFontColor(),
                        memberPanel.getSecondColor(),memberPanel.getSecondFontColor(),
                todo_name,todo_description,todo_datetime,memberPanel.getFullName());

                jPanelListaDeTareasPendientes.add(toDoPanel);
            }
            
        }
    }//GEN-LAST:event_jButtonAgregarTareaPendienteMouseClicked

    private void jButtonCompartirArchivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCompartirArchivoMouseExited
        // TODO add your handling code here:
        jButtonCompartirArchivo.setBackground(thirdColor);
        jButtonCompartirArchivo.setForeground(thirdFontColor);
    }//GEN-LAST:event_jButtonCompartirArchivoMouseExited

    private void jButtonCompartirArchivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCompartirArchivoMouseEntered
        // TODO add your handling code here:
        jButtonCompartirArchivo.setBackground(secondColor);
        jButtonCompartirArchivo.setForeground(secondFontColor);
        
    }//GEN-LAST:event_jButtonCompartirArchivoMouseEntered

    private void jButtonCompartirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCompartirArchivoMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            attachFile();
        }
    }//GEN-LAST:event_jButtonCompartirArchivoMouseClicked

    private void jButtonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            DashboardPanel.showView("groupsPanel");
        }
    }//GEN-LAST:event_jButtonRegresarMouseClicked

    private void jButtonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseEntered
        // TODO add your handling code here:
        jButtonRegresar.setBackground(secondColor);
    }//GEN-LAST:event_jButtonRegresarMouseEntered

    private void jButtonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseExited
        // TODO add your handling code here:
        jButtonRegresar.setBackground(thirdColor);
    }//GEN-LAST:event_jButtonRegresarMouseExited

    private void attachFile(){
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setApproveButtonText("Open File");
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.doLayout();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if(file != null){

                Faker faker = new Faker(new Locale("es","MX"));
                
                Date date = faker.date().birthday();
                GroupSharedFilePanel groupSharedFilePanel = new GroupSharedFilePanel(file.getName(),"Nombre Del Usuario",date.toString(),secondColor,secondFontColor,thirdColor,thirdFontColor,fontColor);
                
                jPanelArchivosCompartidos.add(groupSharedFilePanel);

            }
        }
    
    }
    
    public void initMyComponents(Image groupImage){
        ImageIcon groupIcon = new ImageIcon(groupImage);
        
        jLabelGroupImage.setIcon(groupIcon);
        groupImage.flush();
        groupImage = null;
        groupIcon = null;
        
        groupChatingPanel = new GroupChatingPanel(firstColor,secondColor, secondFontColor);
        jPanelGrupalChat.add(groupChatingPanel);
       
        jScrollPaneMembers.getViewport().setOpaque(false);
        jScrollPaneMembers.getVerticalScrollBar().setUnitIncrement(15);
        
        jScrollPaneListaTareasPendientes.getViewport().setOpaque(false);
        jScrollPaneListaTareasPendientes.getVerticalScrollBar().setUnitIncrement(15);
        
        jScrollPaneArchivosCompartidos.getViewport().setOpaque(false);
        jScrollPaneArchivosCompartidos.getVerticalScrollBar().setUnitIncrement(15);
        
        jTabbedPaneGrouping.setBackground(firstColor);
        jTabbedPaneGrouping.setForeground(fontColor);
        
        groupIcon = null;
        
        Faker faker = new Faker();
        for(int i = 0; i < faker.number().numberBetween(1, 10);i++){
            MemberPanel memberPanel = new MemberPanel();
            jComboBoxMiembros.addItem(memberPanel.getFullName());
            jPanelMembers.add(memberPanel);
        }
        
        jComboBoxMiembros.setSelectedIndex(0);
        jScrollPaneDescripcionTareaPendiente.getViewport().setOpaque(false);
        
        Component[] components = this.getComponents();
        for (Component component : components){
            component.setForeground(fontColor);
        }

        jLabelGroupName.setBackground(secondColor);
        jLabelGroupName.setForeground(secondFontColor);

        jLabelMiembros.setBackground(secondColor);
        jLabelMiembros.setForeground(secondFontColor);

        jButtonEditGroupImage.setBackground(thirdColor);
        jButtonEditGroupImage.setForeground(thirdFontColor);

        jLabelGroupClass.setBackground(thirdColor);
        jLabelGroupClass.setForeground(thirdFontColor);
        
        jLabelFechaCreacion.setForeground(fontColor);

        jButtonAgregarTareaPendiente.setForeground(thirdFontColor);
        jButtonAgregarTareaPendiente.setBackground(thirdColor);
        
        jButtonCompartirArchivo.setForeground(thirdFontColor);
        jButtonCompartirArchivo.setBackground(thirdColor);
        
        jLabelOrdenarPor.setForeground(fontColor);
        
        jComboBoxOrdenarArchivosCompartidos.setForeground(thirdFontColor);
        jComboBoxOrdenarArchivosCompartidos.setBackground(thirdColor);
        
        jLabelMiembroACargo.setForeground(fontColor);
        jLabelNombreTareaPendiente.setForeground(fontColor);
        
        jLabelDescripcion.setForeground(fontColor);
        jLabelFechaFinalizacion.setForeground(fontColor);
        
        jLabelListaTareasPendientes.setForeground(thirdFontColor);
        jLabelListaTareasPendientes.setBackground(thirdColor);

        jComboBoxMiembros.setForeground(thirdFontColor);
        jComboBoxMiembros.setBackground(thirdColor);

        jTextFieldNombreTareaPendiente.setForeground(thirdFontColor);
        jTextFieldNombreTareaPendiente.setCaretColor(thirdFontColor);
        jTextFieldNombreTareaPendiente.setBackground(thirdColor);

        jTextAreaDescripcionTareaPendiente.setForeground(thirdFontColor);
        jTextAreaDescripcionTareaPendiente.setCaretColor(thirdFontColor);
        jTextAreaDescripcionTareaPendiente.setBackground(thirdColor);

        jPanelFechaFinalizacion.setBackground(thirdColor);
        jPanelFechaFinalizacion.setForeground(thirdFontColor);
        
        dateTimePicker = new DateTimePicker();
        dateTimePicker.setFont(jTextFieldNombreTareaPendiente.getFont());
        dateTimePicker.setForeground(thirdColor);
        jPanelFechaFinalizacion.add(dateTimePicker);
        jPanelAboutGroup.setBackground(firstColor);
        jPanelFechaFinalizacion.setBorder(jTextFieldNombreTareaPendiente.getBorder());
        jPanelGrupalChat.setBackground(firstColor);
        jPanelPorHacer.setBackground(firstColor);
        jPanelConfiguraciones.setBackground(firstColor);
        jPanelArchivos.setBackground(firstColor);
    }
 
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarTareaPendiente;
    private javax.swing.JButton jButtonCompartirArchivo;
    private javax.swing.JButton jButtonEditGroupImage;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxMiembros;
    private javax.swing.JComboBox<String> jComboBoxOrdenarArchivosCompartidos;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelFechaCreacion;
    private javax.swing.JLabel jLabelFechaFinalizacion;
    private javax.swing.JLabel jLabelGroupClass;
    private javax.swing.JLabel jLabelGroupImage;
    private javax.swing.JLabel jLabelGroupName;
    private javax.swing.JLabel jLabelListaTareasPendientes;
    private javax.swing.JLabel jLabelMiembroACargo;
    private javax.swing.JLabel jLabelMiembros;
    private javax.swing.JLabel jLabelNombreTareaPendiente;
    private javax.swing.JLabel jLabelOrdenarPor;
    private javax.swing.JPanel jPanelAboutGroup;
    private javax.swing.JPanel jPanelArchivos;
    private javax.swing.JPanel jPanelArchivosCompartidos;
    private javax.swing.JPanel jPanelConfiguraciones;
    private javax.swing.JPanel jPanelFechaFinalizacion;
    private javax.swing.JPanel jPanelGrupalChat;
    private javax.swing.JPanel jPanelListaDeTareasPendientes;
    private javax.swing.JPanel jPanelMembers;
    private javax.swing.JPanel jPanelPorHacer;
    private javax.swing.JScrollPane jScrollPaneArchivosCompartidos;
    private javax.swing.JScrollPane jScrollPaneDescripcionTareaPendiente;
    private javax.swing.JScrollPane jScrollPaneListaTareasPendientes;
    private javax.swing.JScrollPane jScrollPaneMembers;
    private javax.swing.JTabbedPane jTabbedPaneGrouping;
    private javax.swing.JTextArea jTextAreaDescripcionTareaPendiente;
    private javax.swing.JTextField jTextFieldNombreTareaPendiente;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dispose() {
        groupChatingPanel.dispose();
    }
}
