/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author LENOVO
 */
public class ImageMessagePanel extends javax.swing.JPanel {

    /**
     * Creates new form ImageMessagePanel
     */
    public ImageMessagePanel(String sender, String date, Image image, String filename) {
        initComponents();
        jLabelDate.setText(date);
        jLabelSender.setText(sender);
        jLabelImageName.setText(filename);
        jLabelDate.setForeground(DashboardPanel.getSecondFontColor());
        jLabelSender.setForeground(DashboardPanel.getSecondFontColor());
        jLabelImageName.setForeground(DashboardPanel.getSecondFontColor());
        this.setBackground(DashboardPanel.getSecondColor());
        Image resizedImage = image.getScaledInstance(789, 500, Image.SCALE_AREA_AVERAGING);
        ImageIcon icon = new ImageIcon(resizedImage);
        jLabelImageMessage.setIcon(icon);
        resizedImage.flush();
        resizedImage = null;
        icon = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSender = new javax.swing.JLabel();
        jLabelImageMessage = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelImageName = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelSender.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabelSender.setText("Sender");

        jLabelImageMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageMessage.setMaximumSize(new java.awt.Dimension(789, 500));
        jLabelImageMessage.setMinimumSize(new java.awt.Dimension(789, 500));
        jLabelImageMessage.setPreferredSize(new java.awt.Dimension(789, 500));

        jLabelDate.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDate.setText("Date");

        jLabelImageName.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabelImageName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageName.setText("Image Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelSender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImageMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelImageName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelSender)
                .addGap(9, 9, 9)
                .addComponent(jLabelImageName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImageMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelImageMessage;
    private javax.swing.JLabel jLabelImageName;
    private javax.swing.JLabel jLabelSender;
    // End of variables declaration//GEN-END:variables
}
