/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import com.github.javafaker.Faker;
import java.awt.Image;
import java.io.IOException;
import java.util.Locale;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author LENOVO
 */
public class MemberPanel extends javax.swing.JPanel {

    /**
     * Creates new form MemberPanel
     */
    public MemberPanel() {
        initComponents();
        Random colorRandom = new Random(System.currentTimeMillis());
        String imageName = "/resources/images/image"+(colorRandom.nextInt(15)+1)+".jpg";
        try {
            Image image = ImageIO.read(getClass().getResource(imageName));
            Image cover = image.getScaledInstance(88, 88, Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(cover);
            jLabelMemberPhoto.setIcon(imageIcon);
            image.flush();
            cover.flush();
            image = null;
            cover = null;
            Faker faker = new Faker(new Locale("es","MX"));
            String nombre = faker.name().firstName() + " " +faker.name().firstName();
            String apellido = faker.name().lastName() + " " + faker.name().lastName();
            String username = faker.name().username();
            
            jLabelMemberLastName.setText(apellido);
            jLabelMemberName.setText(nombre);
            jLabelMemberUserName.setText(username);
            
            apellido = nombre = username = null;
            
            faker = null;
            
            this.setBackground(DashboardPanel.getFirstColor());
            jLabelMemberLastName.setForeground(DashboardPanel.getFontColor());
            jLabelMemberLastName.setForeground(DashboardPanel.getFontColor());
            jLabelMemberLastName.setForeground(DashboardPanel.getFontColor());
            
        } catch (IOException ex) {
            Logger.getLogger(MemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMemberPhoto = new javax.swing.JLabel();
        jLabelMemberName = new javax.swing.JLabel();
        jLabelMemberLastName = new javax.swing.JLabel();
        jLabelMemberUserName = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(360, 32767));
        setMinimumSize(new java.awt.Dimension(360, 100));
        setPreferredSize(new java.awt.Dimension(360, 100));

        jLabelMemberPhoto.setMaximumSize(new java.awt.Dimension(88, 88));
        jLabelMemberPhoto.setMinimumSize(new java.awt.Dimension(88, 88));
        jLabelMemberPhoto.setPreferredSize(new java.awt.Dimension(88, 88));

        jLabelMemberName.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabelMemberName.setText("Nombre Del Miembro");

        jLabelMemberLastName.setFont(new java.awt.Font("Gadugi", 2, 14)); // NOI18N
        jLabelMemberLastName.setText("Apellido Del Miembro");

        jLabelMemberUserName.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabelMemberUserName.setText("Nombre De Usuario Del Miembro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMemberPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMemberName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMemberLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMemberUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMemberName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMemberLastName)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMemberUserName))
                    .addComponent(jLabelMemberPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMemberLastName;
    private javax.swing.JLabel jLabelMemberName;
    private javax.swing.JLabel jLabelMemberPhoto;
    private javax.swing.JLabel jLabelMemberUserName;
    // End of variables declaration//GEN-END:variables
}
