/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template archivo, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.students;

import com.github.lgooddatepicker.components.DateTimePicker;
import components.ImageFilePreview;
import courseroom.MainFrame;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import panels.generals.Mensaje_Texto_General_Panel;
import panels.generals.Miembro_General_Panel;
import data.interfaces.Componentes_Interface;
import data.interfaces.Limpieza_Interface;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LENOVO
 */
public class Grupo_Estudiante_Panel extends javax.swing.JPanel implements Limpieza_Interface, Componentes_Interface{
    
    private DateTimePicker escogedor_Fecha_Hora;
    private Color primer_Color, segundo_Color,tercer_Color,primer_Color_Fuente, segundo_Color_Fuente, tercer_Color_Fuente;
    private JScrollPane lista_Tareas_Pendientes_JScrollPane, lista_Tareas_Finalizadas_JScrollPane;
    private JPanel lista_Tareas_Pendientes_JPanel, lista_Tareas_Finalizadas_JPanel;
   
    public Grupo_Estudiante_Panel(
            Image imagen_Grupo, 
            String nombre_Grupo, 
            Color _primer_Color, 
            Color _segundo_Color, 
            Color _tercer_Color, 
            Color _primer_Color_Fuente, 
            Color _segundo_Color_Fuente,
            Color _tercer_Color_Fuente ) {
        
        initComponents();
        
        primer_Color = _primer_Color;
        segundo_Color = _segundo_Color;
        primer_Color_Fuente = _primer_Color_Fuente;
        segundo_Color_Fuente = _segundo_Color_Fuente;
        tercer_Color = _tercer_Color;
        tercer_Color_Fuente = _tercer_Color_Fuente;
        
        Image groupImage = imagen_Grupo.getScaledInstance(440,440,Image.SCALE_SMOOTH);
        nombre_Grupo_JLabel.setText(nombre_Grupo);
        ImageIcon groupIcon = new ImageIcon(groupImage);
        
        imagen_Grupo_JLabel.setIcon(groupIcon);
        editar_Imagen_Grupo_JLabel.setIcon(groupIcon);
        groupImage.flush();
        
        Iniciar_Componentes();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_JTabbedPane = new javax.swing.JTabbedPane();
        informacion_Grupo_JPanel = new javax.swing.JPanel();
        imagen_Grupo_JLabel = new javax.swing.JLabel();
        nombre_Grupo_JLabel = new javax.swing.JLabel();
        miembros_JScrollPane = new javax.swing.JScrollPane();
        miembros_JPanel = new javax.swing.JPanel();
        curso_Grupo_JLabel = new javax.swing.JLabel();
        fecha_Creacion_JLabel = new javax.swing.JLabel();
        miembros_Titulo_JLabel = new javax.swing.JLabel();
        regresar_JButton = new javax.swing.JButton();
        chat_Grupal_JPanel = new javax.swing.JPanel();
        mensajes_Chat_JScrollPane = new javax.swing.JScrollPane();
        mensajes_Chat_JPanel = new javax.swing.JPanel();
        enviar_Mensajes_JPanel = new javax.swing.JPanel();
        enviar_Mensaje_JTextField = new javax.swing.JTextField();
        enviar_Mensaje_JButton = new javax.swing.JButton();
        compartir_Archivos_JPanel = new javax.swing.JPanel();
        archivos_Compartidos_JScrollPane = new javax.swing.JScrollPane();
        archivos_Compartidos_JPanel = new javax.swing.JPanel();
        compartir_Archivo_JButton = new javax.swing.JButton();
        ordenar_Archivos_Compatidos_JComboBox = new javax.swing.JComboBox<>();
        ordenar_Archivos_Compartidos_JLabel = new javax.swing.JLabel();
        crear_Tareas_Pendientes_JPanel = new javax.swing.JPanel();
        tareas_Pendientes_JLabel = new javax.swing.JLabel();
        anadir_Tarea_Pendiente_JPanel = new javax.swing.JPanel();
        tarea_Pendiente_JLabel = new javax.swing.JLabel();
        anadir_Tarea_Pendiente_JButton = new javax.swing.JButton();
        fecha_Finalizacion_Tarea_Pendiente_JLabel = new javax.swing.JLabel();
        descripcion_Tarea_Pendiente_JLabel = new javax.swing.JLabel();
        miembro_Cargo_Tarea_Pendiente_JComboBox = new javax.swing.JComboBox<>();
        fecha_Finalizacion_Tarea_Pendiente_JPanel = new javax.swing.JPanel();
        nombre_Tarea_Pendiente_JTextField = new javax.swing.JTextField();
        descripcion_Tarea_Pendiente_JScrollPane = new javax.swing.JScrollPane();
        descripcion_Tarea_Pendiente_JTextArea = new javax.swing.JTextArea();
        miembro_Cargo_Tarea_Pendiente_JLabel = new javax.swing.JLabel();
        mostrar_Tarea_Pendiente_Tipo_JComboBox = new javax.swing.JComboBox<>();
        tareas_Pendientes_JPanel = new javax.swing.JPanel();
        configuraciones_JPanel = new javax.swing.JPanel();
        editar_Imagen_Grupo_JButton = new javax.swing.JButton();
        editar_Nombre_Grupo_JTextField = new javax.swing.JTextField();
        editar_Nombre_Grupo_JLabel = new javax.swing.JLabel();
        editar_Imagen_Grupo_JLabel = new javax.swing.JLabel();
        eliminar_Miembro_JLabel = new javax.swing.JLabel();
        eliminar_Miembro_JComboBox = new javax.swing.JComboBox<>();
        editar_Nombre_Grupo_JButton = new javax.swing.JButton();
        eliminar_Miembro_JButton = new javax.swing.JButton();
        abandonar_Grupo_JButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1085, 630));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1085, 680));
        setLayout(new java.awt.CardLayout());

        grupo_JTabbedPane.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N

        informacion_Grupo_JPanel.setToolTipText("");

        imagen_Grupo_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen_Grupo_JLabel.setToolTipText("Imagen Del Grupo");
        imagen_Grupo_JLabel.setPreferredSize(new java.awt.Dimension(440, 440));

        nombre_Grupo_JLabel.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        nombre_Grupo_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_Grupo_JLabel.setText("Group Name");
        nombre_Grupo_JLabel.setToolTipText("Nombre Del Grupo");
        nombre_Grupo_JLabel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        nombre_Grupo_JLabel.setMinimumSize(new java.awt.Dimension(0, 0));
        nombre_Grupo_JLabel.setOpaque(true);
        nombre_Grupo_JLabel.setPreferredSize(new java.awt.Dimension(416, 84));

        miembros_JScrollPane.setBorder(null);
        miembros_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        miembros_JScrollPane.setOpaque(false);

        miembros_JPanel.setToolTipText("Miembros Del Grupo");
        miembros_JPanel.setOpaque(false);
        miembros_JPanel.setLayout(new javax.swing.BoxLayout(miembros_JPanel, javax.swing.BoxLayout.PAGE_AXIS));
        miembros_JScrollPane.setViewportView(miembros_JPanel);

        curso_Grupo_JLabel.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        curso_Grupo_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curso_Grupo_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/teacher.png"))); // NOI18N
        curso_Grupo_JLabel.setText("Del Curso Sistemas Operativos");
        curso_Grupo_JLabel.setToolTipText("Curso De Proveniencia Del Grupo");
        curso_Grupo_JLabel.setOpaque(true);
        curso_Grupo_JLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                curso_Grupo_JLabelMouseClicked(evt);
            }
        });

        fecha_Creacion_JLabel.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        fecha_Creacion_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_Creacion_JLabel.setText("Creado El 22 De Octubre De 2021");
        fecha_Creacion_JLabel.setToolTipText("Fecha De Creación Del Grupo");

        miembros_Titulo_JLabel.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        miembros_Titulo_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        miembros_Titulo_JLabel.setText("Miembros");
        miembros_Titulo_JLabel.setMaximumSize(new java.awt.Dimension(416, 84));
        miembros_Titulo_JLabel.setMinimumSize(new java.awt.Dimension(416, 84));
        miembros_Titulo_JLabel.setOpaque(true);
        miembros_Titulo_JLabel.setPreferredSize(new java.awt.Dimension(416, 84));

        regresar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/reply.png"))); // NOI18N
        regresar_JButton.setToolTipText("Regresar A Mis Grupos");
        regresar_JButton.setBorder(null);
        regresar_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout informacion_Grupo_JPanelLayout = new javax.swing.GroupLayout(informacion_Grupo_JPanel);
        informacion_Grupo_JPanel.setLayout(informacion_Grupo_JPanelLayout);
        informacion_Grupo_JPanelLayout.setHorizontalGroup(
            informacion_Grupo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion_Grupo_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacion_Grupo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacion_Grupo_JPanelLayout.createSequentialGroup()
                        .addComponent(regresar_JButton)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(fecha_Creacion_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informacion_Grupo_JPanelLayout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(informacion_Grupo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre_Grupo_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curso_Grupo_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                            .addComponent(imagen_Grupo_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 39, Short.MAX_VALUE)
                        .addGroup(informacion_Grupo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(miembros_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(miembros_Titulo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        informacion_Grupo_JPanelLayout.setVerticalGroup(
            informacion_Grupo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion_Grupo_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacion_Grupo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacion_Grupo_JPanelLayout.createSequentialGroup()
                        .addComponent(miembros_Titulo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(miembros_JScrollPane)
                        .addGap(19, 19, 19)
                        .addComponent(fecha_Creacion_JLabel))
                    .addGroup(informacion_Grupo_JPanelLayout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(nombre_Grupo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagen_Grupo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(curso_Grupo_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 19, Short.MAX_VALUE)
                        .addComponent(regresar_JButton)))
                .addContainerGap())
        );

        grupo_JTabbedPane.addTab("Información", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/information.png")), informacion_Grupo_JPanel); // NOI18N

        mensajes_Chat_JScrollPane.setOpaque(false);

        mensajes_Chat_JPanel.setOpaque(false);
        mensajes_Chat_JPanel.setLayout(new javax.swing.BoxLayout(mensajes_Chat_JPanel, javax.swing.BoxLayout.Y_AXIS));
        mensajes_Chat_JScrollPane.setViewportView(mensajes_Chat_JPanel);

        enviar_Mensajes_JPanel.setMinimumSize(new java.awt.Dimension(1085, 70));

        enviar_Mensaje_JTextField.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        enviar_Mensaje_JTextField.setToolTipText("Redactar Mensaje");
        enviar_Mensaje_JTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enviar_Mensaje_JTextFieldKeyPressed(evt);
            }
        });

        enviar_Mensaje_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/send.png"))); // NOI18N
        enviar_Mensaje_JButton.setToolTipText("Enviar Mensaje");
        enviar_Mensaje_JButton.setBorder(null);
        enviar_Mensaje_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar_Mensaje_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar_Mensaje_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enviar_Mensaje_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enviar_Mensaje_JButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout enviar_Mensajes_JPanelLayout = new javax.swing.GroupLayout(enviar_Mensajes_JPanel);
        enviar_Mensajes_JPanel.setLayout(enviar_Mensajes_JPanelLayout);
        enviar_Mensajes_JPanelLayout.setHorizontalGroup(
            enviar_Mensajes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enviar_Mensajes_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enviar_Mensaje_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviar_Mensaje_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        enviar_Mensajes_JPanelLayout.setVerticalGroup(
            enviar_Mensajes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enviar_Mensajes_JPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(enviar_Mensajes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enviar_Mensaje_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enviar_Mensaje_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chat_Grupal_JPanelLayout = new javax.swing.GroupLayout(chat_Grupal_JPanel);
        chat_Grupal_JPanel.setLayout(chat_Grupal_JPanelLayout);
        chat_Grupal_JPanelLayout.setHorizontalGroup(
            chat_Grupal_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mensajes_Chat_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
            .addComponent(enviar_Mensajes_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        chat_Grupal_JPanelLayout.setVerticalGroup(
            chat_Grupal_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_Grupal_JPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mensajes_Chat_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(enviar_Mensajes_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        grupo_JTabbedPane.addTab("Chat Grupal", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/group_3.png")), chat_Grupal_JPanel); // NOI18N

        archivos_Compartidos_JScrollPane.setBorder(null);
        archivos_Compartidos_JScrollPane.setOpaque(false);

        archivos_Compartidos_JPanel.setOpaque(false);
        archivos_Compartidos_JPanel.setLayout(new javax.swing.BoxLayout(archivos_Compartidos_JPanel, javax.swing.BoxLayout.PAGE_AXIS));
        archivos_Compartidos_JScrollPane.setViewportView(archivos_Compartidos_JPanel);

        compartir_Archivo_JButton.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        compartir_Archivo_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/submit.png"))); // NOI18N
        compartir_Archivo_JButton.setText("Compartir Archivo");
        compartir_Archivo_JButton.setToolTipText("Compartir Y Subir Archivo");
        compartir_Archivo_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compartir_Archivo_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compartir_Archivo_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compartir_Archivo_JButtonMouseExited(evt);
            }
        });

        ordenar_Archivos_Compatidos_JComboBox.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        ordenar_Archivos_Compatidos_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Tipo", "Fecha", "Miembro" }));
        ordenar_Archivos_Compatidos_JComboBox.setToolTipText("Ordenar Archivos Compartidos Por");

        ordenar_Archivos_Compartidos_JLabel.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        ordenar_Archivos_Compartidos_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordenar_Archivos_Compartidos_JLabel.setText("Ordenar Por");

        javax.swing.GroupLayout compartir_Archivos_JPanelLayout = new javax.swing.GroupLayout(compartir_Archivos_JPanel);
        compartir_Archivos_JPanel.setLayout(compartir_Archivos_JPanelLayout);
        compartir_Archivos_JPanelLayout.setHorizontalGroup(
            compartir_Archivos_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compartir_Archivos_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(compartir_Archivos_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(archivos_Compartidos_JScrollPane)
                    .addGroup(compartir_Archivos_JPanelLayout.createSequentialGroup()
                        .addComponent(ordenar_Archivos_Compartidos_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordenar_Archivos_Compatidos_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 566, Short.MAX_VALUE)
                        .addComponent(compartir_Archivo_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        compartir_Archivos_JPanelLayout.setVerticalGroup(
            compartir_Archivos_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compartir_Archivos_JPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(compartir_Archivos_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compartir_Archivo_JButton)
                    .addComponent(ordenar_Archivos_Compatidos_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordenar_Archivos_Compartidos_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(archivos_Compartidos_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );

        grupo_JTabbedPane.addTab("Archivos", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/file-upload.png")), compartir_Archivos_JPanel); // NOI18N

        tareas_Pendientes_JLabel.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        tareas_Pendientes_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tareas_Pendientes_JLabel.setText("Lista De Tareas Pendientes");
        tareas_Pendientes_JLabel.setMaximumSize(new java.awt.Dimension(416, 84));
        tareas_Pendientes_JLabel.setMinimumSize(new java.awt.Dimension(416, 84));
        tareas_Pendientes_JLabel.setOpaque(true);
        tareas_Pendientes_JLabel.setPreferredSize(new java.awt.Dimension(416, 84));

        anadir_Tarea_Pendiente_JPanel.setOpaque(false);

        tarea_Pendiente_JLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        tarea_Pendiente_JLabel.setText("Nombre Del Pendiente");

        anadir_Tarea_Pendiente_JButton.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        anadir_Tarea_Pendiente_JButton.setText("Agregar Tarea Pendiente");
        anadir_Tarea_Pendiente_JButton.setToolTipText("Agregar Nueva Tarea Pendiente");
        anadir_Tarea_Pendiente_JButton.setActionCommand("Agregar Pendiente");
        anadir_Tarea_Pendiente_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anadir_Tarea_Pendiente_JButtonMouseClicked(evt);
            }
        });

        fecha_Finalizacion_Tarea_Pendiente_JLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        fecha_Finalizacion_Tarea_Pendiente_JLabel.setText("Fecha De Finalización");

        descripcion_Tarea_Pendiente_JLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        descripcion_Tarea_Pendiente_JLabel.setText("Descripción");

        miembro_Cargo_Tarea_Pendiente_JComboBox.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        miembro_Cargo_Tarea_Pendiente_JComboBox.setToolTipText("Seleccionar El Miembro A Cargo De La Tarea Pendiente");

        fecha_Finalizacion_Tarea_Pendiente_JPanel.setToolTipText("Fecha Posible De Terminación De La Tarea Pendiente");
        fecha_Finalizacion_Tarea_Pendiente_JPanel.setOpaque(false);
        fecha_Finalizacion_Tarea_Pendiente_JPanel.setLayout(new java.awt.CardLayout());

        nombre_Tarea_Pendiente_JTextField.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        nombre_Tarea_Pendiente_JTextField.setToolTipText("Nombre De La Tarea Pendiente");

        descripcion_Tarea_Pendiente_JTextArea.setColumns(20);
        descripcion_Tarea_Pendiente_JTextArea.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        descripcion_Tarea_Pendiente_JTextArea.setRows(5);
        descripcion_Tarea_Pendiente_JTextArea.setToolTipText("Ingresa Aquí La Descripción De La Tarea Pendiente");
        descripcion_Tarea_Pendiente_JScrollPane.setViewportView(descripcion_Tarea_Pendiente_JTextArea);

        miembro_Cargo_Tarea_Pendiente_JLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        miembro_Cargo_Tarea_Pendiente_JLabel.setText("Miembro A Cargo");

        javax.swing.GroupLayout anadir_Tarea_Pendiente_JPanelLayout = new javax.swing.GroupLayout(anadir_Tarea_Pendiente_JPanel);
        anadir_Tarea_Pendiente_JPanel.setLayout(anadir_Tarea_Pendiente_JPanelLayout);
        anadir_Tarea_Pendiente_JPanelLayout.setHorizontalGroup(
            anadir_Tarea_Pendiente_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anadir_Tarea_Pendiente_JPanelLayout.createSequentialGroup()
                .addGroup(anadir_Tarea_Pendiente_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre_Tarea_Pendiente_JTextField)
                    .addComponent(tarea_Pendiente_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(miembro_Cargo_Tarea_Pendiente_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(miembro_Cargo_Tarea_Pendiente_JComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descripcion_Tarea_Pendiente_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descripcion_Tarea_Pendiente_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addComponent(fecha_Finalizacion_Tarea_Pendiente_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fecha_Finalizacion_Tarea_Pendiente_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anadir_Tarea_Pendiente_JButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        anadir_Tarea_Pendiente_JPanelLayout.setVerticalGroup(
            anadir_Tarea_Pendiente_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anadir_Tarea_Pendiente_JPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(miembro_Cargo_Tarea_Pendiente_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miembro_Cargo_Tarea_Pendiente_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tarea_Pendiente_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre_Tarea_Pendiente_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descripcion_Tarea_Pendiente_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion_Tarea_Pendiente_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fecha_Finalizacion_Tarea_Pendiente_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha_Finalizacion_Tarea_Pendiente_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anadir_Tarea_Pendiente_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mostrar_Tarea_Pendiente_Tipo_JComboBox.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        mostrar_Tarea_Pendiente_Tipo_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendientes", "Finalizadas" }));
        mostrar_Tarea_Pendiente_Tipo_JComboBox.setToolTipText("Mostrar Lista De Tareas Pendientes O Finalizadas");
        mostrar_Tarea_Pendiente_Tipo_JComboBox.setBorder(null);
        mostrar_Tarea_Pendiente_Tipo_JComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mostrar_Tarea_Pendiente_Tipo_JComboBoxItemStateChanged(evt);
            }
        });

        tareas_Pendientes_JPanel.setOpaque(false);
        tareas_Pendientes_JPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout crear_Tareas_Pendientes_JPanelLayout = new javax.swing.GroupLayout(crear_Tareas_Pendientes_JPanel);
        crear_Tareas_Pendientes_JPanel.setLayout(crear_Tareas_Pendientes_JPanelLayout);
        crear_Tareas_Pendientes_JPanelLayout.setHorizontalGroup(
            crear_Tareas_Pendientes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_Tareas_Pendientes_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anadir_Tarea_Pendiente_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_Tareas_Pendientes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_Tareas_Pendientes_JPanelLayout.createSequentialGroup()
                        .addComponent(tareas_Pendientes_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(mostrar_Tarea_Pendiente_Tipo_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tareas_Pendientes_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        crear_Tareas_Pendientes_JPanelLayout.setVerticalGroup(
            crear_Tareas_Pendientes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_Tareas_Pendientes_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crear_Tareas_Pendientes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_Tareas_Pendientes_JPanelLayout.createSequentialGroup()
                        .addGroup(crear_Tareas_Pendientes_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tareas_Pendientes_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostrar_Tarea_Pendiente_Tipo_JComboBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tareas_Pendientes_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(crear_Tareas_Pendientes_JPanelLayout.createSequentialGroup()
                        .addGap(0, 77, Short.MAX_VALUE)
                        .addComponent(anadir_Tarea_Pendiente_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );

        grupo_JTabbedPane.addTab("Pendientes", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/daily-tasks.png")), crear_Tareas_Pendientes_JPanel); // NOI18N

        editar_Imagen_Grupo_JButton.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        editar_Imagen_Grupo_JButton.setText("Cambiar Imagen");
        editar_Imagen_Grupo_JButton.setToolTipText("Cambiar Imagen Del Grupo");
        editar_Imagen_Grupo_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editar_Imagen_Grupo_JButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editar_Imagen_Grupo_JButton.setMaximumSize(new java.awt.Dimension(400, 40));
        editar_Imagen_Grupo_JButton.setMinimumSize(new java.awt.Dimension(400, 40));
        editar_Imagen_Grupo_JButton.setPreferredSize(new java.awt.Dimension(400, 40));
        editar_Imagen_Grupo_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editar_Imagen_Grupo_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editar_Imagen_Grupo_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editar_Imagen_Grupo_JButtonMouseExited(evt);
            }
        });

        editar_Nombre_Grupo_JTextField.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        editar_Nombre_Grupo_JTextField.setText("Nombre Del Grupo");

        editar_Nombre_Grupo_JLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        editar_Nombre_Grupo_JLabel.setText("Nombre Del Grupo");

        editar_Imagen_Grupo_JLabel.setToolTipText("Imagen Del Grupo A Editar");
        editar_Imagen_Grupo_JLabel.setMaximumSize(new java.awt.Dimension(440, 440));
        editar_Imagen_Grupo_JLabel.setMinimumSize(new java.awt.Dimension(440, 440));
        editar_Imagen_Grupo_JLabel.setPreferredSize(new java.awt.Dimension(440, 440));

        eliminar_Miembro_JLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        eliminar_Miembro_JLabel.setText("Eliminar Miembro");

        eliminar_Miembro_JComboBox.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        eliminar_Miembro_JComboBox.setToolTipText("Seleccionar Miembro A Eliminar");

        editar_Nombre_Grupo_JButton.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        editar_Nombre_Grupo_JButton.setText("Editar");
        editar_Nombre_Grupo_JButton.setToolTipText("Editar Nombre Del Grupo");
        editar_Nombre_Grupo_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editar_Nombre_Grupo_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editar_Nombre_Grupo_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editar_Nombre_Grupo_JButtonMouseExited(evt);
            }
        });

        eliminar_Miembro_JButton.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        eliminar_Miembro_JButton.setText("Eliminar");
        eliminar_Miembro_JButton.setToolTipText("Eliminar Miembro Del Grupo");
        eliminar_Miembro_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar_Miembro_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminar_Miembro_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminar_Miembro_JButtonMouseExited(evt);
            }
        });

        abandonar_Grupo_JButton.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        abandonar_Grupo_JButton.setText("Abandonar Grupo");
        abandonar_Grupo_JButton.setToolTipText("Abandona Y Elimina El Grupo De Los Tuyos");
        abandonar_Grupo_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abandonar_Grupo_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abandonar_Grupo_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abandonar_Grupo_JButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout configuraciones_JPanelLayout = new javax.swing.GroupLayout(configuraciones_JPanel);
        configuraciones_JPanel.setLayout(configuraciones_JPanelLayout);
        configuraciones_JPanelLayout.setHorizontalGroup(
            configuraciones_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configuraciones_JPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(configuraciones_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configuraciones_JPanelLayout.createSequentialGroup()
                        .addGroup(configuraciones_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(configuraciones_JPanelLayout.createSequentialGroup()
                                .addComponent(eliminar_Miembro_JComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(configuraciones_JPanelLayout.createSequentialGroup()
                                .addComponent(editar_Nombre_Grupo_JTextField)
                                .addGap(6, 6, 6)))
                        .addGroup(configuraciones_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editar_Nombre_Grupo_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar_Miembro_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(abandonar_Grupo_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(editar_Nombre_Grupo_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminar_Miembro_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(configuraciones_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editar_Imagen_Grupo_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editar_Imagen_Grupo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        configuraciones_JPanelLayout.setVerticalGroup(
            configuraciones_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configuraciones_JPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(configuraciones_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editar_Imagen_Grupo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(configuraciones_JPanelLayout.createSequentialGroup()
                        .addComponent(editar_Nombre_Grupo_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configuraciones_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editar_Nombre_Grupo_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editar_Nombre_Grupo_JTextField))
                        .addGap(18, 18, 18)
                        .addComponent(eliminar_Miembro_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(configuraciones_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eliminar_Miembro_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar_Miembro_JComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(configuraciones_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editar_Imagen_Grupo_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abandonar_Grupo_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grupo_JTabbedPane.addTab("Configuraciones", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/edit-tool.png")), configuraciones_JPanel); // NOI18N

        add(grupo_JTabbedPane, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void editar_Imagen_Grupo_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar_Imagen_Grupo_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){

            JFileChooser escogedor_Archivo = new JFileChooser();
            escogedor_Archivo.setAccessory(new ImageFilePreview(escogedor_Archivo));
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos De Imagenes", "png", "jpg", "jpeg", "bmp");
            escogedor_Archivo.addChoosableFileFilter(filtro);
            escogedor_Archivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
            escogedor_Archivo.setAcceptAllFileFilterUsed(true);
            escogedor_Archivo.setApproveButtonText("Cargar Imagen");
            int resultado = escogedor_Archivo.showOpenDialog(this);

            if (resultado == JFileChooser.APPROVE_OPTION) {
                File archivo = escogedor_Archivo.getSelectedFile();

                try {
                    Image abrir_Imagen = ImageIO.read(archivo);
                    int largo_Imagen = editar_Imagen_Grupo_JLabel.getHeight();
                    ImageIcon autenticacionIcon = new ImageIcon(abrir_Imagen.getScaledInstance(largo_Imagen,largo_Imagen,Image.SCALE_SMOOTH));

                    editar_Imagen_Grupo_JLabel.setIcon(autenticacionIcon);

                    Student_Dashboard_Panel.setUserImage(autenticacionIcon.getImage());
                    abrir_Imagen.flush();

                } catch (IOException ex) {
                    MainFrame.getLogger().log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_editar_Imagen_Grupo_JButtonMouseClicked

    private void editar_Imagen_Grupo_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar_Imagen_Grupo_JButtonMouseEntered
        // TODO add your handling code here:
        editar_Imagen_Grupo_JButton.setBackground(segundo_Color);
        editar_Imagen_Grupo_JButton.setForeground(segundo_Color_Fuente);
    }//GEN-LAST:event_editar_Imagen_Grupo_JButtonMouseEntered

    private void editar_Imagen_Grupo_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar_Imagen_Grupo_JButtonMouseExited
        // TODO add your handling code here:
        editar_Imagen_Grupo_JButton.setBackground(tercer_Color);
        editar_Imagen_Grupo_JButton.setForeground(tercer_Color_Fuente);
    }//GEN-LAST:event_editar_Imagen_Grupo_JButtonMouseExited

    private void curso_Grupo_JLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curso_Grupo_JLabelMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
        }
    }//GEN-LAST:event_curso_Grupo_JLabelMouseClicked

    private void anadir_Tarea_Pendiente_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anadir_Tarea_Pendiente_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
            Miembro_General_Panel miembro_General_Panel = 
                    (Miembro_General_Panel)miembros_JPanel.getComponent(
                            miembro_Cargo_Tarea_Pendiente_JComboBox.getSelectedIndex());
            
            String tarea_Pendiente_nombre = nombre_Tarea_Pendiente_JTextField.getText();
            String tarea_Pendiente_descricion = descripcion_Tarea_Pendiente_JTextArea.getText();
            String tarea_Pendiente_fecha = 
                    MainFrame.Concatenar(escogedor_Fecha_Hora.getDatePicker().getDateStringOrEmptyString()," - ",escogedor_Fecha_Hora.getTimePicker().getTimeStringOrEmptyString());
            
            if(!tarea_Pendiente_nombre.isEmpty() && !tarea_Pendiente_nombre.isBlank() && 
                    !tarea_Pendiente_descricion.isEmpty() && !tarea_Pendiente_descricion.isBlank() &&
                    !tarea_Pendiente_fecha.isEmpty() && !tarea_Pendiente_fecha.isBlank()){
                Tarea_Pendiente_Estudiante_Panel toDoPanel = new Tarea_Pendiente_Estudiante_Panel(miembro_General_Panel.Obtener_Icono_Imagen(),
                        miembro_General_Panel.Obtener_Primer_Color(),miembro_General_Panel.Obtener_Primer_Color_Fuente(),
                        miembro_General_Panel.Obtener_Segundo_Color(),miembro_General_Panel.Obtener_Segundo_Color_Fuente(),
                tarea_Pendiente_nombre,tarea_Pendiente_descricion,tarea_Pendiente_fecha,miembro_General_Panel.Obtener_Nombre_Completo());

                lista_Tareas_Pendientes_JPanel.add(toDoPanel);
            }
            
        }
    }//GEN-LAST:event_anadir_Tarea_Pendiente_JButtonMouseClicked

    private void compartir_Archivo_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compartir_Archivo_JButtonMouseExited
        // TODO add your handling code here:
        compartir_Archivo_JButton.setBackground(tercer_Color);
        compartir_Archivo_JButton.setForeground(tercer_Color_Fuente);
    }//GEN-LAST:event_compartir_Archivo_JButtonMouseExited

    private void compartir_Archivo_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compartir_Archivo_JButtonMouseEntered
        // TODO add your handling code here:
        compartir_Archivo_JButton.setBackground(segundo_Color);
        compartir_Archivo_JButton.setForeground(segundo_Color_Fuente);
        
    }//GEN-LAST:event_compartir_Archivo_JButtonMouseEntered

    private void compartir_Archivo_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compartir_Archivo_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Compartir_Archivo();
        }
    }//GEN-LAST:event_compartir_Archivo_JButtonMouseClicked

    private void regresar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Student_Dashboard_Panel.showView("Grupos");
        }
    }//GEN-LAST:event_regresar_JButtonMouseClicked

    private void regresar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseEntered
        // TODO add your handling code here:
        regresar_JButton.setBackground(segundo_Color);
    }//GEN-LAST:event_regresar_JButtonMouseEntered

    private void regresar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseExited
        // TODO add your handling code here:
        regresar_JButton.setBackground(tercer_Color);
    }//GEN-LAST:event_regresar_JButtonMouseExited

    private void editar_Nombre_Grupo_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar_Nombre_Grupo_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
        }
        
    }//GEN-LAST:event_editar_Nombre_Grupo_JButtonMouseClicked

    private void editar_Nombre_Grupo_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar_Nombre_Grupo_JButtonMouseEntered
        // TODO add your handling code here:
        editar_Nombre_Grupo_JButton.setBackground(segundo_Color);
        editar_Nombre_Grupo_JButton.setForeground(segundo_Color_Fuente);
    }//GEN-LAST:event_editar_Nombre_Grupo_JButtonMouseEntered

    private void editar_Nombre_Grupo_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar_Nombre_Grupo_JButtonMouseExited
        // TODO add your handling code here:
        editar_Nombre_Grupo_JButton.setBackground(tercer_Color);
        editar_Nombre_Grupo_JButton.setForeground(tercer_Color_Fuente);
    }//GEN-LAST:event_editar_Nombre_Grupo_JButtonMouseExited

    private void eliminar_Miembro_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_Miembro_JButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_Miembro_JButtonMouseClicked

    private void eliminar_Miembro_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_Miembro_JButtonMouseEntered
        // TODO add your handling code here:
        eliminar_Miembro_JButton.setBackground(segundo_Color);
        eliminar_Miembro_JButton.setForeground(segundo_Color_Fuente);
    }//GEN-LAST:event_eliminar_Miembro_JButtonMouseEntered

    private void eliminar_Miembro_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_Miembro_JButtonMouseExited
        // TODO add your handling code here:
        eliminar_Miembro_JButton.setBackground(tercer_Color);
        eliminar_Miembro_JButton.setForeground(tercer_Color_Fuente);
    }//GEN-LAST:event_eliminar_Miembro_JButtonMouseExited

    private void abandonar_Grupo_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abandonar_Grupo_JButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_abandonar_Grupo_JButtonMouseClicked

    private void abandonar_Grupo_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abandonar_Grupo_JButtonMouseEntered
        // TODO add your handling code here:
        abandonar_Grupo_JButton.setBackground(segundo_Color.darker());
        abandonar_Grupo_JButton.setForeground(segundo_Color_Fuente.brighter());
    }//GEN-LAST:event_abandonar_Grupo_JButtonMouseEntered

    private void abandonar_Grupo_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abandonar_Grupo_JButtonMouseExited
        // TODO add your handling code here:
        abandonar_Grupo_JButton.setBackground(tercer_Color.darker());
        abandonar_Grupo_JButton.setForeground(tercer_Color_Fuente.brighter());
    }//GEN-LAST:event_abandonar_Grupo_JButtonMouseExited

    private void enviar_Mensaje_JTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enviar_Mensaje_JTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Enviar_Mensaje();
        }
    }//GEN-LAST:event_enviar_Mensaje_JTextFieldKeyPressed

    private void enviar_Mensaje_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_Mensaje_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Enviar_Mensaje();
        }
    }//GEN-LAST:event_enviar_Mensaje_JButtonMouseClicked

    private void enviar_Mensaje_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_Mensaje_JButtonMouseEntered
        // TODO add your handling code here:
        enviar_Mensaje_JButton.setBackground(primer_Color);
    }//GEN-LAST:event_enviar_Mensaje_JButtonMouseEntered

    private void enviar_Mensaje_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_Mensaje_JButtonMouseExited
        // TODO add your handling code here:
        enviar_Mensaje_JButton.setBackground(segundo_Color);
    }//GEN-LAST:event_enviar_Mensaje_JButtonMouseExited

    private void mostrar_Tarea_Pendiente_Tipo_JComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mostrar_Tarea_Pendiente_Tipo_JComboBoxItemStateChanged
        // TODO add your handling code here:
        if(mostrar_Tarea_Pendiente_Tipo_JComboBox.getSelectedIndex() == 0){
            tareas_Pendientes_JLabel.setText("Lista De Tareas Pendientes");
            ((CardLayout) tareas_Pendientes_JPanel.getLayout()).show(tareas_Pendientes_JPanel, "Tareas_Pendientes");
            
        } 
        else{
            tareas_Pendientes_JLabel.setText("Lista De Tareas Finalizadas");
            ((CardLayout) tareas_Pendientes_JPanel.getLayout()).show(tareas_Pendientes_JPanel, "Tareas_Finalizadas");
        }
    }//GEN-LAST:event_mostrar_Tarea_Pendiente_Tipo_JComboBoxItemStateChanged

    private void Enviar_Mensaje(){
        String mensaje = enviar_Mensaje_JTextField.getText();
        if(!mensaje.isEmpty() && !mensaje.isBlank()){
            
            String emisor = MainFrame.getFaker().dune().character();
            String fecha = MainFrame.getFaker().backToTheFuture().date();
            Mensaje_Texto_General_Panel mensaje_Texto_General_Panel = new Mensaje_Texto_General_Panel(emisor,mensaje,fecha);
            mensaje_Texto_General_Panel.setMaximumSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width-400,200));
            mensajes_Chat_JPanel.add(mensaje_Texto_General_Panel);
            enviar_Mensaje_JTextField.setText("");
                    
        }
    }
    
    private void Compartir_Archivo(){
        JFileChooser escogedor_Archivo = new JFileChooser();
        escogedor_Archivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        escogedor_Archivo.setApproveButtonText("Compartir Archivo");
        escogedor_Archivo.setMultiSelectionEnabled(false);
        escogedor_Archivo.doLayout();
        int result = escogedor_Archivo.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File archivo = escogedor_Archivo.getSelectedFile();
            if(archivo != null){
                
                Date fecha = MainFrame.getFaker().date().birthday();
                Archivo_Compartido_Grupo_Estudiante_Panel archivo_Compartido_Grupo_Estudiante_Panel = 
                        new Archivo_Compartido_Grupo_Estudiante_Panel(archivo,"Nombre Del Usuario",
                        fecha.toString(),segundo_Color,segundo_Color_Fuente,tercer_Color,
                        tercer_Color_Fuente,primer_Color_Fuente);
                
                archivos_Compartidos_JPanel.add(archivo_Compartido_Grupo_Estudiante_Panel);

            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abandonar_Grupo_JButton;
    private javax.swing.JButton anadir_Tarea_Pendiente_JButton;
    private javax.swing.JPanel anadir_Tarea_Pendiente_JPanel;
    private javax.swing.JPanel archivos_Compartidos_JPanel;
    private javax.swing.JScrollPane archivos_Compartidos_JScrollPane;
    private javax.swing.JPanel chat_Grupal_JPanel;
    private javax.swing.JButton compartir_Archivo_JButton;
    private javax.swing.JPanel compartir_Archivos_JPanel;
    private javax.swing.JPanel configuraciones_JPanel;
    private javax.swing.JPanel crear_Tareas_Pendientes_JPanel;
    private javax.swing.JLabel curso_Grupo_JLabel;
    private javax.swing.JLabel descripcion_Tarea_Pendiente_JLabel;
    private javax.swing.JScrollPane descripcion_Tarea_Pendiente_JScrollPane;
    private javax.swing.JTextArea descripcion_Tarea_Pendiente_JTextArea;
    private javax.swing.JButton editar_Imagen_Grupo_JButton;
    private javax.swing.JLabel editar_Imagen_Grupo_JLabel;
    private javax.swing.JButton editar_Nombre_Grupo_JButton;
    private javax.swing.JLabel editar_Nombre_Grupo_JLabel;
    private javax.swing.JTextField editar_Nombre_Grupo_JTextField;
    private javax.swing.JButton eliminar_Miembro_JButton;
    private javax.swing.JComboBox<String> eliminar_Miembro_JComboBox;
    private javax.swing.JLabel eliminar_Miembro_JLabel;
    private javax.swing.JButton enviar_Mensaje_JButton;
    private javax.swing.JTextField enviar_Mensaje_JTextField;
    private javax.swing.JPanel enviar_Mensajes_JPanel;
    private javax.swing.JLabel fecha_Creacion_JLabel;
    private javax.swing.JLabel fecha_Finalizacion_Tarea_Pendiente_JLabel;
    private javax.swing.JPanel fecha_Finalizacion_Tarea_Pendiente_JPanel;
    private javax.swing.JTabbedPane grupo_JTabbedPane;
    private javax.swing.JLabel imagen_Grupo_JLabel;
    private javax.swing.JPanel informacion_Grupo_JPanel;
    private javax.swing.JPanel mensajes_Chat_JPanel;
    private javax.swing.JScrollPane mensajes_Chat_JScrollPane;
    private javax.swing.JComboBox<String> miembro_Cargo_Tarea_Pendiente_JComboBox;
    private javax.swing.JLabel miembro_Cargo_Tarea_Pendiente_JLabel;
    private javax.swing.JPanel miembros_JPanel;
    private javax.swing.JScrollPane miembros_JScrollPane;
    private javax.swing.JLabel miembros_Titulo_JLabel;
    private javax.swing.JComboBox<String> mostrar_Tarea_Pendiente_Tipo_JComboBox;
    private javax.swing.JLabel nombre_Grupo_JLabel;
    private javax.swing.JTextField nombre_Tarea_Pendiente_JTextField;
    private javax.swing.JLabel ordenar_Archivos_Compartidos_JLabel;
    private javax.swing.JComboBox<String> ordenar_Archivos_Compatidos_JComboBox;
    private javax.swing.JButton regresar_JButton;
    private javax.swing.JLabel tarea_Pendiente_JLabel;
    private javax.swing.JLabel tareas_Pendientes_JLabel;
    private javax.swing.JPanel tareas_Pendientes_JPanel;
    // End of variables declaration//GEN-END:variables

    

    @Override
    public void Iniciar_Componentes() {
        lista_Tareas_Finalizadas_JScrollPane = new JScrollPane();
        lista_Tareas_Pendientes_JScrollPane  = new JScrollPane();
        
        lista_Tareas_Finalizadas_JPanel = new JPanel();
        lista_Tareas_Pendientes_JPanel = new JPanel();
        
        lista_Tareas_Finalizadas_JScrollPane.setBorder(null);
        lista_Tareas_Finalizadas_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        lista_Tareas_Finalizadas_JScrollPane.setOpaque(false);
        
        lista_Tareas_Pendientes_JScrollPane.setBorder(null);
        lista_Tareas_Pendientes_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        lista_Tareas_Pendientes_JScrollPane.setOpaque(false);

        lista_Tareas_Finalizadas_JScrollPane.setViewportView(lista_Tareas_Finalizadas_JPanel);
        lista_Tareas_Finalizadas_JScrollPane.getViewport().setOpaque(false);
        lista_Tareas_Finalizadas_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        
        lista_Tareas_Pendientes_JScrollPane.setViewportView(lista_Tareas_Pendientes_JPanel);
        lista_Tareas_Pendientes_JScrollPane.getViewport().setOpaque(false);
        lista_Tareas_Pendientes_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        
        lista_Tareas_Finalizadas_JPanel.setOpaque(false);
        lista_Tareas_Finalizadas_JPanel.setLayout(new javax.swing.BoxLayout(lista_Tareas_Finalizadas_JPanel, javax.swing.BoxLayout.PAGE_AXIS));
        lista_Tareas_Finalizadas_JScrollPane.setViewportView(lista_Tareas_Finalizadas_JPanel);
        
        lista_Tareas_Pendientes_JPanel.setOpaque(false);
        lista_Tareas_Pendientes_JPanel.setLayout(new javax.swing.BoxLayout(lista_Tareas_Pendientes_JPanel, javax.swing.BoxLayout.PAGE_AXIS));
        lista_Tareas_Pendientes_JScrollPane.setViewportView(lista_Tareas_Pendientes_JPanel);
        
        tareas_Pendientes_JPanel.add(lista_Tareas_Finalizadas_JScrollPane, "Tareas_Finalizadas");
        tareas_Pendientes_JPanel.add(lista_Tareas_Pendientes_JScrollPane, "Tareas_Pendientes");
        ((CardLayout)tareas_Pendientes_JPanel.getLayout()).show(tareas_Pendientes_JPanel, "Tareas_Pendientes");
        
        anadir_Tarea_Pendiente_JPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(primer_Color_Fuente), "Agregar Pendiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 18),primer_Color_Fuente));
        
        imagen_Grupo_JLabel.setBorder(javax.swing.BorderFactory.createLineBorder(segundo_Color));
        editar_Imagen_Grupo_JLabel.setBorder(javax.swing.BorderFactory.createLineBorder(segundo_Color));
       
        miembros_JScrollPane.getViewport().setOpaque(false);
        miembros_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        
        archivos_Compartidos_JScrollPane.getViewport().setOpaque(false);
        archivos_Compartidos_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        
       
        Miembro_General_Panel memberPanel;
        for(int i = 0; i < MainFrame.getFaker().number().numberBetween(1, 10);i++){
            memberPanel = new Miembro_General_Panel();
            miembro_Cargo_Tarea_Pendiente_JComboBox.addItem(memberPanel.Obtener_Nombre_Completo());
            eliminar_Miembro_JComboBox.addItem(memberPanel.Obtener_Nombre_Completo());
            miembros_JPanel.add(memberPanel);
        }
        
        miembro_Cargo_Tarea_Pendiente_JComboBox.setSelectedIndex(0);
        descripcion_Tarea_Pendiente_JScrollPane.getViewport().setOpaque(false);
        
        mensajes_Chat_JScrollPane.getViewport().setOpaque(false);
        mensajes_Chat_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        
        escogedor_Fecha_Hora = new DateTimePicker();
        escogedor_Fecha_Hora.setFont(nombre_Tarea_Pendiente_JTextField.getFont());
        fecha_Finalizacion_Tarea_Pendiente_JPanel.add(escogedor_Fecha_Hora);
        fecha_Finalizacion_Tarea_Pendiente_JPanel.setBorder(nombre_Tarea_Pendiente_JTextField.getBorder());
        
        Colorear_Componentes();
        
    }
    
     
    @Override
    public void Colorear_Componentes(){
        
        grupo_JTabbedPane.setBackground(primer_Color);
        grupo_JTabbedPane.setForeground(primer_Color_Fuente);
        
        Component[] components = this.getComponents();
        for (Component component : components){
            component.setForeground(primer_Color_Fuente);
        }

        nombre_Grupo_JLabel.setBackground(segundo_Color);
        nombre_Grupo_JLabel.setForeground(segundo_Color_Fuente);

        miembros_Titulo_JLabel.setBackground(segundo_Color);
        miembros_Titulo_JLabel.setForeground(segundo_Color_Fuente);

        editar_Imagen_Grupo_JButton.setBackground(tercer_Color);
        editar_Imagen_Grupo_JButton.setForeground(tercer_Color_Fuente);
        
        abandonar_Grupo_JButton.setBackground(tercer_Color.darker());
        abandonar_Grupo_JButton.setForeground(tercer_Color_Fuente.brighter());

        curso_Grupo_JLabel.setBackground(tercer_Color);
        curso_Grupo_JLabel.setForeground(tercer_Color_Fuente);
        
        fecha_Creacion_JLabel.setForeground(primer_Color_Fuente);
        editar_Nombre_Grupo_JLabel.setForeground(primer_Color_Fuente);

        anadir_Tarea_Pendiente_JButton.setForeground(tercer_Color_Fuente);
        anadir_Tarea_Pendiente_JButton.setBackground(tercer_Color);
        
        compartir_Archivo_JButton.setForeground(tercer_Color_Fuente);
        compartir_Archivo_JButton.setBackground(tercer_Color);
        
        ordenar_Archivos_Compartidos_JLabel.setForeground(primer_Color_Fuente);
        eliminar_Miembro_JLabel.setForeground(primer_Color_Fuente);
        
        ordenar_Archivos_Compatidos_JComboBox.setForeground(tercer_Color_Fuente);
        ordenar_Archivos_Compatidos_JComboBox.setBackground(tercer_Color);
        
        mostrar_Tarea_Pendiente_Tipo_JComboBox.setForeground(tercer_Color_Fuente);
        mostrar_Tarea_Pendiente_Tipo_JComboBox.setBackground(tercer_Color);
        mostrar_Tarea_Pendiente_Tipo_JComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(segundo_Color), 
                "Mostrar Lista Por", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
                javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                new java.awt.Font("Gadugi", 1, 14),segundo_Color_Fuente)); // NOI18N
        
        miembro_Cargo_Tarea_Pendiente_JLabel.setForeground(primer_Color_Fuente);
        tarea_Pendiente_JLabel.setForeground(primer_Color_Fuente);
        
        descripcion_Tarea_Pendiente_JLabel.setForeground(primer_Color_Fuente);
        fecha_Finalizacion_Tarea_Pendiente_JLabel.setForeground(primer_Color_Fuente);
        
        tareas_Pendientes_JLabel.setForeground(tercer_Color_Fuente);
        tareas_Pendientes_JLabel.setBackground(tercer_Color);

        miembro_Cargo_Tarea_Pendiente_JComboBox.setForeground(tercer_Color_Fuente);
        miembro_Cargo_Tarea_Pendiente_JComboBox.setBackground(tercer_Color);
        
        eliminar_Miembro_JComboBox.setForeground(tercer_Color_Fuente);
        eliminar_Miembro_JComboBox.setBackground(tercer_Color);
        
        regresar_JButton.setBackground(tercer_Color);
        regresar_JButton.setForeground(tercer_Color_Fuente);
        
        editar_Nombre_Grupo_JButton.setBackground(tercer_Color);
        editar_Nombre_Grupo_JButton.setForeground(tercer_Color_Fuente);
        
        eliminar_Miembro_JButton.setBackground(tercer_Color);
        eliminar_Miembro_JButton.setForeground(tercer_Color_Fuente);

        nombre_Tarea_Pendiente_JTextField.setForeground(tercer_Color_Fuente);
        nombre_Tarea_Pendiente_JTextField.setCaretColor(tercer_Color_Fuente);
        nombre_Tarea_Pendiente_JTextField.setBackground(tercer_Color);
        
        editar_Nombre_Grupo_JTextField.setForeground(tercer_Color_Fuente);
        editar_Nombre_Grupo_JTextField.setCaretColor(tercer_Color_Fuente);
        editar_Nombre_Grupo_JTextField.setBackground(tercer_Color);

        descripcion_Tarea_Pendiente_JTextArea.setForeground(tercer_Color_Fuente);
        descripcion_Tarea_Pendiente_JTextArea.setCaretColor(tercer_Color_Fuente);
        descripcion_Tarea_Pendiente_JTextArea.setBackground(tercer_Color);

        fecha_Finalizacion_Tarea_Pendiente_JPanel.setBackground(tercer_Color);
        fecha_Finalizacion_Tarea_Pendiente_JPanel.setForeground(tercer_Color_Fuente);
        
        informacion_Grupo_JPanel.setBackground(primer_Color);
        chat_Grupal_JPanel.setBackground(primer_Color);
        crear_Tareas_Pendientes_JPanel.setBackground(primer_Color);
        configuraciones_JPanel.setBackground(primer_Color);
        compartir_Archivos_JPanel.setBackground(primer_Color);
        
        escogedor_Fecha_Hora.setForeground(tercer_Color);
        enviar_Mensajes_JPanel.setBackground(primer_Color);
        enviar_Mensaje_JTextField.setBackground(segundo_Color);
        enviar_Mensaje_JTextField.setForeground(segundo_Color_Fuente);
        enviar_Mensaje_JTextField.setCaretColor(segundo_Color_Fuente);
    }
    
    
    @Override
    public void Limpiar() {
        mensajes_Chat_JPanel.removeAll();
        lista_Tareas_Pendientes_JPanel.removeAll();
        lista_Tareas_Finalizadas_JPanel.removeAll();
        archivos_Compartidos_JPanel.removeAll();
        primer_Color = segundo_Color =tercer_Color = primer_Color_Fuente = segundo_Color_Fuente = tercer_Color_Fuente = null;
    }
}
