/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.students;

import courseroom.MainFrame;
import java.awt.Color;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author LENOVO
 */
public class Student_Courses_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Student_Courses_Panel
     */
    public Student_Courses_Panel() {
        initComponents();
        
        System.out.println("Student Courses -> Getting Image From https://loremflickr.com/1280/720/sunset,beach/all");
        try {
            URL imageURL = new URL("https://loremflickr.com/1280/720/sunset,beach/all");
            ImageIcon imageIcon = new ImageIcon(imageURL);
            jLabelCoursesImage.setIcon(imageIcon);
            String tooltip = "Image from " + imageURL.getHost();
            jLabelCoursesImage.setToolTipText(tooltip);
            imageIcon.getImage().flush();
            imageIcon = null;
            imageURL = null;
            tooltip = null;
        } catch (MalformedURLException ex) {
            Logger.getLogger(Student_Courses_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCoursesImage = new javax.swing.JLabel();
        jTabbedPaneCourses = new javax.swing.JTabbedPane();
        jScrollPaneActualCourses = new javax.swing.JScrollPane();
        jPanelActualCourses = new javax.swing.JPanel();
        jScrollPaneSeachCourses = new javax.swing.JScrollPane();
        jPanelSearchCourses = new javax.swing.JPanel();
        jScrollPaneRelatedCourses = new javax.swing.JScrollPane();
        jPanelRelatedCourses = new javax.swing.JPanel();
        jScrollPaneFinishedCourses = new javax.swing.JScrollPane();
        jPanelFinishedCourses = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1085, 630));
        setOpaque(false);

        jLabelCoursesImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTabbedPaneCourses.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N

        jScrollPaneActualCourses.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jScrollPaneActualCourses.setOpaque(false);

        jPanelActualCourses.setOpaque(false);

        javax.swing.GroupLayout jPanelActualCoursesLayout = new javax.swing.GroupLayout(jPanelActualCourses);
        jPanelActualCourses.setLayout(jPanelActualCoursesLayout);
        jPanelActualCoursesLayout.setHorizontalGroup(
            jPanelActualCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1071, Short.MAX_VALUE)
        );
        jPanelActualCoursesLayout.setVerticalGroup(
            jPanelActualCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jScrollPaneActualCourses.setViewportView(jPanelActualCourses);

        jTabbedPaneCourses.addTab("Mis Cursos Actuales", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/online-learning.png")), jScrollPaneActualCourses); // NOI18N

        jScrollPaneSeachCourses.setOpaque(false);

        jPanelSearchCourses.setOpaque(false);

        javax.swing.GroupLayout jPanelSearchCoursesLayout = new javax.swing.GroupLayout(jPanelSearchCourses);
        jPanelSearchCourses.setLayout(jPanelSearchCoursesLayout);
        jPanelSearchCoursesLayout.setHorizontalGroup(
            jPanelSearchCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1071, Short.MAX_VALUE)
        );
        jPanelSearchCoursesLayout.setVerticalGroup(
            jPanelSearchCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jScrollPaneSeachCourses.setViewportView(jPanelSearchCourses);

        jTabbedPaneCourses.addTab("Buscar Cursos", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/online-class.png")), jScrollPaneSeachCourses); // NOI18N

        jScrollPaneRelatedCourses.setOpaque(false);

        jPanelRelatedCourses.setOpaque(false);

        javax.swing.GroupLayout jPanelRelatedCoursesLayout = new javax.swing.GroupLayout(jPanelRelatedCourses);
        jPanelRelatedCourses.setLayout(jPanelRelatedCoursesLayout);
        jPanelRelatedCoursesLayout.setHorizontalGroup(
            jPanelRelatedCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1071, Short.MAX_VALUE)
        );
        jPanelRelatedCoursesLayout.setVerticalGroup(
            jPanelRelatedCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jScrollPaneRelatedCourses.setViewportView(jPanelRelatedCourses);

        jTabbedPaneCourses.addTab("Cursos Relacionados", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/online-education.png")), jScrollPaneRelatedCourses, ""); // NOI18N

        jScrollPaneFinishedCourses.setOpaque(false);

        jPanelFinishedCourses.setOpaque(false);

        javax.swing.GroupLayout jPanelFinishedCoursesLayout = new javax.swing.GroupLayout(jPanelFinishedCourses);
        jPanelFinishedCourses.setLayout(jPanelFinishedCoursesLayout);
        jPanelFinishedCoursesLayout.setHorizontalGroup(
            jPanelFinishedCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1071, Short.MAX_VALUE)
        );
        jPanelFinishedCoursesLayout.setVerticalGroup(
            jPanelFinishedCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jScrollPaneFinishedCourses.setViewportView(jPanelFinishedCourses);

        jTabbedPaneCourses.addTab("Cursos Finalizados", new javax.swing.ImageIcon(getClass().getResource("/resources/icons/login.png")), jScrollPaneFinishedCourses); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCoursesImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPaneCourses))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCoursesImage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPaneCourses)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    public void colorMyComponents(){
        Color noColor = new Color(0,0,0,0);
        jTabbedPaneCourses.setBackground(noColor);
        jTabbedPaneCourses.setForeground(MainFrame.getFontColor());
        
        jScrollPaneActualCourses.getViewport().setOpaque(false);
        jScrollPaneFinishedCourses.getViewport().setOpaque(false);
        jScrollPaneRelatedCourses.getViewport().setOpaque(false);
        jScrollPaneSeachCourses.getViewport().setOpaque(false);
        
        jScrollPaneActualCourses.getVerticalScrollBar().setUnitIncrement(15);
        jScrollPaneFinishedCourses.getVerticalScrollBar().setUnitIncrement(15);
        jScrollPaneRelatedCourses.getVerticalScrollBar().setUnitIncrement(15);
        jScrollPaneSeachCourses.getVerticalScrollBar().setUnitIncrement(15);
        
        jScrollPaneActualCourses.getHorizontalScrollBar().setUnitIncrement(15);
        jScrollPaneFinishedCourses.getHorizontalScrollBar().setUnitIncrement(15);
        jScrollPaneRelatedCourses.getHorizontalScrollBar().setUnitIncrement(15);
        jScrollPaneSeachCourses.getHorizontalScrollBar().setUnitIncrement(15);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCoursesImage;
    private javax.swing.JPanel jPanelActualCourses;
    private javax.swing.JPanel jPanelFinishedCourses;
    private javax.swing.JPanel jPanelRelatedCourses;
    private javax.swing.JPanel jPanelSearchCourses;
    private javax.swing.JScrollPane jScrollPaneActualCourses;
    private javax.swing.JScrollPane jScrollPaneFinishedCourses;
    private javax.swing.JScrollPane jScrollPaneRelatedCourses;
    private javax.swing.JScrollPane jScrollPaneSeachCourses;
    private javax.swing.JTabbedPane jTabbedPaneCourses;
    // End of variables declaration//GEN-END:variables
}
