/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.students;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class Student_Group_Shared_File_Panel extends javax.swing.JPanel {

    private Color secondColor, secondFontColor, thirdColor, thirdFontColor;
   
    
    public Student_Group_Shared_File_Panel(
            String filename,
            String member, 
            String date, 
            Color _secondColor, 
            Color _secondFontColor, 
            Color _thirdColor, 
            Color _thirdFontColor, 
            Color fontColor) {
        initComponents();
        secondColor = _secondColor;
        secondFontColor = _secondFontColor;
        thirdColor = _thirdColor;
        thirdFontColor = _thirdFontColor;
        jLabelFileDate.setText(date);
        jLabelFileName.setText(filename);
        jLabelFileIssuer.setText(member);
        
        jButtonDownloadFile.setBackground(thirdColor);
        jButtonDownloadFile.setForeground(thirdFontColor);
        
        jButtonRemoveFile.setBackground(thirdColor);
        jButtonRemoveFile.setForeground(thirdFontColor);
        
        jLabelFileDate.setForeground(fontColor);
        jLabelFileName.setForeground(fontColor);
        jLabelFileIssuer.setForeground(fontColor);
        
        this.setBorder(javax.swing.BorderFactory.createLineBorder(fontColor));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFileName = new javax.swing.JLabel();
        jLabelFileIssuer = new javax.swing.JLabel();
        jLabelFileDate = new javax.swing.JLabel();
        jButtonDownloadFile = new javax.swing.JButton();
        jLabelTipoArchivoImagen = new javax.swing.JLabel();
        jButtonRemoveFile = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 65));
        setMinimumSize(new java.awt.Dimension(1070, 65));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1070, 65));

        jLabelFileName.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        jLabelFileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFileName.setToolTipText("Nombre Del Archivo");
        jLabelFileName.setMaximumSize(new java.awt.Dimension(373, 21));
        jLabelFileName.setMinimumSize(new java.awt.Dimension(373, 21));
        jLabelFileName.setPreferredSize(new java.awt.Dimension(373, 21));

        jLabelFileIssuer.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        jLabelFileIssuer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFileIssuer.setToolTipText("Emisor Del Archivo");

        jLabelFileDate.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        jLabelFileDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFileDate.setToolTipText("Fecha Del Envío");

        jButtonDownloadFile.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jButtonDownloadFile.setText("Descargar Archivo");
        jButtonDownloadFile.setToolTipText("Descargar Archivo");
        jButtonDownloadFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDownloadFileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDownloadFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDownloadFileMouseExited(evt);
            }
        });

        jLabelTipoArchivoImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoArchivoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/shelf.png"))); // NOI18N

        jButtonRemoveFile.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jButtonRemoveFile.setText("Remover Archivo");
        jButtonRemoveFile.setToolTipText("Remover Archivo Compartido (Eliminar Archivo)");
        jButtonRemoveFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoveFileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRemoveFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRemoveFileMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTipoArchivoImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRemoveFile)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDownloadFile))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFileIssuer, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabelFileDate, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTipoArchivoImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFileIssuer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFileDate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDownloadFile)
                            .addComponent(jButtonRemoveFile))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoveFileMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            int result = JOptionPane.showConfirmDialog(this, "Mensaje De Confirmación", "Esta Segur@ De Eliminar Este Archivo", JOptionPane.QUESTION_MESSAGE);

            if (result == JOptionPane.OK_OPTION) {
                
            }
        }
    }//GEN-LAST:event_jButtonRemoveFileMouseClicked

    private void jButtonDownloadFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDownloadFileMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
        }
    }//GEN-LAST:event_jButtonDownloadFileMouseClicked

    private void jButtonRemoveFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoveFileMouseEntered
        // TODO add your handling code here:
        jButtonRemoveFile.setBackground(secondColor);
        jButtonRemoveFile.setForeground(secondFontColor);
    }//GEN-LAST:event_jButtonRemoveFileMouseEntered

    private void jButtonRemoveFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoveFileMouseExited
        // TODO add your handling code here:
        jButtonRemoveFile.setBackground(thirdColor);
        jButtonRemoveFile.setForeground(thirdFontColor);
    }//GEN-LAST:event_jButtonRemoveFileMouseExited

    private void jButtonDownloadFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDownloadFileMouseEntered
        // TODO add your handling code here:
        jButtonDownloadFile.setBackground(secondColor);
        jButtonDownloadFile.setForeground(secondFontColor);
        
    }//GEN-LAST:event_jButtonDownloadFileMouseEntered

    private void jButtonDownloadFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDownloadFileMouseExited
        // TODO add your handling code here:
        jButtonDownloadFile.setBackground(thirdColor);
        jButtonDownloadFile.setForeground(thirdFontColor);
    }

    // Variables declaration - do not modify//GEN-LAST:event_jButtonDownloadFileMouseExited
    private javax.swing.JButton jButtonDownloadFile;//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemoveFile;
    private javax.swing.JLabel jLabelFileDate;
    private javax.swing.JLabel jLabelFileIssuer;
    private javax.swing.JLabel jLabelFileName;
    private javax.swing.JLabel jLabelTipoArchivoImagen;
    // End of variables declaration//GEN-END:variables
}
