package paneles.profesores.cursos;

import clases.Celda_Renderer;
import clases.Escogedor_Archivos;
import com.github.lgooddatepicker.components.DatePickerSettings;
import courseroom.CourseRoom;
import courseroom.CourseRoom_Frame;
import datos.interfaces.Carta_Visibilidad_Interface;
import datos.interfaces.Componentes_Interface;
import datos.interfaces.Limpieza_Interface;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.ResponseModel;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.FilenameUtils;
import paneles.profesores.Tablero_Profesor_Panel;

/**
 *
 * @author LENOVO
 */
public class Crear_Tarea_Profesor_Panel extends javax.swing.JPanel implements Componentes_Interface, Limpieza_Interface, Carta_Visibilidad_Interface{

    private byte carta_Visible;
    private int Id_Curso;
    private String Id_Vista;
    private int Id_Tarea;
    
    /**
     * Creates new form Crear_Tarea_Profesor_Panel
     */
    public Crear_Tarea_Profesor_Panel(int id_Curso, String id_Vista) {
        initComponents();
        this.Id_Curso = id_Curso;
        this.Id_Vista = id_Vista;
        this.Id_Tarea = -1;
        Iniciar_Componentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_JPanel = new javax.swing.JPanel();
        titulo_JLabel = new javax.swing.JLabel();
        informacion_JButton = new javax.swing.JButton();
        archivos_Adjuntos_JButton = new javax.swing.JButton();
        regresar_JButton = new javax.swing.JButton();
        tarea_JLayeredPane = new javax.swing.JLayeredPane();
        informacion_Tarea_JPanel = new javax.swing.JPanel();
        editar_Nombre_JLabel = new javax.swing.JLabel();
        editar_Nombre_JTextField = new javax.swing.JTextField();
        editar_Descripcion_JLabel = new javax.swing.JLabel();
        editar_Descripcion_JScrollPane = new javax.swing.JScrollPane();
        editar_Descripcion_JTextPane = new javax.swing.JTextPane();
        editar_Fecha_Entrega_JLabel = new javax.swing.JLabel();
        escogedor_Fecha_Hora = new com.github.lgooddatepicker.components.DateTimePicker();
        guardar_Cambios_Datos_Generales_Tarea_JButton = new javax.swing.JButton();
        archivos_Adjuntos_JPanel = new javax.swing.JPanel();
        subir_Archivos_Adjuntos_JButton = new javax.swing.JButton();
        archivos_Adjuntos_JScrollPane = new javax.swing.JScrollPane();
        archivos_Adjuntos_JTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1100, 630));
        setOpaque(false);

        titulo_JPanel.setMaximumSize(new java.awt.Dimension(32767, 72));
        titulo_JPanel.setPreferredSize(new java.awt.Dimension(982, 72));
        titulo_JPanel.setOpaque(false);

        titulo_JLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        titulo_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_JLabel.setText("Crear Tarea");
        titulo_JLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        titulo_JLabel.setMaximumSize(new java.awt.Dimension(818, 68));
        titulo_JLabel.setMinimumSize(new java.awt.Dimension(818, 68));
        titulo_JLabel.setOpaque(true);
        titulo_JLabel.setPreferredSize(new java.awt.Dimension(818, 68));

        informacion_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/info_1.png"))); // NOI18N
        informacion_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ((ImageIcon)informacion_JButton.getIcon()).getImage().flush();
        informacion_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informacion_JButtonMouseClicked(evt);
            }
        });

        archivos_Adjuntos_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/context.png"))); // NOI18N
        archivos_Adjuntos_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ((ImageIcon)archivos_Adjuntos_JButton.getIcon()).getImage().flush();
        archivos_Adjuntos_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archivos_Adjuntos_JButtonMouseClicked(evt);
            }
        });

        regresar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/reply.png"))); // NOI18N
        regresar_JButton.setToolTipText("<html><h3>Regresar A Tareas</h3></html>");
        regresar_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        regresar_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ((ImageIcon)regresar_JButton.getIcon()).getImage().flush();
        regresar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout titulo_JPanelLayout = new javax.swing.GroupLayout(titulo_JPanel);
        titulo_JPanel.setLayout(titulo_JPanelLayout);
        titulo_JPanelLayout.setHorizontalGroup(
            titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titulo_JPanelLayout.createSequentialGroup()
                .addComponent(regresar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titulo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 574, Short.MAX_VALUE)
                .addComponent(informacion_JButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(archivos_Adjuntos_JButton)
                .addGap(43, 43, 43))
        );
        titulo_JPanelLayout.setVerticalGroup(
            titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titulo_JPanelLayout.createSequentialGroup()
                .addGroup(titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresar_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(titulo_JPanelLayout.createSequentialGroup()
                        .addGroup(titulo_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(archivos_Adjuntos_JButton)
                            .addComponent(informacion_JButton)
                            .addComponent(titulo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tarea_JLayeredPane.setPreferredSize(new java.awt.Dimension(982, 534));
        tarea_JLayeredPane.setLayout(new java.awt.CardLayout());

        informacion_Tarea_JPanel.setPreferredSize(new java.awt.Dimension(1110, 630));
        informacion_Tarea_JPanel.setToolTipText("");
        informacion_Tarea_JPanel.setOpaque(false);

        editar_Nombre_JLabel.setText("Nombre");
        editar_Nombre_JLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        editar_Nombre_JTextField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        editar_Nombre_JTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editar_Nombre_JTextFieldKeyTyped(evt);
            }
        });

        editar_Descripcion_JLabel.setText("Descripción");
        editar_Descripcion_JLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        editar_Descripcion_JTextPane.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        editar_Descripcion_JTextPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editar_Descripcion_JTextPaneKeyTyped(evt);
            }
        });
        editar_Descripcion_JScrollPane.setViewportView(editar_Descripcion_JTextPane);

        editar_Fecha_Entrega_JLabel.setText("Fecha De Entrega");
        editar_Fecha_Entrega_JLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        escogedor_Fecha_Hora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        guardar_Cambios_Datos_Generales_Tarea_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/check.png"))); // NOI18N
        guardar_Cambios_Datos_Generales_Tarea_JButton.setText("Guardar Cambios");
        guardar_Cambios_Datos_Generales_Tarea_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guardar_Cambios_Datos_Generales_Tarea_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar_Cambios_Datos_Generales_Tarea_JButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        guardar_Cambios_Datos_Generales_Tarea_JButton.setToolTipText("<html> <h3>Crear nueva cuenta</h3> </html>");
        ((ImageIcon)guardar_Cambios_Datos_Generales_Tarea_JButton.getIcon()).getImage().flush();
        guardar_Cambios_Datos_Generales_Tarea_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardar_Cambios_Datos_Generales_Tarea_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardar_Cambios_Datos_Generales_Tarea_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardar_Cambios_Datos_Generales_Tarea_JButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout informacion_Tarea_JPanelLayout = new javax.swing.GroupLayout(informacion_Tarea_JPanel);
        informacion_Tarea_JPanel.setLayout(informacion_Tarea_JPanelLayout);
        informacion_Tarea_JPanelLayout.setHorizontalGroup(
            informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion_Tarea_JPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editar_Nombre_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(editar_Nombre_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(escogedor_Fecha_Hora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(editar_Fecha_Entrega_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardar_Cambios_Datos_Generales_Tarea_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editar_Descripcion_JScrollPane)
                    .addComponent(editar_Descripcion_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                .addContainerGap())
        );
        informacion_Tarea_JPanelLayout.setVerticalGroup(
            informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion_Tarea_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacion_Tarea_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacion_Tarea_JPanelLayout.createSequentialGroup()
                        .addComponent(editar_Descripcion_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editar_Descripcion_JScrollPane))
                    .addGroup(informacion_Tarea_JPanelLayout.createSequentialGroup()
                        .addComponent(editar_Nombre_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editar_Nombre_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editar_Fecha_Entrega_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escogedor_Fecha_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(guardar_Cambios_Datos_Generales_Tarea_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 279, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tarea_JLayeredPane.add(informacion_Tarea_JPanel, "Informacion");

        archivos_Adjuntos_JPanel.setPreferredSize(new java.awt.Dimension(1110, 630));
        archivos_Adjuntos_JPanel.setToolTipText("");
        archivos_Adjuntos_JPanel.setOpaque(false);

        subir_Archivos_Adjuntos_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/submit.png"))); // NOI18N
        subir_Archivos_Adjuntos_JButton.setText("Subir Adjunto(s)");
        subir_Archivos_Adjuntos_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        subir_Archivos_Adjuntos_JButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        subir_Archivos_Adjuntos_JButton.setToolTipText("Compartir Y Subir Archivo");
        ((ImageIcon)subir_Archivos_Adjuntos_JButton.getIcon()).getImage().flush();
        subir_Archivos_Adjuntos_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subir_Archivos_Adjuntos_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subir_Archivos_Adjuntos_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subir_Archivos_Adjuntos_JButtonMouseExited(evt);
            }
        });

        archivos_Adjuntos_JScrollPane.setBorder(null);
        archivos_Adjuntos_JScrollPane.setOpaque(false);

        archivos_Adjuntos_JTable.setAutoCreateRowSorter(true);
        archivos_Adjuntos_JTable.setModel(

            new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Archivo", "Adjuntado", "Remover"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }

                @Override
                public Class getColumnClass(int column)
                {
                    for(int i = 0; i < archivos_Adjuntos_JTable.getRowCount(); i++)
                    {
                        //The first valid value of a cell of given column is retrieved.
                        if(getValueAt(i,column) != null)
                        {
                            return getValueAt(i, column).getClass();
                        }
                    }
                    //if no valid value is found, default renderer is returned.
                    return super.getColumnClass(column);
                }
            });
            archivos_Adjuntos_JTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            archivos_Adjuntos_JTable.setRowHeight(75);
            archivos_Adjuntos_JTable.setShowGrid(true);
            archivos_Adjuntos_JTable.setShowVerticalLines(false);
            archivos_Adjuntos_JTable.setSurrendersFocusOnKeystroke(true);
            archivos_Adjuntos_JTable.setRowSorter(new TableRowSorter(archivos_Adjuntos_JTable.getModel()));
            archivos_Adjuntos_JTable.addMouseListener(new MouseAdapter() {

                @Override
                public void mousePressed(MouseEvent e) {
                    if (e.getClickCount() == 2) {

                        JTable tabla = (JTable) e.getComponent();
                        int columna = tabla.getSelectedColumn();

                        switch (columna) {
                            // Abrir
                            /*case 0:
                            {
                                int fila = tabla.getRowSorter().convertRowIndexToModel(tabla.getSelectedRow());
                                DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
                                Celda_Renderer celda = (Celda_Renderer) modelo.getValueAt(fila, 0);
                                String extension = FilenameUtils.getExtension(celda.Texto());
                                String ruta = celda.ID();
                                CourseRoom.Utilerias().Abrir_Archivo(ruta, extension, celda.Texto());
                            }
                            break;*/
                            // Remover
                            case 3:
                            {
                                int resultado = JOptionPane.showConfirmDialog(CourseRoom_Frame.getInstance(), 
                                    "¿Estás Segur@ De Remover Este Archivo Adjunto?", "Remover Archivo Adjunto", 
                                    JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

                                if(resultado == JOptionPane.YES_OPTION){
                                    int fila = tabla.getRowSorter().convertRowIndexToModel(tabla.getSelectedRow());

                                    DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
                                    Celda_Renderer celda = (Celda_Renderer)  modelo.getValueAt(fila, columna);

                                    int id_Archivo_Subido = Integer.parseInt(celda.ID());
                                    SwingUtilities.invokeLater(() -> {
                                        ResponseModel response = CourseRoom.Solicitudes().Remover_Archivo_Subido_Tarea(id_Archivo_Subido, Tablero_Profesor_Panel.Id_Usuario());

                                        if(response.Is_Success()){
                                            CourseRoom.Utilerias().Mensaje_Informativo("Remover Archivo Adjunto", response.Mensaje());
                                            modelo.removeRow(fila);
                                        }else{
                                            CourseRoom.Utilerias().Mensaje_Alerta("Remover Archivo Adjunto", response.Mensaje());
                                        }
                                    });
                                }

                                break;
                            }
                            default:
                            break;
                        }
                    }
                }
            });
            archivos_Adjuntos_JScrollPane.setViewportView(archivos_Adjuntos_JTable);

            javax.swing.GroupLayout archivos_Adjuntos_JPanelLayout = new javax.swing.GroupLayout(archivos_Adjuntos_JPanel);
            archivos_Adjuntos_JPanel.setLayout(archivos_Adjuntos_JPanelLayout);
            archivos_Adjuntos_JPanelLayout.setHorizontalGroup(
                archivos_Adjuntos_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(archivos_Adjuntos_JPanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addGroup(archivos_Adjuntos_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(archivos_Adjuntos_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
                        .addGroup(archivos_Adjuntos_JPanelLayout.createSequentialGroup()
                            .addComponent(subir_Archivos_Adjuntos_JButton)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(0, 0, 0))
            );
            archivos_Adjuntos_JPanelLayout.setVerticalGroup(
                archivos_Adjuntos_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(archivos_Adjuntos_JPanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(archivos_Adjuntos_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(subir_Archivos_Adjuntos_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0))
            );

            tarea_JLayeredPane.add(archivos_Adjuntos_JPanel, "Archivos_Adjuntos");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(titulo_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
                        .addComponent(tarea_JLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE))
                    .addGap(32, 32, 32))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(titulo_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tarea_JLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
        }// </editor-fold>//GEN-END:initComponents

    private void informacion_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacion_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            ((CardLayout) tarea_JLayeredPane.getLayout()).show(tarea_JLayeredPane, "Informacion");
            carta_Visible = 0;
            Carta_Visible();
        }
    }//GEN-LAST:event_informacion_JButtonMouseClicked

    private void archivos_Adjuntos_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archivos_Adjuntos_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            ((CardLayout)tarea_JLayeredPane.getLayout()).show(tarea_JLayeredPane, "Archivos_Adjuntos");
            carta_Visible = 1;
            Carta_Visible();
        }
    }//GEN-LAST:event_archivos_Adjuntos_JButtonMouseClicked

    private void regresar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Profesor_Panel.Retirar_Vista(this);
            Tablero_Profesor_Panel.Mostrar_Vista(Id_Vista);
            this.Limpiar();
        }
    }//GEN-LAST:event_regresar_JButtonMouseClicked

    private void regresar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseEntered
        // TODO add your handling code here:
        regresar_JButton.setBackground(CourseRoom.Utilerias().Tercer_Color());
    }//GEN-LAST:event_regresar_JButtonMouseEntered

    private void regresar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseExited
        // TODO add your handling code here:
        regresar_JButton.setBackground(CourseRoom.Utilerias().Segundo_Color());
    }//GEN-LAST:event_regresar_JButtonMouseExited

    private void subir_Archivos_Adjuntos_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subir_Archivos_Adjuntos_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Compartir_Archivos();
        }
    }//GEN-LAST:event_subir_Archivos_Adjuntos_JButtonMouseClicked

    private void subir_Archivos_Adjuntos_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subir_Archivos_Adjuntos_JButtonMouseEntered
        // TODO add your handling code here:
        subir_Archivos_Adjuntos_JButton.setBackground(CourseRoom.Utilerias().Segundo_Color());
        subir_Archivos_Adjuntos_JButton.setForeground(CourseRoom.Utilerias().Segundo_Color_Fuente());
    }//GEN-LAST:event_subir_Archivos_Adjuntos_JButtonMouseEntered

    private void subir_Archivos_Adjuntos_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subir_Archivos_Adjuntos_JButtonMouseExited
        // TODO add your handling code here:
        subir_Archivos_Adjuntos_JButton.setBackground(CourseRoom.Utilerias().Tercer_Color());
        subir_Archivos_Adjuntos_JButton.setForeground(CourseRoom.Utilerias().Tercer_Color_Fuente());
    }//GEN-LAST:event_subir_Archivos_Adjuntos_JButtonMouseExited

    private void editar_Nombre_JTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editar_Nombre_JTextFieldKeyTyped
        char c = evt.getKeyChar();
            if (Character.isDigit(c)) {
            getToolkit().beep();//sonido de no aceptar más caracteres. 
            evt.consume();//hace que esa pulsación de tecla se rechace.
        }
        int longitud = editar_Nombre_JTextField.getText().length();
            if(longitud > 79){
            editar_Nombre_JTextField.setText(editar_Nombre_JTextField.getText().substring(0,longitud-1));
            CourseRoom.Utilerias().Mensaje_Alerta("Alerta!!!","El Título De Tu Tarea<br>Rebasa Los 80 Caracteres");
        }
    }//GEN-LAST:event_editar_Nombre_JTextFieldKeyTyped

    private void editar_Descripcion_JTextPaneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editar_Descripcion_JTextPaneKeyTyped
        int longitud = editar_Descripcion_JTextPane.getText().length();
            if (longitud > 1499) {
            editar_Descripcion_JTextPane.setText(editar_Descripcion_JTextPane.getText().substring(0, longitud - 1));
            CourseRoom.Utilerias().Mensaje_Alerta("Alerta!!!","La Descripción De Tu Tarea<br>Rebasa Los 1500 Caracteres");
          }
    }//GEN-LAST:event_editar_Descripcion_JTextPaneKeyTyped

    private void guardar_Cambios_Datos_Generales_Tarea_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardar_Cambios_Datos_Generales_Tarea_JButtonMouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isLeftMouseButton(evt)) {
            SwingUtilities.invokeLater(() -> {
                String fecha_Finalizacion = CourseRoom.Utilerias().Fecha_Hora(escogedor_Fecha_Hora.getDatePicker().getDate(), escogedor_Fecha_Hora.getTimePicker().getTime());
                ResponseModel respuesta = CourseRoom.Solicitudes().Agregar_Tarea(Id_Curso, editar_Nombre_JTextField.getText()
                        , editar_Descripcion_JTextPane.getText(), fecha_Finalizacion);
                if (respuesta.Is_Success()) {
                    CourseRoom.Utilerias().Mensaje_Informativo("Mensaje Informativo", respuesta.Mensaje());
                    Id_Tarea = respuesta.Codigo();
                    archivos_Adjuntos_JButton.setEnabled(true);
                    informacion_JButton.setEnabled(false);
                    ((CardLayout)tarea_JLayeredPane.getLayout()).show(tarea_JLayeredPane, "Archivos_Adjuntos");
                    carta_Visible = 1;
                    Carta_Visible();
                } else {
                    CourseRoom.Utilerias().Mensaje_Error("Error", respuesta.Mensaje());
                }
            });
        }
    }//GEN-LAST:event_guardar_Cambios_Datos_Generales_Tarea_JButtonMouseClicked

    private void guardar_Cambios_Datos_Generales_Tarea_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardar_Cambios_Datos_Generales_Tarea_JButtonMouseEntered
        // TODO add your handling code here:
        guardar_Cambios_Datos_Generales_Tarea_JButton.setBackground(CourseRoom.Utilerias().Segundo_Color());
        guardar_Cambios_Datos_Generales_Tarea_JButton.setForeground(CourseRoom.Utilerias().Segundo_Color_Fuente());
    }//GEN-LAST:event_guardar_Cambios_Datos_Generales_Tarea_JButtonMouseEntered

    private void guardar_Cambios_Datos_Generales_Tarea_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardar_Cambios_Datos_Generales_Tarea_JButtonMouseExited
        // TODO add your handling code here:
        guardar_Cambios_Datos_Generales_Tarea_JButton.setBackground(CourseRoom.Utilerias().Tercer_Color());
        guardar_Cambios_Datos_Generales_Tarea_JButton.setForeground(CourseRoom.Utilerias().Tercer_Color_Fuente());
    }//GEN-LAST:event_guardar_Cambios_Datos_Generales_Tarea_JButtonMouseExited
  
    public void Compartir_Archivos() {
        Escogedor_Archivos escogedor_Archivos = new Escogedor_Archivos();
        int resultado = escogedor_Archivos.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo_Abierto = escogedor_Archivos.getSelectedFile();
            
            if(archivo_Abierto != null){
                
                long tamanio = FileUtils.sizeOf(archivo_Abierto);
                tamanio = (0 != tamanio) ? tamanio / 1000 / 1000 : 0;
                if(tamanio < 35){
                    
                    SwingUtilities.invokeLater(() -> {
                        try {
                            
                            Celda_Renderer[] celdas = new Celda_Renderer[3];
                            DefaultTableModel modelo = (DefaultTableModel) archivos_Adjuntos_JTable.getModel();
                            Celda_Renderer celda;
                            
                            ResponseModel response = CourseRoom.Solicitudes().Enviar_Archivo_Adjunto_Tarea(Tablero_Profesor_Panel.Id_Usuario(), archivo_Abierto.getName(),
                                    FileUtils.readFileToByteArray(archivo_Abierto),
                                    FilenameUtils.getExtension(archivo_Abierto.getName()));

                            if(response.Is_Success()){
                                String id_Archivo = String.valueOf(response.Codigo());
                                
                                Image imagen = ImageIO.read(getClass().getResource("/recursos/iconos/box.png"));
                                ImageIcon icono = new ImageIcon(imagen);
                                celda = new Celda_Renderer(icono, archivo_Abierto.getName(), id_Archivo);
                                celdas[0] = celda;
                                celda = new Celda_Renderer(CourseRoom.Utilerias().Fecha_Hora_Local(), id_Archivo);
                                celdas[1] = celda;
                                imagen = ImageIO.read(getClass().getResource("/recursos/iconos/close.png"));
                                icono = new ImageIcon(imagen);
                                celda = new Celda_Renderer(icono, id_Archivo);
                                celdas[2] = celda;
                                modelo.insertRow(0,celdas);
                                CourseRoom.Utilerias().Mensaje_Informativo("Tarea",response.Mensaje());
                                imagen.flush();
                                
                            } else{
                                CourseRoom.Utilerias().Mensaje_Alerta("Alerta!!!",response.Mensaje());
                            }

                        } catch (IOException ex) {
                            CourseRoom.Utilerias().Mensaje_Error("Error!!!","Se Encontro Un Error Al Compartir El Archivo");
                        }
                    
                    });
                    
                } else {
                    CourseRoom.Utilerias().Mensaje_Alerta("Alerta!!!","Hay Archivo(s) Que Superan El Tamaño Aceptado De Subida");
                }                 
                    
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archivos_Adjuntos_JButton;
    private javax.swing.JPanel archivos_Adjuntos_JPanel;
    private javax.swing.JScrollPane archivos_Adjuntos_JScrollPane;
    private javax.swing.JTable archivos_Adjuntos_JTable;
    private javax.swing.JLabel editar_Descripcion_JLabel;
    private javax.swing.JScrollPane editar_Descripcion_JScrollPane;
    private javax.swing.JTextPane editar_Descripcion_JTextPane;
    private javax.swing.JLabel editar_Fecha_Entrega_JLabel;
    private javax.swing.JLabel editar_Nombre_JLabel;
    private javax.swing.JTextField editar_Nombre_JTextField;
    private com.github.lgooddatepicker.components.DateTimePicker escogedor_Fecha_Hora;
    private javax.swing.JButton guardar_Cambios_Datos_Generales_Tarea_JButton;
    private javax.swing.JButton informacion_JButton;
    private javax.swing.JPanel informacion_Tarea_JPanel;
    private javax.swing.JButton regresar_JButton;
    private javax.swing.JButton subir_Archivos_Adjuntos_JButton;
    private javax.swing.JLayeredPane tarea_JLayeredPane;
    private javax.swing.JLabel titulo_JLabel;
    private javax.swing.JPanel titulo_JPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Iniciar_Componentes() {
        carta_Visible = 0;
        archivos_Adjuntos_JButton.setEnabled(false);
        editar_Descripcion_JScrollPane.getViewport().setOpaque(false);
        editar_Descripcion_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        editar_Descripcion_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
        Font gadugi = new Font("Segoe UI", Font.BOLD, 16);
        archivos_Adjuntos_JScrollPane.getViewport().setOpaque(false);
        archivos_Adjuntos_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        archivos_Adjuntos_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
        archivos_Adjuntos_JTable.getTableHeader().setFont(gadugi);
        archivos_Adjuntos_JTable.setDefaultRenderer(Celda_Renderer.class, new Celda_Renderer());
        
        archivos_Adjuntos_JTable.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                if (e.getClickCount() == 2) {

                    JTable tabla = (JTable) e.getComponent();
                    int columna = tabla.getSelectedColumn();

                    //Remover
                    if (columna == 2) {
                        
                    }

                }
            }
        });
        
        LocalDate fecha_Minima = LocalDate.now();
        Locale local = new Locale("es","MX");
        DatePickerSettings ajustes_Fecha = new DatePickerSettings(local);
        ajustes_Fecha.setFirstDayOfWeek(DayOfWeek.MONDAY);
        ajustes_Fecha.setFontVetoedDate(gadugi);
        ajustes_Fecha.setFontValidDate(gadugi);
        ajustes_Fecha.setFontCalendarDateLabels(gadugi);
        ajustes_Fecha.setFontCalendarWeekNumberLabels(gadugi);
        ajustes_Fecha.setFontCalendarWeekdayLabels(gadugi);
        ajustes_Fecha.setFontTodayLabel(gadugi);
        ajustes_Fecha.setFontMonthAndYearMenuLabels(gadugi);
        ajustes_Fecha.setFontTodayLabel(gadugi);
        ajustes_Fecha.setVisibleClearButton(false);
        ajustes_Fecha.setVisibleTodayButton(false);
        escogedor_Fecha_Hora.getDatePicker().setSettings(ajustes_Fecha);
        escogedor_Fecha_Hora.getDatePicker().getComponent(0).setFont(gadugi);
        escogedor_Fecha_Hora.getDatePicker().getSettings().setDateRangeLimits(fecha_Minima, LocalDate.MAX);
        escogedor_Fecha_Hora.getDatePicker().setDate(fecha_Minima);
        escogedor_Fecha_Hora.getDatePicker().setOpaque(false);
        escogedor_Fecha_Hora.getDatePicker().setVisible(true);
        
        escogedor_Fecha_Hora.getTimePicker().setFont(gadugi);
        escogedor_Fecha_Hora.getTimePicker().getComponent(0).setFont(gadugi);
        escogedor_Fecha_Hora.getTimePicker().setTime(LocalTime.now());
        escogedor_Fecha_Hora.getTimePicker().setOpaque(false);
        escogedor_Fecha_Hora.getTimePicker().setVisible(true);
        
        Colorear_Componentes();
    }

    @Override
    public void Colorear_Componentes() {
        regresar_JButton.setBackground(CourseRoom.Utilerias().Segundo_Color());
        titulo_JLabel.setForeground(CourseRoom.Utilerias().Segundo_Color_Fuente());
        titulo_JLabel.setBackground(CourseRoom.Utilerias().Segundo_Color());
        
        
        archivos_Adjuntos_JTable.setBackground(CourseRoom.Utilerias().Primer_Color());
        archivos_Adjuntos_JTable.setForeground(CourseRoom.Utilerias().Primer_Color_Fuente());

        archivos_Adjuntos_JTable.getTableHeader().setBackground(CourseRoom.Utilerias().Tercer_Color());
        archivos_Adjuntos_JTable.getTableHeader().setForeground(CourseRoom.Utilerias().Tercer_Color_Fuente());
        archivos_Adjuntos_JTable.setGridColor(CourseRoom.Utilerias().Segundo_Color());

        archivos_Adjuntos_JTable.setSelectionBackground(CourseRoom.Utilerias().Segundo_Color());
        archivos_Adjuntos_JTable.setSelectionForeground(CourseRoom.Utilerias().Segundo_Color_Fuente());

        DefaultTableModel modelo = (DefaultTableModel) archivos_Adjuntos_JTable.getModel();
        Celda_Renderer celda;
        for (int i = 0; i < archivos_Adjuntos_JTable.getRowCount(); i++) {
            for (int j = 0; j < modelo.getColumnCount(); j++) {
                celda = (Celda_Renderer) modelo.getValueAt(i, j);
                celda.Color_Fuente(CourseRoom.Utilerias().Primer_Color_Fuente());
            }
        }
        
        editar_Nombre_JLabel.setForeground(CourseRoom.Utilerias().Primer_Color_Fuente());
        editar_Descripcion_JLabel.setForeground(CourseRoom.Utilerias().Primer_Color_Fuente());
        editar_Fecha_Entrega_JLabel.setForeground(CourseRoom.Utilerias().Primer_Color_Fuente());

        editar_Nombre_JTextField.setForeground(CourseRoom.Utilerias().Tercer_Color_Fuente());
        editar_Nombre_JTextField.setBackground(CourseRoom.Utilerias().Tercer_Color());
        editar_Nombre_JTextField.setCaretColor(CourseRoom.Utilerias().Tercer_Color_Fuente());
        editar_Descripcion_JTextPane.setForeground(CourseRoom.Utilerias().Segundo_Color_Fuente());
        editar_Descripcion_JTextPane.setBackground(CourseRoom.Utilerias().Segundo_Color());
        editar_Descripcion_JTextPane.setCaretColor(CourseRoom.Utilerias().Segundo_Color_Fuente());

        escogedor_Fecha_Hora.setForeground(CourseRoom.Utilerias().Tercer_Color_Fuente());
        escogedor_Fecha_Hora.setBackground(CourseRoom.Utilerias().Tercer_Color());

        subir_Archivos_Adjuntos_JButton.setBackground(CourseRoom.Utilerias().Tercer_Color());
        subir_Archivos_Adjuntos_JButton.setForeground(CourseRoom.Utilerias().Tercer_Color_Fuente());
        
        guardar_Cambios_Datos_Generales_Tarea_JButton.setBackground(CourseRoom.Utilerias().Tercer_Color());
        guardar_Cambios_Datos_Generales_Tarea_JButton.setForeground(CourseRoom.Utilerias().Tercer_Color_Fuente());

        Carta_Visible();
    }

    @Override
    public void Limpiar() {
        DefaultTableModel modelo = (DefaultTableModel) archivos_Adjuntos_JTable.getModel();
        modelo.setRowCount(0);
    }

    @Override
    public void Carta_Visible() {
        switch (carta_Visible) {
            case 0:
                informacion_JButton.setBackground(CourseRoom.Utilerias().Tercer_Color());
                archivos_Adjuntos_JButton.setBackground(CourseRoom.Utilerias().Segundo_Color());
                break;
            case 1:
                informacion_JButton.setBackground(CourseRoom.Utilerias().Segundo_Color());
                archivos_Adjuntos_JButton.setBackground(CourseRoom.Utilerias().Tercer_Color());
                break;
        }
    }
}
