/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template archivo, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles.generales.mensajes;

import datos.interfaces.Componentes_Interface;
import javax.swing.ImageIcon;
import courseroom.CourseRoom;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class Mensaje_Archivo_Izquierdo_General_Panel extends javax.swing.JPanel implements Componentes_Interface{

    private String ruta, extension;
    
    public Mensaje_Archivo_Izquierdo_General_Panel(
            String emisor,
            String fecha,
            String _ruta,
            String _extension,
            String _nombre_Archivo) {

        initComponents();

        fecha_JLabel.setText(fecha);
        emisor_JLabel.setText(emisor);
        nombre_Archivo_JLabel.setText(_nombre_Archivo);
        
        ruta = _ruta;
        extension = _extension;

        Iniciar_Componentes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido_JPanel = new javax.swing.JPanel();
        emisor_JLabel = new javax.swing.JLabel();
        fecha_JLabel = new javax.swing.JLabel();
        nombre_Archivo_JLabel = new javax.swing.JLabel();
        descargar_JButton = new javax.swing.JButton();
        abrir_JButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 200));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1110, 200));

        contenido_JPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contenido_JPanel.setMaximumSize(new java.awt.Dimension(713, 188));
        contenido_JPanel.setPreferredSize(new java.awt.Dimension(713, 188));

        emisor_JLabel.setFont(new java.awt.Font("Gadugi", 1, 15)); // NOI18N
        emisor_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emisor_JLabel.setToolTipText("<html> <h3>Emisor del mensaje</h3> </html>");

        fecha_JLabel.setFont(new java.awt.Font("Gadugi", 1, 15)); // NOI18N
        fecha_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fecha_JLabel.setToolTipText("<html> <h3>Fecha y hora del mensaje recibido</h3> </html>");
        fecha_JLabel.setMaximumSize(new java.awt.Dimension(33210, 25));

        nombre_Archivo_JLabel.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        nombre_Archivo_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_Archivo_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/file.png"))); // NOI18N
        nombre_Archivo_JLabel.setToolTipText("<html> <h3>Nombre del archivo</h3> </html>");
        ((ImageIcon)nombre_Archivo_JLabel.getIcon()).getImage().flush();

        descargar_JButton.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        descargar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/download.png"))); // NOI18N
        descargar_JButton.setText("Descargar");
        descargar_JButton.setMaximumSize(new java.awt.Dimension(75, 35));
        descargar_JButton.setMinimumSize(new java.awt.Dimension(75, 35));
        descargar_JButton.setPreferredSize(new java.awt.Dimension(75, 35));
        ((ImageIcon)descargar_JButton.getIcon()).getImage().flush();
        descargar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descargar_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                descargar_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                descargar_JButtonMouseExited(evt);
            }
        });

        abrir_JButton.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        abrir_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/box.png"))); // NOI18N
        abrir_JButton.setText("Abrir");
        abrir_JButton.setMaximumSize(new java.awt.Dimension(75, 35));
        abrir_JButton.setMinimumSize(new java.awt.Dimension(75, 35));
        abrir_JButton.setPreferredSize(new java.awt.Dimension(75, 35));
        ((ImageIcon)abrir_JButton.getIcon()).getImage().flush();
        abrir_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrir_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abrir_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abrir_JButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contenido_JPanelLayout = new javax.swing.GroupLayout(contenido_JPanel);
        contenido_JPanel.setLayout(contenido_JPanelLayout);
        contenido_JPanelLayout.setHorizontalGroup(
            contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenido_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenido_JPanelLayout.createSequentialGroup()
                        .addGroup(contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emisor_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_Archivo_JLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contenido_JPanelLayout.createSequentialGroup()
                        .addComponent(abrir_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descargar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        contenido_JPanelLayout.setVerticalGroup(
            contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenido_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emisor_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(nombre_Archivo_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addGroup(contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descargar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrir_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(fecha_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(contenido_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenido_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descargar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descargar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
        }
    }//GEN-LAST:event_descargar_JButtonMouseClicked

    private void descargar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descargar_JButtonMouseEntered
        // TODO add your handling code here:
        descargar_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
        descargar_JButton.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
    }//GEN-LAST:event_descargar_JButtonMouseEntered

    private void descargar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descargar_JButtonMouseExited
        // TODO add your handling code here:
        descargar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
        descargar_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
    }//GEN-LAST:event_descargar_JButtonMouseExited

    private void abrir_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrir_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            CourseRoom.Utilerias.Abrir_Archivo(ruta, extension, nombre_Archivo_JLabel.getText());
        }
    }//GEN-LAST:event_abrir_JButtonMouseClicked

    private void abrir_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrir_JButtonMouseEntered
        // TODO add your handling code here:
        abrir_JButton.setBackground(CourseRoom.Utilerias.Segundo_Color());
        abrir_JButton.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
    }//GEN-LAST:event_abrir_JButtonMouseEntered

    private void abrir_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrir_JButtonMouseExited
        // TODO add your handling code here:
        abrir_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
        abrir_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
    }//GEN-LAST:event_abrir_JButtonMouseExited

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir_JButton;
    private javax.swing.JPanel contenido_JPanel;
    private javax.swing.JButton descargar_JButton;
    private javax.swing.JLabel emisor_JLabel;
    private javax.swing.JLabel fecha_JLabel;
    private javax.swing.JLabel nombre_Archivo_JLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Iniciar_Componentes() {
        Colorear_Componentes();
        
    }

    @Override
    public void Colorear_Componentes() {
        contenido_JPanel.setBackground(CourseRoom.Utilerias.Segundo_Color());
        contenido_JPanel.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());

        fecha_JLabel.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        emisor_JLabel.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        nombre_Archivo_JLabel.setForeground(CourseRoom.Utilerias.Segundo_Color_Fuente());
        
        descargar_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
        descargar_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
        abrir_JButton.setBackground(CourseRoom.Utilerias.Tercer_Color());
        abrir_JButton.setForeground(CourseRoom.Utilerias.Tercer_Color_Fuente());
    }

}
