/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.generals;

import data.interfaces.Limpieza_Interface;
import java.awt.Color;
import java.io.File;
import javax.swing.SwingUtilities;
import main.MainFrame;

/**
 *
 * @author LENOVO
 */
public class Archivo_Subido_Tarea_General_Panel extends javax.swing.JPanel implements Limpieza_Interface{

    private Color primer_Color_Fuente,segundo_Color_Fuente,primer_Color_Fondo, segundo_Color_Fondo;
    private File archivo_Subido;
    
    public Archivo_Subido_Tarea_General_Panel(
            File archivo, 
            Color _background, 
            Color _primer_Color_Fuente, 
            Color _segundo_Color_Fondo, 
            Color _segundo_Color_Fuente) {
        initComponents();
        
        segundo_Color_Fuente = _segundo_Color_Fuente;
        primer_Color_Fondo = _background;
        segundo_Color_Fondo = _segundo_Color_Fondo;
        primer_Color_Fuente = _primer_Color_Fuente;
        archivo_Subido = archivo;
        
        nombre_JLabel.setForeground(primer_Color_Fuente);
        nombre_JLabel.setBackground(_background);
        nombre_JLabel.setText(archivo_Subido.getName());
        nombre_JLabel.setToolTipText(MainFrame.Concatenar("Nombre Del Archivo Subido: ", nombre_JLabel.getText()));
        
        remover_JButton.setForeground(primer_Color_Fuente);
        remover_JButton.setBackground(primer_Color_Fondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icono_JLabel = new javax.swing.JLabel();
        remover_JButton = new javax.swing.JButton();
        nombre_JLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 44));
        setMinimumSize(new java.awt.Dimension(400, 44));
        setOpaque(false);

        icono_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/submit.png"))); // NOI18N

        remover_JButton.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        remover_JButton.setText("X");
        remover_JButton.setToolTipText("Remover Archivo");
        remover_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remover_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                remover_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                remover_JButtonMouseExited(evt);
            }
        });

        nombre_JLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        nombre_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_JLabel.setToolTipText("Nombre Del Archivo");
        nombre_JLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icono_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remover_JButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icono_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(remover_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void remover_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remover_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            this.setVisible(false);
        }
    }//GEN-LAST:event_remover_JButtonMouseClicked

    private void remover_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remover_JButtonMouseEntered
        // TODO add your handling code here:
        remover_JButton.setForeground(segundo_Color_Fuente);
        remover_JButton.setBackground(segundo_Color_Fondo);
    }//GEN-LAST:event_remover_JButtonMouseEntered

    private void remover_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remover_JButtonMouseExited
        // TODO add your handling code here:
        remover_JButton.setForeground(primer_Color_Fuente);
        remover_JButton.setBackground(primer_Color_Fondo);
    }//GEN-LAST:event_remover_JButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icono_JLabel;
    private javax.swing.JLabel nombre_JLabel;
    private javax.swing.JButton remover_JButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Limpiar() {
        primer_Color_Fuente = segundo_Color_Fuente = primer_Color_Fondo =  segundo_Color_Fondo = null;
        archivo_Subido = null;
    }
}
