/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseroom;


import dashboard.DashboardPanel;
import java.awt.CardLayout;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import login.LoginPanel;
import login.RecuperarCredencialesPanel;
import registration.CrearCuentaPanel;
/**
 *
 * @author LENOVO
 */
public class MainFrame extends javax.swing.JFrame {

    private static LoginPanel login;
    private static RecuperarCredencialesPanel recuperarCredenciales;
    private static CrearCuentaPanel crearCuenta;
    private static DashboardPanel dashboard;
    private static Color lightBlue,darkBlue;
    private static ImageIcon logoImage;
    private static CardLayout viewerLayout;
   
    
    /**
     * Creates new form MainFrame
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public MainFrame() {
        
        initComponents();
        jScrollPaneFondo.getVerticalScrollBar().setUnitIncrement(15);
        jScrollPaneFondo.getHorizontalScrollBar().setUnitIncrement(15);
        
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        
        darkBlue = new Color(14,30,64);
        lightBlue  = new Color(104,194,232);
        Image darkImageLogo = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../resources/images/Course_Room_Brand_Blue.png"))).getImage();
        logoImage = new ImageIcon(darkImageLogo.getScaledInstance(150, 125, Image.SCALE_SMOOTH));
        darkImageLogo = null;
        login = new LoginPanel();
        recuperarCredenciales = new RecuperarCredencialesPanel();
        crearCuenta = new CrearCuentaPanel();
        dashboard = new DashboardPanel();
        
        jPanelViewer.add("login",login);
        jPanelViewer.add("recuperarCredenciales",recuperarCredenciales);
        jPanelViewer.add("crearCuenta",crearCuenta);
        jPanelViewer.add("dashboard",dashboard);
        
        viewerLayout = (CardLayout)jPanelViewer.getLayout();
        
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneFondo = new javax.swing.JScrollPane();
        jPanelViewer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CourseRoom - Tu Espacio Personal Para Estudiar");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../resources/images/Course_Room_Logo.png")));
        setMinimumSize(new java.awt.Dimension(800, 650));
        setName("mainFrame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelViewer.setLayout(new java.awt.CardLayout());
        jScrollPaneFondo.setViewportView(jPanelViewer);

        getContentPane().add(jScrollPaneFondo, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dispose();
        System.gc();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    public static void showLogin(){
        viewerLayout.show(jPanelViewer, "login");
    }
    
    public static void showRecuperarCredenciales(){
        viewerLayout.show(jPanelViewer, "recuperarCredenciales");
    }
    
    public static void showCrearCuenta(){
        viewerLayout.show(jPanelViewer, "crearCuenta");
    }
    
    public static void showDashboard(){
        viewerLayout.show(jPanelViewer, "dashboard");
    }
    
    public static void logOut(){
        viewerLayout.show(jPanelViewer, "login");
    }
   
    @Override
    public void dispose(){
        dashboard.dispose();
        recuperarCredenciales.dispose();
        login = null;
        recuperarCredenciales = null;
        crearCuenta = null;
        dashboard = null;
        lightBlue = null;
        darkBlue = null;
        logoImage = null;
        viewerLayout = null;
        super.dispose();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel jPanelViewer;
    private javax.swing.JScrollPane jScrollPaneFondo;
    // End of variables declaration//GEN-END:variables

   
    /**
     * @return the lightBlue
     */
    public static Color getLightBlue() {
        return lightBlue;
    }

    /**
     * @return the darkBlue
     */
    public static Color getDarkBlue() {
        return darkBlue;
    }
    

    /**
     * @return the logoImage
     */
    public static ImageIcon getLogoImage() {
        return logoImage;
    }


    /**
     * @return the login
     */
    public static LoginPanel getLogin() {
        return login;
    }


    
    
}
