/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles.estudiantes;

import interfaces.Componentes_Interface;
import interfaces.Limpieza_Interface;
import java.awt.Color;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class Archivo_Compartido_Grupo_Estudiante_Panel extends javax.swing.JPanel implements Limpieza_Interface, Componentes_Interface{

    private Color segundo_Color, segundo_Color_Fuente, tercer_Color, tercer_Color_Fuente;
    private File archivo;
    
    public Archivo_Compartido_Grupo_Estudiante_Panel(
            File _archivo,
            String nombre_Miembro, 
            String fecha_Hora, 
            Color _segundo_Color, 
            Color _segundo_Color_Fuente, 
            Color _tercer_Color, 
            Color _tercer_Color_Fuente) {
        
        initComponents();
        
        archivo = _archivo;
        segundo_Color = _segundo_Color;
        segundo_Color_Fuente = _segundo_Color_Fuente;
        tercer_Color = _tercer_Color;
        tercer_Color_Fuente = _tercer_Color_Fuente;
        
        fecha_Hora_JLabel.setText(fecha_Hora);
        nombre_JLabel.setText(archivo.getName());
        emisor_JLabel.setText(nombre_Miembro);
        
        Iniciar_Componentes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido_JPanel = new javax.swing.JPanel();
        nombre_JLabel = new javax.swing.JLabel();
        emisor_JLabel = new javax.swing.JLabel();
        fecha_Hora_JLabel = new javax.swing.JLabel();
        descargar_JButton = new javax.swing.JButton();
        icono_JLabel = new javax.swing.JLabel();
        remover_JButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 146));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1080, 146));

        contenido_JPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nombre_JLabel.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        nombre_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_JLabel.setToolTipText("<html>\n<h3>Nombre del archivo compartido</h3>\n</html>");
        nombre_JLabel.setMaximumSize(new java.awt.Dimension(373, 21));
        nombre_JLabel.setMinimumSize(new java.awt.Dimension(373, 21));
        nombre_JLabel.setPreferredSize(new java.awt.Dimension(373, 21));

        emisor_JLabel.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        emisor_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emisor_JLabel.setToolTipText("<html>\n<h3>Compartido por</h3>\n</html>");

        fecha_Hora_JLabel.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        fecha_Hora_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_Hora_JLabel.setToolTipText("<html>\n<h3>Fecha y hora de la compartición</h3>\n</html>");

        descargar_JButton.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        descargar_JButton.setText("Descargar");
        descargar_JButton.setToolTipText("");
        descargar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descargar_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                descargar_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                descargar_JButtonMouseExited(evt);
            }
        });

        icono_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/shelf.png"))); // NOI18N

        remover_JButton.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        remover_JButton.setText("Remover");
        remover_JButton.setToolTipText("");
        remover_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remover_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                remover_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                remover_JButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contenido_JPanelLayout = new javax.swing.GroupLayout(contenido_JPanel);
        contenido_JPanel.setLayout(contenido_JPanelLayout);
        contenido_JPanelLayout.setHorizontalGroup(
            contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenido_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icono_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenido_JPanelLayout.createSequentialGroup()
                        .addComponent(remover_JButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descargar_JButton))
                    .addComponent(nombre_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                    .addComponent(emisor_JLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fecha_Hora_JLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contenido_JPanelLayout.setVerticalGroup(
            contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenido_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombre_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenido_JPanelLayout.createSequentialGroup()
                        .addComponent(emisor_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha_Hora_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icono_JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenido_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remover_JButton)
                    .addComponent(descargar_JButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contenido_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenido_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void remover_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remover_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
            int resultado = JOptionPane.showConfirmDialog(this, "Mensaje De Confirmación", "Esta Segur@ De Eliminar Este Archivo", JOptionPane.QUESTION_MESSAGE);

            if (resultado == JOptionPane.OK_OPTION) {
                
            }
        }
    }//GEN-LAST:event_remover_JButtonMouseClicked

    private void descargar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descargar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
        }
    }//GEN-LAST:event_descargar_JButtonMouseClicked

    private void remover_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remover_JButtonMouseEntered
        // TODO add your handling code here:
        remover_JButton.setBackground(segundo_Color);
        remover_JButton.setForeground(segundo_Color_Fuente);
    }//GEN-LAST:event_remover_JButtonMouseEntered

    private void remover_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remover_JButtonMouseExited
        // TODO add your handling code here:
        remover_JButton.setBackground(tercer_Color);
        remover_JButton.setForeground(tercer_Color_Fuente);
    }//GEN-LAST:event_remover_JButtonMouseExited

    private void descargar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descargar_JButtonMouseEntered
        // TODO add your handling code here:
        descargar_JButton.setBackground(segundo_Color);
        descargar_JButton.setForeground(segundo_Color_Fuente);
        
    }//GEN-LAST:event_descargar_JButtonMouseEntered

    private void descargar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descargar_JButtonMouseExited
        // TODO add your handling code here:
        descargar_JButton.setBackground(tercer_Color);
        descargar_JButton.setForeground(tercer_Color_Fuente);
    }

    // Variables declaration - do not modify//GEN-LAST:event_descargar_JButtonMouseExited
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenido_JPanel;
    private javax.swing.JButton descargar_JButton;
    private javax.swing.JLabel emisor_JLabel;
    private javax.swing.JLabel fecha_Hora_JLabel;
    private javax.swing.JLabel icono_JLabel;
    private javax.swing.JLabel nombre_JLabel;
    private javax.swing.JButton remover_JButton;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void Iniciar_Componentes() {
        
        Colorear_Componentes();
    }

    @Override
    public void Colorear_Componentes() {
        
        fecha_Hora_JLabel.setForeground(segundo_Color_Fuente);
        nombre_JLabel.setForeground(segundo_Color_Fuente);
        emisor_JLabel.setForeground(segundo_Color_Fuente);

        contenido_JPanel.setBackground(segundo_Color);
        descargar_JButton.setBackground(tercer_Color);
        descargar_JButton.setForeground(tercer_Color_Fuente);
        remover_JButton.setBackground(tercer_Color);
        remover_JButton.setForeground(tercer_Color_Fuente);
    }
    
    @Override
    public void Limpiar() {
        archivo = null;
        segundo_Color = segundo_Color_Fuente = tercer_Color = tercer_Color_Fuente = null;
    }
}
