/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles.estudiantes;

import interfaces.Componentes_Interface;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import main.CourseRoom;

/**
 *
 * @author LENOVO
 */
public class Curso_Estudiante_Panel extends javax.swing.JPanel implements Componentes_Interface{

    private Color primer_Color, segundo_Color,tercer_Color,primer_Color_Fuente, segundo_Color_Fuente, tercer_Color_Fuente;
    
    
    public Curso_Estudiante_Panel(
            String id,
            String nombre_Curso,
            String nombre_Profesor,
            Image imagen_Curso,
            Image imagen_Profesor,
            Color _primer_Color,
            Color _primer_Color_Fuente,
            Color _segundo_Color,
            Color _segundo_Color_Fuente,
            Color _tercer_Color,
            Color _tercer_Color_Fuente
        ) {
        
        initComponents();
        
        nombre_Curso_JTextPane.setText(CourseRoom.Formato_HTML_Centro(nombre_Curso));
        nombre_Profesor_JTextPane.setText(CourseRoom.Formato_HTML_Centro(nombre_Profesor));
        
        ImageIcon icono = new ImageIcon(imagen_Curso);
        imagen_Curso_JLabel.setIcon(icono);
        icono = new ImageIcon(imagen_Profesor);
        imagen_Profesor_JLabel.setIcon(icono);
        
        primer_Color = _primer_Color;
        segundo_Color = _segundo_Color;
        primer_Color_Fuente = _primer_Color_Fuente;
        segundo_Color_Fuente = _segundo_Color_Fuente;
        tercer_Color = _tercer_Color;
        tercer_Color_Fuente = _tercer_Color_Fuente;
        
        Iniciar_Componentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        curso_JTabbedPane = new javax.swing.JTabbedPane();
        informacion_Curso_JPanel = new javax.swing.JPanel();
        imagen_Profesor_JLabel = new javax.swing.JLabel();
        imagen_Curso_JLabel = new javax.swing.JLabel();
        regresar_JButton = new javax.swing.JButton();
        nombre_Curso_JScrollPane = new javax.swing.JScrollPane();
        nombre_Curso_JTextPane = new javax.swing.JTextPane();
        nombre_Profesor_JScrollPane = new javax.swing.JScrollPane();
        nombre_Profesor_JTextPane = new javax.swing.JTextPane();
        descripcion_Curso_JScrollPane = new javax.swing.JScrollPane();
        descripcion_Curso_JTextPane = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1080, 630));
        setLayout(new java.awt.CardLayout());

        curso_JTabbedPane.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        curso_JTabbedPane.setOpaque(true);

        imagen_Profesor_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen_Profesor_JLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagen_Profesor_JLabel.setMaximumSize(new java.awt.Dimension(175, 175));
        imagen_Profesor_JLabel.setMinimumSize(new java.awt.Dimension(175, 175));
        imagen_Profesor_JLabel.setPreferredSize(new java.awt.Dimension(175, 175));

        imagen_Curso_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen_Curso_JLabel.setMinimumSize(new java.awt.Dimension(1068, 175));
        imagen_Curso_JLabel.setPreferredSize(new java.awt.Dimension(1068, 175));

        regresar_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/reply.png"))); // NOI18N
        regresar_JButton.setBorder(null);
        regresar_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regresar_JButtonMouseExited(evt);
            }
        });

        nombre_Curso_JScrollPane.setBorder(null);

        nombre_Curso_JTextPane.setEditable(false);
        nombre_Curso_JTextPane.setBorder(null);
        nombre_Curso_JTextPane.setContentType("text/html"); // NOI18N
        nombre_Curso_JTextPane.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        nombre_Curso_JTextPane.setText("");
        nombre_Curso_JScrollPane.setViewportView(nombre_Curso_JTextPane);

        nombre_Profesor_JScrollPane.setBorder(null);

        nombre_Profesor_JTextPane.setEditable(false);
        nombre_Profesor_JTextPane.setBorder(null);
        nombre_Profesor_JTextPane.setContentType("text/html"); // NOI18N
        nombre_Profesor_JTextPane.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        nombre_Profesor_JTextPane.setText("");
        nombre_Profesor_JScrollPane.setViewportView(nombre_Profesor_JTextPane);

        descripcion_Curso_JScrollPane.setBorder(null);
        descripcion_Curso_JScrollPane.setOpaque(false);

        descripcion_Curso_JTextPane.setEditable(false);
        descripcion_Curso_JTextPane.setBorder(null);
        descripcion_Curso_JTextPane.setContentType("text/html"); // NOI18N
        descripcion_Curso_JTextPane.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        descripcion_Curso_JTextPane.setText("");
        descripcion_Curso_JTextPane.setOpaque(false);
        descripcion_Curso_JScrollPane.setViewportView(descripcion_Curso_JTextPane);

        javax.swing.GroupLayout informacion_Curso_JPanelLayout = new javax.swing.GroupLayout(informacion_Curso_JPanel);
        informacion_Curso_JPanel.setLayout(informacion_Curso_JPanelLayout);
        informacion_Curso_JPanelLayout.setHorizontalGroup(
            informacion_Curso_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion_Curso_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacion_Curso_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre_Curso_JScrollPane)
                    .addComponent(imagen_Curso_JLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacion_Curso_JPanelLayout.createSequentialGroup()
                        .addGroup(informacion_Curso_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacion_Curso_JPanelLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(imagen_Profesor_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
                            .addComponent(nombre_Profesor_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(descripcion_Curso_JScrollPane))
                    .addGroup(informacion_Curso_JPanelLayout.createSequentialGroup()
                        .addComponent(regresar_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        informacion_Curso_JPanelLayout.setVerticalGroup(
            informacion_Curso_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion_Curso_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen_Curso_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre_Curso_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(informacion_Curso_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacion_Curso_JPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcion_Curso_JScrollPane))
                    .addGroup(informacion_Curso_JPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(imagen_Profesor_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre_Profesor_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(regresar_JButton)))
                .addContainerGap())
        );

        curso_JTabbedPane.addTab("Información", new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/online-learning.png")), informacion_Curso_JPanel); // NOI18N

        add(curso_JTabbedPane, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void regresar_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Pagina_Cursos");
        }
    }//GEN-LAST:event_regresar_JButtonMouseClicked

    private void regresar_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseExited
        // TODO add your handling code here:
        regresar_JButton.setBackground(primer_Color);
    }//GEN-LAST:event_regresar_JButtonMouseExited

    private void regresar_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar_JButtonMouseEntered
        // TODO add your handling code here:
        regresar_JButton.setBackground(segundo_Color);
    }//GEN-LAST:event_regresar_JButtonMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane curso_JTabbedPane;
    private javax.swing.JScrollPane descripcion_Curso_JScrollPane;
    private javax.swing.JTextPane descripcion_Curso_JTextPane;
    private javax.swing.JLabel imagen_Curso_JLabel;
    private javax.swing.JLabel imagen_Profesor_JLabel;
    private javax.swing.JPanel informacion_Curso_JPanel;
    private javax.swing.JScrollPane nombre_Curso_JScrollPane;
    private javax.swing.JTextPane nombre_Curso_JTextPane;
    private javax.swing.JScrollPane nombre_Profesor_JScrollPane;
    private javax.swing.JTextPane nombre_Profesor_JTextPane;
    private javax.swing.JButton regresar_JButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Iniciar_Componentes() {
       
        descripcion_Curso_JScrollPane.getViewport().setOpaque(false);
        nombre_Curso_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        nombre_Curso_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
        
        nombre_Profesor_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        nombre_Profesor_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
        
        descripcion_Curso_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        descripcion_Curso_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
        
        descripcion_Curso_JTextPane.setText(CourseRoom.Formato_HTML_Centro(CourseRoom.Faker().lorem().paragraph(6)));
        
        Colorear_Componentes();
    }

    @Override
    public void Colorear_Componentes() {
        
        curso_JTabbedPane.setBackground(segundo_Color);
        curso_JTabbedPane.setForeground(segundo_Color_Fuente);
        informacion_Curso_JPanel.setBackground(primer_Color);
        
        nombre_Curso_JTextPane.setBackground(segundo_Color);
        nombre_Curso_JTextPane.setForeground(segundo_Color_Fuente);
        nombre_Curso_JTextPane.setCaretColor(segundo_Color_Fuente);
        
        nombre_Profesor_JTextPane.setBackground(tercer_Color);
        nombre_Profesor_JTextPane.setForeground(tercer_Color_Fuente);
        nombre_Profesor_JTextPane.setCaretColor(tercer_Color_Fuente);
        
        regresar_JButton.setBackground(primer_Color);
        descripcion_Curso_JTextPane.setForeground(primer_Color_Fuente);
        
    }
}
