/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles.estudiantes;

import interfaces.Componentes_Interface;
import java.awt.Color;
import java.awt.Image;

/**
 *
 * @author LENOVO
 */
public class Pagina_Curso_Informacion_Estudiante_Panel extends javax.swing.JPanel implements Componentes_Interface{

    private Titulo_Curso_Estudiante_Panel titulo_Curso_Estudiante_Panel;
    private Curso_Informacion_Estudiante_Panel sobre_El_Curso_Estudiante_Panel;
    
    public Pagina_Curso_Informacion_Estudiante_Panel(
            String id,
            String nombre_Curso,
            Image imagen_Curso,
            Color _primer_Color,
            Color _primer_Color_Fuente,
            Color _segundo_Color,
            Color _segundo_Color_Fuente,
            Color _tercer_Color,
            Color _tercer_Color_Fuente
        ) {
        
        initComponents();
        
        titulo_Curso_Estudiante_Panel = new Titulo_Curso_Estudiante_Panel(nombre_Curso,
        _segundo_Color, _tercer_Color, _tercer_Color_Fuente);
        
        sobre_El_Curso_Estudiante_Panel = new Curso_Informacion_Estudiante_Panel(imagen_Curso,_segundo_Color, _tercer_Color, 
                _tercer_Color_Fuente);
        
        Iniciar_Componentes();
        
        contenido_JPanel.setBackground(_primer_Color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido_JScrollPane = new javax.swing.JScrollPane();
        contenido_JPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1080, 630));
        setLayout(new java.awt.CardLayout());

        contenido_JScrollPane.setBorder(null);

        contenido_JPanel.setLayout(new javax.swing.BoxLayout(contenido_JPanel, javax.swing.BoxLayout.PAGE_AXIS));
        contenido_JScrollPane.setViewportView(contenido_JPanel);

        add(contenido_JScrollPane, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenido_JPanel;
    private javax.swing.JScrollPane contenido_JScrollPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Iniciar_Componentes() {
       
        contenido_JScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        contenido_JScrollPane.getHorizontalScrollBar().setUnitIncrement(15);
        
        contenido_JPanel.add(titulo_Curso_Estudiante_Panel);
        contenido_JPanel.add(sobre_El_Curso_Estudiante_Panel);
        
        Colorear_Componentes();
    }

    @Override
    public void Colorear_Componentes() {
       //No soportado
    }
}
