/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles.estudiantes;

import interfaces.Componentes_Interface;
import interfaces.Limpieza_Interface;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;


/**
 *
 * @author LENOVO
 */
public class Pagina_Curso_Estudiante_Panel extends javax.swing.JPanel implements Limpieza_Interface, Componentes_Interface{
    
    private static Pagina_Curso_Estudiante_Panel este;
    private Pagina_Curso_Informacion_Estudiante_Panel pagina_Curso_Informacion_Estudiante_Panel;
    private Pagina_Curso_Profesor_Estudiante_Panel pagina_Curso_Profesor_Estudiante_Panel;
    private static CardLayout layout;
    
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Pagina_Curso_Estudiante_Panel(String id,
            String nombre_Curso,
            String nombre_Profesor,
            Image imagen_Curso,
            Image imagen_Profesor,
            Color _primer_Color,
            Color _primer_Color_Fuente,
            Color _segundo_Color,
            Color _segundo_Color_Fuente,
            Color _tercer_Color,
            Color _tercer_Color_Fuente){
        
       initComponents();
       
       pagina_Curso_Informacion_Estudiante_Panel = new Pagina_Curso_Informacion_Estudiante_Panel(id, nombre_Curso, 
               imagen_Curso, _primer_Color, _primer_Color_Fuente,
               _segundo_Color, _segundo_Color_Fuente, _tercer_Color, _tercer_Color_Fuente);
       
       pagina_Curso_Profesor_Estudiante_Panel = new Pagina_Curso_Profesor_Estudiante_Panel(nombre_Curso, nombre_Profesor,
               imagen_Profesor, _primer_Color, _primer_Color_Fuente, _segundo_Color, 
               _segundo_Color_Fuente, _tercer_Color, _tercer_Color_Fuente);
        
       Iniciar_Componentes();
       
       este = this;
       layout = (CardLayout)this.getLayout();
       
       
        
    }
   
    
    public static void Mostrar_Informacion_Curso(){
        layout.show(este, "Informacion");
    }
    
    public static void Mostrar_Informacion_Profesor(){
        layout.show(este, "Profesor");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(1085, 630));
        setPreferredSize(new java.awt.Dimension(1085, 630));
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void Iniciar_Componentes() {
       
        this.add(pagina_Curso_Informacion_Estudiante_Panel, "Informacion");
        this.add(pagina_Curso_Profesor_Estudiante_Panel,"Profesor");
        Colorear_Componentes();
    }

    @Override
    public void Colorear_Componentes() {
        pagina_Curso_Informacion_Estudiante_Panel.Colorear_Componentes();
        pagina_Curso_Profesor_Estudiante_Panel.Colorear_Componentes();
    }
    
    @Override
    public void Limpiar() {
        
    }
}
