/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles.estudiantes;

import paneles.estudiantes.perfil.Perfil_Estudiante_Panel;
import paneles.estudiantes.tareas.Tareas_Estudiante_Panel;
import paneles.estudiantes.grupos.Grupos_Estudiante_Panel;
import paneles.estudiantes.chats.Chats_Estudiante_Panel;
import paneles.estudiantes.preguntas.Preguntas_Estudiante_Panel;
import paneles.estudiantes.avisos.Avisos_Estudiante_Panel;
import paneles.estudiantes.fechas.Fechas_Estudiante_Panel;
import courseroom.CourseRoom;
import paneles.generales.tablero.Acerca_General_Panel;
import paneles.generales.tablero.Reproductor_Musica_General_Panel;
import courseroom.CourseRoom_Frame;
import datos.colecciones.Lista_Pares;
import interfaces.Componentes_Interface;
import interfaces.Limpieza_Interface;
import datos.estructuras.Par;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.PixelGrabber;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import paneles.estudiantes.cursos.Cursos_Estudiante_Panel;
import paneles.estudiantes.desempeno_escolar.Desempeno_Escolar_Estudiante_Panel;

/**
 *
 * @author LENOVO
 */
public class Tablero_Estudiante_Panel extends javax.swing.JPanel implements Limpieza_Interface, Componentes_Interface{

    private static Image imagen_Usuario;
    
    private static Chats_Estudiante_Panel chats_Estudiante_Panel;
    private static Acerca_General_Panel acerca_De_Panel;
    private static Perfil_Estudiante_Panel perfil_Estudiante_Panel;
    private static Desempeno_Escolar_Estudiante_Panel desempeno_Escolar_Estudiante_Panel;
    private static Reproductor_Musica_General_Panel reproductor_Musica_Panel;
    private static Avisos_Estudiante_Panel avisos_Estudiante_Panel;
    private static Grupos_Estudiante_Panel grupos_Estudiante_Panel;
    private static Fechas_Estudiante_Panel fechas_Estudiante_Panel;
    private static Tareas_Estudiante_Panel tareas_Estudiante_Panel;
    private static Ajustes_Estudiante_Panel ajustes_Panel;
    private static Cursos_Estudiante_Panel cursos_Estudiante_Panel;
    private static Preguntas_Estudiante_Panel dudas_Estudiante_Panel;
    
    private static CardLayout layout;
    private Tiempo_Servidor tiempo_Servidor_Hilo;
    private volatile boolean tiempo_Servidor_Detenido;
    
    /**
     * Creates new form DashboardPanel
     */
    @SuppressWarnings({"CallToThreadStartDuringObjectConstruction", "OverridableMethodCallInConstructor"})
    public Tablero_Estudiante_Panel() {
        initComponents();
       
        Iniciar_Componentes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_JPanel = new javax.swing.JPanel();
        imagen_Perfil_JLabel = new javax.swing.JLabel();
        stats_JButton = new javax.swing.JButton();
        cursos_JButton = new javax.swing.JButton();
        tareas_JButton = new javax.swing.JButton();
        fechas_JButton = new javax.swing.JButton();
        avisos_JButton = new javax.swing.JButton();
        grupos_JButton = new javax.swing.JButton();
        chats_JButton = new javax.swing.JButton();
        reproductor_Musica_JButton = new javax.swing.JButton();
        acerca_De_JButton = new javax.swing.JButton();
        ajustes_JButton = new javax.swing.JButton();
        salir_JButton = new javax.swing.JButton();
        preguntas_JButton = new javax.swing.JButton();
        barra_Superior_JPanel = new javax.swing.JPanel();
        fecha_Hora_Servidor_JLabel = new javax.swing.JLabel();
        menu_JButton = new javax.swing.JButton();
        visualizador_JPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1260, 670));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1260, 670));

        menu_JPanel.setMaximumSize(new java.awt.Dimension(150, 2147483647));
        menu_JPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        menu_JPanel.setOpaque(false);
        menu_JPanel.setPreferredSize(new java.awt.Dimension(150, 630));
        menu_JPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen_Perfil_JLabel.setToolTipText("Mostrar Perfil Del Usuario.");
        imagen_Perfil_JLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagen_Perfil_JLabel.setMaximumSize(new java.awt.Dimension(150, 150));
        imagen_Perfil_JLabel.setMinimumSize(new java.awt.Dimension(150, 150));
        imagen_Perfil_JLabel.setOpaque(true);
        imagen_Perfil_JLabel.setPreferredSize(new java.awt.Dimension(150, 150));
        imagen_Perfil_JLabel.setRequestFocusEnabled(false);
        imagen_Perfil_JLabel.setVerifyInputWhenFocusTarget(false);
        imagen_Perfil_JLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen_Perfil_JLabelMouseClicked(evt);
            }
        });
        menu_JPanel.add(imagen_Perfil_JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        stats_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        stats_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/qualification_1.png"))); // NOI18N
        stats_JButton.setText("Stats");
        stats_JButton.setToolTipText("Mostrar Las Estadisticas & Desempeño Escolar Del Usuario.");
        stats_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stats_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stats_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        stats_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stats_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stats_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stats_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(stats_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        cursos_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        cursos_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/training.png"))); // NOI18N
        cursos_JButton.setText("Cursos");
        cursos_JButton.setToolTipText("Mostrar Cursos.");
        cursos_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cursos_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cursos_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        cursos_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursos_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cursos_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cursos_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(cursos_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 185, -1, -1));

        tareas_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        tareas_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/homework.png"))); // NOI18N
        tareas_JButton.setText("Tareas");
        tareas_JButton.setToolTipText("Mostrar Mis Tareas.");
        tareas_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tareas_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tareas_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        tareas_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tareas_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tareas_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tareas_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(tareas_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        fechas_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        fechas_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/schedule.png"))); // NOI18N
        fechas_JButton.setText("Fechas");
        fechas_JButton.setToolTipText("Mostrar El Calendario De Fechas.");
        fechas_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fechas_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fechas_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        fechas_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechas_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fechas_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fechas_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(fechas_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, -1, -1));

        avisos_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        avisos_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/bell.png"))); // NOI18N
        avisos_JButton.setText("Avisos");
        avisos_JButton.setToolTipText("Mostrar Mis Avisos.");
        avisos_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        avisos_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        avisos_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        avisos_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avisos_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                avisos_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                avisos_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(avisos_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        grupos_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        grupos_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/group-meeting.png"))); // NOI18N
        grupos_JButton.setText("Grupos");
        grupos_JButton.setToolTipText("Mostrar Mis Grupos.");
        grupos_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupos_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grupos_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        grupos_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grupos_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grupos_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grupos_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(grupos_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 325, -1, -1));

        chats_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        chats_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/online-chat.png"))); // NOI18N
        chats_JButton.setText("Chats");
        chats_JButton.setToolTipText("Mostrar Mis Chats.");
        chats_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chats_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chats_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        chats_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chats_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chats_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chats_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(chats_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        reproductor_Musica_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        reproductor_Musica_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/audio.png"))); // NOI18N
        reproductor_Musica_JButton.setText("Música");
        reproductor_Musica_JButton.setToolTipText("Reproducir Música.");
        reproductor_Musica_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reproductor_Musica_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reproductor_Musica_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        reproductor_Musica_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reproductor_Musica_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reproductor_Musica_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reproductor_Musica_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(reproductor_Musica_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 395, -1, -1));

        acerca_De_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        acerca_De_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/info.png"))); // NOI18N
        acerca_De_JButton.setText("Acerca");
        acerca_De_JButton.setToolTipText("Acerca De CourseRoom.");
        acerca_De_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        acerca_De_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acerca_De_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        acerca_De_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acerca_De_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acerca_De_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                acerca_De_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(acerca_De_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        ajustes_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        ajustes_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/settings.png"))); // NOI18N
        ajustes_JButton.setText("Ajustes");
        ajustes_JButton.setToolTipText("Configuraciones");
        ajustes_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ajustes_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ajustes_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        ajustes_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajustes_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajustes_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajustes_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(ajustes_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 465, -1, -1));

        salir_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        salir_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/exit-door.png"))); // NOI18N
        salir_JButton.setText("Salir");
        salir_JButton.setToolTipText("Cerrar Sesión.");
        salir_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        salir_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salir_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salir_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salir_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(salir_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 535, -1, -1));

        preguntas_JButton.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        preguntas_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/doubt.png"))); // NOI18N
        preguntas_JButton.setText("Asks");
        preguntas_JButton.setToolTipText("Configuraciones");
        preguntas_JButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        preguntas_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        preguntas_JButton.setPreferredSize(new java.awt.Dimension(150, 35));
        preguntas_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preguntas_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                preguntas_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                preguntas_JButtonMouseExited(evt);
            }
        });
        menu_JPanel.add(preguntas_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        barra_Superior_JPanel.setBackground(java.awt.Color.black);
        barra_Superior_JPanel.setMinimumSize(new java.awt.Dimension(1260, 40));
        barra_Superior_JPanel.setOpaque(false);
        barra_Superior_JPanel.setPreferredSize(new java.awt.Dimension(1260, 40));

        fecha_Hora_Servidor_JLabel.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        fecha_Hora_Servidor_JLabel.setForeground(java.awt.Color.white);
        fecha_Hora_Servidor_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fecha_Hora_Servidor_JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/clock_2.png"))); // NOI18N
        fecha_Hora_Servidor_JLabel.setToolTipText("Fecha & Hora Del Servidor");
        fecha_Hora_Servidor_JLabel.setMaximumSize(new java.awt.Dimension(127, 40));
        fecha_Hora_Servidor_JLabel.setMinimumSize(new java.awt.Dimension(127, 40));
        fecha_Hora_Servidor_JLabel.setPreferredSize(new java.awt.Dimension(127, 40));

        menu_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/menu.png"))); // NOI18N
        menu_JButton.setToolTipText("Mostrar/Ocultar Menú");
        menu_JButton.setBorder(null);
        menu_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_JButton.setMaximumSize(new java.awt.Dimension(40, 40));
        menu_JButton.setMinimumSize(new java.awt.Dimension(40, 40));
        menu_JButton.setPreferredSize(new java.awt.Dimension(40, 40));
        menu_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_JButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_JButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_JButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout barra_Superior_JPanelLayout = new javax.swing.GroupLayout(barra_Superior_JPanel);
        barra_Superior_JPanel.setLayout(barra_Superior_JPanelLayout);
        barra_Superior_JPanelLayout.setHorizontalGroup(
            barra_Superior_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_Superior_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fecha_Hora_Servidor_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barra_Superior_JPanelLayout.setVerticalGroup(
            barra_Superior_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_Superior_JPanelLayout.createSequentialGroup()
                .addGroup(barra_Superior_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_Hora_Servidor_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        visualizador_JPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        visualizador_JPanel.setName(""); // NOI18N
        visualizador_JPanel.setOpaque(false);
        visualizador_JPanel.setPreferredSize(new java.awt.Dimension(1110, 630));
        visualizador_JPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barra_Superior_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(visualizador_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(barra_Superior_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualizador_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void imagen_Perfil_JLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen_Perfil_JLabelMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            layout.show(visualizador_JPanel, "Perfil");
        }
    }//GEN-LAST:event_imagen_Perfil_JLabelMouseClicked

    private void menu_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            menu_JPanel.setVisible(!menu_JPanel.isVisible());
        }
    }//GEN-LAST:event_menu_JButtonMouseClicked

    private void menu_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_JButtonMouseEntered
        // TODO add your handling code here:
        menu_JButton.setBackground(CourseRoom.Segundo_Color());
    }//GEN-LAST:event_menu_JButtonMouseEntered

    private void menu_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_JButtonMouseExited
        // TODO add your handling code here:
        menu_JButton.setBackground(CourseRoom.Primer_Color());
    }//GEN-LAST:event_menu_JButtonMouseExited

    private void stats_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stats_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Desempeno_Escolar");
        }
    }//GEN-LAST:event_stats_JButtonMouseClicked

    private void stats_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stats_JButtonMouseEntered
        // TODO add your handling code here:
        stats_JButton.setBackground(CourseRoom.Tercer_Color());
        stats_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_stats_JButtonMouseEntered

    private void stats_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stats_JButtonMouseExited
        // TODO add your handling code here:
        stats_JButton.setBackground(CourseRoom.Segundo_Color());
        stats_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_stats_JButtonMouseExited

    private void cursos_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursos_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Cursos");
        }
    }//GEN-LAST:event_cursos_JButtonMouseClicked

    private void cursos_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursos_JButtonMouseEntered
        // TODO add your handling code here:
        cursos_JButton.setBackground(CourseRoom.Tercer_Color());
        cursos_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_cursos_JButtonMouseEntered

    private void cursos_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursos_JButtonMouseExited
        // TODO add your handling code here:
        cursos_JButton.setBackground(CourseRoom.Segundo_Color());
        cursos_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_cursos_JButtonMouseExited

    private void tareas_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tareas_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Tareas");
        }
        
    }//GEN-LAST:event_tareas_JButtonMouseClicked

    private void tareas_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tareas_JButtonMouseEntered
        // TODO add your handling code here:
        tareas_JButton.setBackground(CourseRoom.Tercer_Color());
        tareas_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_tareas_JButtonMouseEntered

    private void tareas_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tareas_JButtonMouseExited
        // TODO add your handling code here:
        tareas_JButton.setBackground(CourseRoom.Segundo_Color());
        tareas_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_tareas_JButtonMouseExited

    private void fechas_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechas_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Fechas");
        }
    }//GEN-LAST:event_fechas_JButtonMouseClicked

    private void fechas_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechas_JButtonMouseEntered
        // TODO add your handling code here:
        fechas_JButton.setBackground(CourseRoom.Tercer_Color());
        fechas_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_fechas_JButtonMouseEntered

    private void fechas_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechas_JButtonMouseExited
        // TODO add your handling code here:
        fechas_JButton.setBackground(CourseRoom.Segundo_Color());
        fechas_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_fechas_JButtonMouseExited

    private void avisos_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avisos_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Avisos");
        }
    }//GEN-LAST:event_avisos_JButtonMouseClicked

    private void avisos_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avisos_JButtonMouseEntered
        // TODO add your handling code here:
        avisos_JButton.setBackground(CourseRoom.Tercer_Color());
        avisos_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_avisos_JButtonMouseEntered

    private void avisos_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avisos_JButtonMouseExited
        // TODO add your handling code here:
        avisos_JButton.setBackground(CourseRoom.Segundo_Color());
        avisos_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_avisos_JButtonMouseExited

    private void grupos_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grupos_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Grupos");
        }
    }//GEN-LAST:event_grupos_JButtonMouseClicked

    private void grupos_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grupos_JButtonMouseEntered
        // TODO add your handling code here:
        grupos_JButton.setBackground(CourseRoom.Tercer_Color());
        grupos_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_grupos_JButtonMouseEntered

    private void grupos_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grupos_JButtonMouseExited
        // TODO add your handling code here:
        grupos_JButton.setBackground(CourseRoom.Segundo_Color());
        grupos_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_grupos_JButtonMouseExited

    private void chats_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chats_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Chats");
        }
    }//GEN-LAST:event_chats_JButtonMouseClicked

    private void chats_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chats_JButtonMouseEntered
        // TODO add your handling code here:
        chats_JButton.setBackground(CourseRoom.Tercer_Color());
        chats_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_chats_JButtonMouseEntered

    private void chats_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chats_JButtonMouseExited
        // TODO add your handling code here:
        chats_JButton.setBackground(CourseRoom.Segundo_Color());
        chats_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_chats_JButtonMouseExited

    private void reproductor_Musica_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reproductor_Musica_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Musica");
        }
    }//GEN-LAST:event_reproductor_Musica_JButtonMouseClicked

    private void reproductor_Musica_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reproductor_Musica_JButtonMouseEntered
        // TODO add your handling code here:
        reproductor_Musica_JButton.setBackground(CourseRoom.Tercer_Color());
        reproductor_Musica_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_reproductor_Musica_JButtonMouseEntered

    private void reproductor_Musica_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reproductor_Musica_JButtonMouseExited
        // TODO add your handling code here:
        reproductor_Musica_JButton.setBackground(CourseRoom.Segundo_Color());
        reproductor_Musica_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_reproductor_Musica_JButtonMouseExited

    private void acerca_De_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acerca_De_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Acerca_De");
        }
    }//GEN-LAST:event_acerca_De_JButtonMouseClicked

    private void acerca_De_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acerca_De_JButtonMouseEntered
        // TODO add your handling code here:
        acerca_De_JButton.setBackground(CourseRoom.Tercer_Color());
        acerca_De_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_acerca_De_JButtonMouseEntered

    private void acerca_De_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acerca_De_JButtonMouseExited
        // TODO add your handling code here:
        acerca_De_JButton.setBackground(CourseRoom.Segundo_Color());
        acerca_De_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_acerca_De_JButtonMouseExited

    private void ajustes_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajustes_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Ajustes");
        }
    }//GEN-LAST:event_ajustes_JButtonMouseClicked

    private void ajustes_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajustes_JButtonMouseEntered
        // TODO add your handling code here:
        ajustes_JButton.setBackground(CourseRoom.Tercer_Color());
        ajustes_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_ajustes_JButtonMouseEntered

    private void ajustes_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajustes_JButtonMouseExited
        // TODO add your handling code here:
        ajustes_JButton.setBackground(CourseRoom.Segundo_Color());
        ajustes_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_ajustes_JButtonMouseExited

    private void salir_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            
            CourseRoom_Frame.Cerrar_Sesion();
            this.Limpiar();
        }
    }//GEN-LAST:event_salir_JButtonMouseClicked

    private void salir_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir_JButtonMouseEntered
        // TODO add your handling code here:
        salir_JButton.setBackground(CourseRoom.Tercer_Color());
        salir_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_salir_JButtonMouseEntered

    private void salir_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir_JButtonMouseExited
        // TODO add your handling code here:
        salir_JButton.setBackground(CourseRoom.Segundo_Color());
        salir_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_salir_JButtonMouseExited

    private void preguntas_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preguntas_JButtonMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            Tablero_Estudiante_Panel.Mostrar_Vista("Preguntas");
        }
    }//GEN-LAST:event_preguntas_JButtonMouseClicked

    private void preguntas_JButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preguntas_JButtonMouseEntered
        // TODO add your handling code here:
        preguntas_JButton.setBackground(CourseRoom.Tercer_Color());
        preguntas_JButton.setForeground(CourseRoom.Tercer_Color_Fuente());
    }//GEN-LAST:event_preguntas_JButtonMouseEntered

    private void preguntas_JButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preguntas_JButtonMouseExited
        // TODO add your handling code here:
        preguntas_JButton.setBackground(CourseRoom.Segundo_Color());
        preguntas_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
    }//GEN-LAST:event_preguntas_JButtonMouseExited

   
    public static void Establecer_Colores(){
        try {
            Color primer_Color, segundo_Color, tercer_Color,primer_Color_Fuente, segundo_Color_Fuente, tercer_Color_Fuente;
            int maximo_auxiliar = 0;
            primer_Color = Color.BLACK;
            Lista_Pares<Integer, Color> lista_Colores = new Lista_Pares<>();
            PixelGrabber obtener_Pixeles = new PixelGrabber(imagen_Usuario, 0, 0, -1, -1, false);
            int largo_Imagen = imagen_Usuario.getWidth(null);
            int[] pixeles;
            int pixel,rojo,verde,azul,numero_Auxiliar,posicion;
            Color color;
            Par<Integer, Color> par;
            if (obtener_Pixeles.grabPixels()) {
                pixeles = (int[]) obtener_Pixeles.getPixels();
                for(int i = 0; i < pixeles.length; i++){
                    pixel = pixeles[i];
                    rojo = (pixel  & 0x00ff0000) >> 16;
                    verde = (pixel & 0x0000ff00) >> 8;
                    azul = pixel & 0x000000ff;
                    color = new Color(rojo,verde,azul);
                    par = lista_Colores.get_from_second(color);
            
                    if (par != null) { //existe
                        numero_Auxiliar = par.first()+ 1;
                        par.first(numero_Auxiliar);
                        if (numero_Auxiliar > maximo_auxiliar) {
                            primer_Color = color;
                            maximo_auxiliar = numero_Auxiliar;
                        }
                    } else {
                        lista_Colores.push_back(1, color);
                    }

                    i += CourseRoom.Random().nextInt(largo_Imagen+1) + largo_Imagen;
                }

                segundo_Color = primer_Color;
            
                int iteraciones = 0;
                if(lista_Colores.size() > 1){
                    
                    while(Math.abs(segundo_Color.getRGB() - primer_Color.getRGB()) < 3000000){
                        posicion = CourseRoom.Random().nextInt((int)lista_Colores.size()-1);
                        segundo_Color = lista_Colores.get(posicion).second();
                        iteraciones++;
                        if(iteraciones > 25){
                             while(primer_Color.getRGB() == segundo_Color.getRGB()){
                                posicion = CourseRoom.Random().nextInt((int)lista_Colores.size()-1);
                                segundo_Color = lista_Colores.get(posicion).second();
                            }
                             break;
                        }
                    }
                }
               
                tercer_Color = segundo_Color;
                if(lista_Colores.size() > 2){
                    iteraciones = 0;
                    
                    while(Math.abs(tercer_Color.getRGB() - primer_Color.getRGB()) < 3000000 || Math.abs(segundo_Color.getRGB() - tercer_Color.getRGB()) < 3000000){
                        posicion = CourseRoom.Random().nextInt((int)lista_Colores.size()-1);
                        tercer_Color = lista_Colores.get(posicion).second();
                        iteraciones++;
                        if(iteraciones > 50){
                            while(tercer_Color.getRGB() == primer_Color.getRGB() || tercer_Color.getRGB() == segundo_Color.getRGB()){
                                posicion = CourseRoom.Random().nextInt((int)lista_Colores.size()-1);
                                tercer_Color = lista_Colores.get(posicion).second();
                            }
                            break;
                        }
                    }
                }
                
                rojo = primer_Color.getRed();
                primer_Color_Fuente = (rojo >= 155) ? Color.BLACK : Color.WHITE;
                rojo = segundo_Color.getRed();
                segundo_Color_Fuente = (rojo >= 155) ? Color.BLACK : Color.WHITE;
                rojo = tercer_Color.getRed();
                tercer_Color_Fuente = (rojo >= 155) ? Color.BLACK : Color.WHITE;
                lista_Colores.clear();
                
                CourseRoom.Primer_Color(primer_Color);
                CourseRoom.Segundo_Color(segundo_Color);
                CourseRoom.Tercer_Color(tercer_Color);
                CourseRoom.Primer_Color_Fuente(primer_Color_Fuente);
                CourseRoom.Segundo_Color_Fuente(segundo_Color_Fuente);
                CourseRoom.Tercer_Color_Fuente(tercer_Color_Fuente);

                CourseRoom_Frame.Colorear(); 
                
                Colorear();
            }
            
        } catch (InterruptedException ex) {
            
        }
            
    }
    
    public static void Colorear(){
         
        acerca_De_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        ajustes_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        avisos_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        chats_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        cursos_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        fechas_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        grupos_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        stats_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        reproductor_Musica_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        salir_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        tareas_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        imagen_Perfil_JLabel.setForeground(CourseRoom.Segundo_Color_Fuente());
        preguntas_JButton.setForeground(CourseRoom.Segundo_Color_Fuente());
        acerca_De_JButton.setBackground(CourseRoom.Segundo_Color());
        ajustes_JButton.setBackground(CourseRoom.Segundo_Color());
        avisos_JButton.setBackground(CourseRoom.Segundo_Color());
        chats_JButton.setBackground(CourseRoom.Segundo_Color());
        cursos_JButton.setBackground(CourseRoom.Segundo_Color());
        fechas_JButton.setBackground(CourseRoom.Segundo_Color());
        grupos_JButton.setBackground(CourseRoom.Segundo_Color());
        stats_JButton.setBackground(CourseRoom.Segundo_Color());
        reproductor_Musica_JButton.setBackground(CourseRoom.Segundo_Color());
        salir_JButton.setBackground(CourseRoom.Segundo_Color());
        tareas_JButton.setBackground(CourseRoom.Segundo_Color());
        preguntas_JButton.setBackground(CourseRoom.Segundo_Color());
        menu_JButton.setBackground(CourseRoom.Primer_Color());

        fecha_Hora_Servidor_JLabel.setForeground(CourseRoom.Primer_Color_Fuente());

        fecha_Hora_Servidor_JLabel.setForeground(CourseRoom.Primer_Color_Fuente());
       
        perfil_Estudiante_Panel.Colorear_Componentes();
        avisos_Estudiante_Panel.Colorear_Componentes();
        tareas_Estudiante_Panel.Colorear_Componentes();
        chats_Estudiante_Panel.Colorear_Componentes();
        acerca_De_Panel.Colorear_Componentes();
        tareas_Estudiante_Panel.Colorear_Componentes();
        grupos_Estudiante_Panel.Colorear_Componentes();
        avisos_Estudiante_Panel.Colorear_Componentes();
        fechas_Estudiante_Panel.Colorear_Componentes();
        ajustes_Panel.Colorear_Componentes();
        dudas_Estudiante_Panel.Colorear_Componentes();
        cursos_Estudiante_Panel.Colorear_Componentes();
        desempeno_Escolar_Estudiante_Panel.Colorear_Componentes();
    }
    
    
    @Override
    public void Limpiar(){
        tareas_Estudiante_Panel.Limpiar();
        reproductor_Musica_Panel.Limpiar();
        chats_Estudiante_Panel.Limpiar();
        avisos_Estudiante_Panel.Limpiar();
        fechas_Estudiante_Panel.Limpiar();
        grupos_Estudiante_Panel.Limpiar();
        cursos_Estudiante_Panel.Limpiar();
        perfil_Estudiante_Panel.Limpiar();
        desempeno_Escolar_Estudiante_Panel.Limpiar();
        
    }
    
    public static void Agregar_Vista(Component componente, String llave){
        visualizador_JPanel.add(llave,componente);
    }
    
    public static void Mostrar_Vista(String llave){
        layout.show(visualizador_JPanel, llave);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton acerca_De_JButton;
    private static javax.swing.JButton ajustes_JButton;
    private static javax.swing.JButton avisos_JButton;
    private javax.swing.JPanel barra_Superior_JPanel;
    private static javax.swing.JButton chats_JButton;
    private static javax.swing.JButton cursos_JButton;
    private static javax.swing.JLabel fecha_Hora_Servidor_JLabel;
    private static javax.swing.JButton fechas_JButton;
    private static javax.swing.JButton grupos_JButton;
    private static javax.swing.JLabel imagen_Perfil_JLabel;
    private static javax.swing.JButton menu_JButton;
    private javax.swing.JPanel menu_JPanel;
    private static javax.swing.JButton preguntas_JButton;
    private static javax.swing.JButton reproductor_Musica_JButton;
    private static javax.swing.JButton salir_JButton;
    private static javax.swing.JButton stats_JButton;
    private static javax.swing.JButton tareas_JButton;
    private static javax.swing.JPanel visualizador_JPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the imagen_Usuario
     */
    public static Image Imagen_Usuario() {
        return imagen_Usuario;
    }
    
    
    public static void Imagen_Usuario(Image _imagen_Usuario) {
        imagen_Usuario = _imagen_Usuario;
        ImageIcon imagen_Perfil = new ImageIcon(imagen_Usuario.getScaledInstance(175,175, Image.SCALE_SMOOTH));
        imagen_Perfil_JLabel.setIcon(imagen_Perfil);
        int ancho_Imagen = Perfil_Estudiante_Panel.Obtener_Imagen_Perfil_JLabel().getPreferredSize().width;
        int largo_Imagen = Perfil_Estudiante_Panel.Obtener_Imagen_Perfil_JLabel().getPreferredSize().height;
        ImageIcon icono = new ImageIcon(imagen_Perfil.getImage().getScaledInstance(ancho_Imagen,largo_Imagen,Image.SCALE_SMOOTH));
        Perfil_Estudiante_Panel.Obtener_Imagen_Perfil_JLabel().setIcon(icono);
        imagen_Perfil.getImage().flush();
    }

    @Override
    public void Iniciar_Componentes() {
         try {
            
            tiempo_Servidor_Detenido = true;
            System.out.println("Dashboard -> Getting Image From https://i.pravatar.cc/450");
            URL url_Imagen = new URL("https://i.pravatar.cc/450");
            imagen_Usuario = ImageIO.read(url_Imagen);
            Image imagen_Redimensionada = imagen_Usuario.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            ImageIcon icono_Imagen = new ImageIcon(imagen_Redimensionada);
            imagen_Perfil_JLabel.setIcon(icono_Imagen);
            icono_Imagen.getImage().flush();
            imagen_Redimensionada.flush();
            perfil_Estudiante_Panel = new Perfil_Estudiante_Panel();
            visualizador_JPanel.add("Perfil",perfil_Estudiante_Panel);
            
            desempeno_Escolar_Estudiante_Panel = new Desempeno_Escolar_Estudiante_Panel();
            visualizador_JPanel.add("Desempeno_Escolar",desempeno_Escolar_Estudiante_Panel);
            
            chats_Estudiante_Panel = new Chats_Estudiante_Panel();
            visualizador_JPanel.add("Chats", chats_Estudiante_Panel);
            
            grupos_Estudiante_Panel = new Grupos_Estudiante_Panel();
            visualizador_JPanel.add("Grupos", grupos_Estudiante_Panel);

            tareas_Estudiante_Panel = new Tareas_Estudiante_Panel();
            visualizador_JPanel.add("Tareas",tareas_Estudiante_Panel);
            
            fechas_Estudiante_Panel = new Fechas_Estudiante_Panel();
            visualizador_JPanel.add("Fechas",fechas_Estudiante_Panel);
            
            avisos_Estudiante_Panel = new Avisos_Estudiante_Panel();
            visualizador_JPanel.add("Avisos",avisos_Estudiante_Panel);
            
            acerca_De_Panel = new Acerca_General_Panel();
            visualizador_JPanel.add("Acerca_De",acerca_De_Panel);
            
            reproductor_Musica_Panel = new Reproductor_Musica_General_Panel();
            visualizador_JPanel.add("Musica",reproductor_Musica_Panel);
            
            ajustes_Panel = new Ajustes_Estudiante_Panel();
            visualizador_JPanel.add("Ajustes",ajustes_Panel);
            
            dudas_Estudiante_Panel = new Preguntas_Estudiante_Panel();
            visualizador_JPanel.add("Preguntas", dudas_Estudiante_Panel);
            
            cursos_Estudiante_Panel = new Cursos_Estudiante_Panel();
            visualizador_JPanel.add("Cursos", cursos_Estudiante_Panel);
            
            layout = (CardLayout) visualizador_JPanel.getLayout();
            
            tiempo_Servidor_Hilo = new Tiempo_Servidor();
            tiempo_Servidor_Hilo.start();
            
            
        } catch (MalformedURLException ex) {
            
        } catch (IOException ex) {
            
        } 
    }

    @Override
    public void Colorear_Componentes() {
        Colorear();
    }
    
    public class Tiempo_Servidor extends Thread{
    

        public Tiempo_Servidor(){
        }

        @Override
        @SuppressWarnings("SleepWhileInLoop")
        public void run(){
            Date fecha;
            SimpleDateFormat formato_Fecha = new SimpleDateFormat("EEEE dd/MM/yyyy hh:mm:ss a");
            String tiempo;
            while(tiempo_Servidor_Detenido){
                
                try {
                    fecha = new Date();
                    tiempo = formato_Fecha.format(fecha);
                    fecha_Hora_Servidor_JLabel.setText(tiempo);
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    
                    
                }
            }
        }

    }
}
